### ISSUE TITLE
Failing example not presented in PHP 7.0.10

### ISSUE THREAD

**Issue by jon-acker** [phpspec/phpspec#1004]
Something appears to be wrong with the formatter for failing example on PHP 7.0.10 (on both OSX and Linux, both bash and fish shells). On a failed example using -fpretty I get this:
![screen shot 2016-09-22 at 11 42 26](https://cloud.githubusercontent.com/assets/956800/18745434/0b2748b2-80ba-11e6-9e86-a8c3314c13b6.png)

And using default progress bar I get:
![screen shot 2016-09-22 at 11 43 05](https://cloud.githubusercontent.com/assets/956800/18745369/c64114ee-80b9-11e6-9e61-0c80f587cef1.png)

**Comment by ciaranmcnulty** [comment]
What version are you using?

**Comment by jon-acker** [comment]
disappeared after reinstalled :)
