### ISSUE TITLE
Personal templates break the test suite

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1008]
Not sure how to resolve this but opening an issue as an FAQ

If a user has personal templates in `~/.phpspec` the Behat features relating to code generation will fail, because those templates will be used

**Comment by stof** [comment]
Maybe make Behat overwrite the ``$HOME`` variable when launching the phpspec subprocess, to make it point to a folder controlled by Behat ? Btw, this would allow us to write a scenario covering the personal template feature, without erasing your own personal templates.

**Comment by ciaranmcnulty** [comment]
Great idea @stof !

**Comment by pamil** [comment]
I tried to implement the solution proposed by @stof, but unfortunately Behat does not launch any subprocesses in order to run `phpspec`, it uses `CommandTester` from `symfony/console` instead.
