### ISSUE TITLE
shouldThrow pass if ErrorException thrown

### ISSUE THREAD

**Issue by nightlinus** [phpspec/phpspec#1013]
I suppose this scenario is describing bug, can somebody give me the cue where to find related code? ThrowMatcher::verifyPositive is not executed at all.

Scenario: Throwing an exception during construction with warning inside when beConstructedWith specifies valid parameters
    Given the spec file "spec/Runner/ExceptionExample3/MarkdownSpec.php" contains:
      """
      <?php

      namespace spec\Warning\ExceptionExample;

      use PhpSpec\ObjectBehavior;
      use Prophecy\Argument;

      class MarkdownSpec extends ObjectBehavior
      {
          function let()
          {
              $this->shouldThrow()->duringInitialization();
          }
      }

      """
    And the class file "src/Runner/ExceptionExample3/Markdown.php" contains:
      """
      <?php

      namespace Warning\ExceptionExample;

      class Markdown
      {
          public function __construct($param)
          {
              trigger_error('Warning', E_USER_WARNING);
          }
      }

      """
    When I run phpspec
    Then the suite should not pass

**Comment by jameshalsall** [comment]
The above doesn't make sense, you aren't telling PhpSpec that `Markdown` should be constructed with an argument, but your `Markdown` class expects 1 argument in the constructor.

Also, I don't think using `let()` is the correct place to do that, you should have an example in your spec specifically for verifying that the exception is thrown.

**Comment by nightlinus** [comment]
I am sorry not so clear test. Let me clarify issue:
  Scenario: Throwing an exception during method with warning inside
    Given the spec file "spec/Runner/ExceptionExample3/MarkdownSpec.php" contains:
      """
      <?php

      namespace spec\Warning\ExceptionExample;

      use PhpSpec\ObjectBehavior;
      use Prophecy\Argument;

      class WarningExampleSpec extends ObjectBehavior
      {
          function it_throws_exception()
          {
              $this->shouldThrow()->during('triggerWarning');
          }
      }

      """
    And the class file "src/Runner/ExceptionExample3/Markdown.php" contains:
      """
      <?php

      namespace Warning\ExceptionExample;

      class WarningExample
      {
          public function triggersWarning()
          {
              trigger_error('Warning', E_USER_WARNING);
          }
      }

      """
    When I run phpspec
    Then the suite should not pass
