### ISSUE TITLE
PHPSpec fails when creating mock examples

### ISSUE THREAD

**Issue by ghost** [phpspec/phpspec#1019]
I'm new to the world of BDD and I am keen to get going, but I don't quite understand why my specs fail when I'm allowing PHPSec to write the code for me? Also, I would like to add PHPSpec can't read the code from the src folder and keeps asking me if I would like to create it. I think this is strange behaviour.

I'm using the latest version of PHPSpec from Composer.

**Comment by roukmoute** [comment]
What is your error?
Could you give your example?
If you use psr-4, have you set it?

**Comment by fsociety79** [comment]
The PHPSpec runner fails informing me of broken tests when I'm following the tutorial here:
http://www.phpspec.net/en/stable/manual/let-and-letgo.html

**Comment by roukmoute** [comment]
This is not a tutorial but only examples for differents situations.
This is why it is important to give us a concrete example of what you doing, is it on github?
Have you previous tests it work?

**Comment by fsociety79** [comment]
The code I used (please note that I ran PHPSpec twice as PHPSpec asks to complete the code on the first time round):
phpspec desc DescribeFileSystemLogger
phpspec run
phpspec run

**Comment by unfunco** [comment]
Can you post the `autoload` section of your `composer.json`, and if you have one, `your `phpspec.yml`?

**Comment by fsociety79** [comment]
C:\Users\Julian\Downloads>vendor\bin\phpspec desc FileSystemLogger
Specification for FileSystemLogger created in C:\Users\Julian\Downloads\spec\FileSystemLoggerSpec.php.


C:\Users\Julian\Downloads>vendor\bin\phpspec run
FileSystemLogger
  11  - it is initializable
      class FileSystemLogger does not exist.

/  skipped: 0%  /  pending: 0%  /  passed: 0%   /  failed: 0%   / broken: 100%  /  1 examples
1 specs
1 example (1 broken)
65ms


  Do you want me to create `FileSystemLogger` for you?
                                                                         [Y/n]

Class FileSystemLogger created in C:\Users\Julian\Downloads\src\FileSystemLogger.php.



  [PhpSpec\Process\Prerequisites\PrerequisiteFailedException]
  The type FileSystemLogger was generated but could not be loaded. Do you need to configure an autoloader?


run [-f|--format FORMAT] [--stop-on-failure] [--no-code-generation] [--no-rerun] [--fake] [-b|--bootstrap BOOTSTRAP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command> [<spec>]

**Comment by unfunco** [comment]
> Do you need to configure an autoloader?

To try and diagnose quickly, add the following to your `composer.json`:

```json
"autoload": {
    "psr-0": {
        "": "src/"
    }
}
```

Then run `composer update`, and then try `vendor\bin\phpspec run` again. If that fixes the issue, you have a misconfigured autoloader. I'm almost certain there's no issue here, it looks like misconfiguration.

If you follow these in order then you should be up and running:

1. http://www.phpspec.net/en/stable/manual/installation.html
2. http://www.phpspec.net/en/stable/manual/getting-started.html

**Comment by fsociety79** [comment]
Contents of composer.json file:
{
    "require": {
        "phpspec/phpspec": "^3.1"
    },
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    }
}

I'm still getting the following error:
C:\Users\Julian\Downloads>vendor\bin\phpspec run
FileSystemLogger
  11  - it is initializable
      class FileSystemLogger does not exist.

/  skipped: 0%  /  pending: 0%  /  passed: 0%   /  failed: 0%   / broken: 100%  /  1 examples
1 specs
1 example (1 broken)
65ms


  Do you want me to create `FileSystemLogger` for you?
                                                                         [Y/n]
y

  File "FileSystemLogger.php" already exists. Overwrite?
                                                                         [y/N]
y

Class FileSystemLogger created in C:\Users\Julian\Downloads\src\FileSystemLogger.php.



  [PhpSpec\Process\Prerequisites\PrerequisiteFailedException]
  The type FileSystemLogger was generated but could not be loaded. Do you need to configure an autoloader?


run [-f|--format FORMAT] [--stop-on-failure] [--no-code-generation] [--no-rerun] [--fake] [-b|--bootstrap BOOTSTRAP] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-c|--config CONFIG] [--] <command> [<spec>]

**Comment by unfunco** [comment]
Interesting, I thought I had just replicated the issue:

<img width="1389" alt="screen shot 2016-10-28 at 17 34 16" src="https://cloud.githubusercontent.com/assets/1716636/19814146/ebe9dfcc-9d34-11e6-9d71-44d6025e82e8.png">

But that happened because I had a custom template as I'm currently looking at #1018 – when I removed my custom template it worked as expected.

<img width="1389" alt="screen shot 2016-10-28 at 17 34 32" src="https://cloud.githubusercontent.com/assets/1716636/19814200/21489398-9d35-11e6-89bc-64fd49cda440.png">

Have you configured a custom template in your home directory? (e.g. `class.tpl`) – if not, could you post the content of what is being automatically generated in `FileSystemLogger.php`?

**Comment by ciaranmcnulty** [comment]
What happens if you remove the trailing slash on src and do a composer update before trying again?

**Comment by unfunco** [comment]
Ah? That [dang Windows](https://www.youtube.com/watch?v=8TCxE0bWQeQ) again?

**Comment by fsociety79** [comment]
I'm getting even more strange behaviour now. When I execute 'phpspec run' it gets stuck in a loop.

Here's the contents of composer.json:
```
{
    "require": {
        "phpspec/phpspec": "^3.1"
    },
    "autoload": {
        "psr-0": {
        "": "src/"
        }
    }
}
```

Here's the contents of spec/FileSystemLoggerSpec.php:
```
<?php

namespace spec;

use FileSystemLogger;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class FileSystemLoggerSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType(FileSystemLogger::class);
    }
}
```

Here's the contents of FileSystemLogger.php:
```
<?php

class FileSystemLogger
{
}
```

**Comment by ciaranmcnulty** [comment]
What happens if you remove the trailing slash on src?
