### ISSUE TITLE
ReadMe in MarkDown

### ISSUE THREAD

**Issue by Harincka** [phpspec/phpspec#1028]
Hi, 
I propose to update the README.rst to README.md for more readability.
A PR is prepared for the issue.

**Comment by ciaranmcnulty** [comment]
In what ways do you think it will be more readable?

**Comment by Harincka** [comment]
I'm sorry for that, my teacher ask me to change a project on github for trying to contribute in a project. I saw a lot of a project which had .md. I don't know why it will be better than .rst, that is just a proposition. 

Sorry about the disagreement.

**Comment by ciaranmcnulty** [comment]
I'm genuinely asking! No disagreement ;-)
