### ISSUE TITLE
Interface double doesn't support inheritance

### ISSUE THREAD

**Issue by tobiassjosten** [phpspec/phpspec#1045]
I've running into a problem testing a class which depends on an interface, which in turn inherits from another interface. The class uses methods from both interfaces. When I stub and inject the child interface however, phpspec creates a double which lacks the inheritance and thus complains about undefined methods.

I made an example if that helps make it clearer: https://github.com/tobiassjosten/phpspecinterfaceinheritance

Am I doing something wrong? It feels like a common scenario, so maybe I'm just missing a feature for the doubles?

**Comment by unfunco** [comment]
According to the example you have provided, both of your interfaces are disparate. You have a `Feature` interface and a `BusinessObjective` interface, and both are standalone, I can't see any inheritance in the examples you have provided.

**Comment by unfunco** [comment]
I have opened a PR to your sample repo which you might want to take a look at to see if it helps with your issue: https://github.com/tobiassjosten/phpspecinterfaceinheritance/pull/1

**Comment by tobiassjosten** [comment]
Hah… Sorry for wasting your time – that's entirely correct. With the inheritance actually in place it works as expected. Now to figure out why it doesn't, in my actual project.

Thanks!

**Comment by unfunco** [comment]
Not a problem! Feel free to come back if there are still some issues you're wrestling with, thanks for closing the issue. 👍
