### ISSUE TITLE
Strict standards: Declaration of Double\... should be compatible with ...

### ISSUE THREAD

**Issue by DavidGarciaCat** [phpspec/phpspec#1053]
Hello,

Recently I've added a new Spec to the project I am working, and - althrough all Specs are returning green status - I get this error:

`src/...`
```php
    public function __construct(CacheManager $cacheManager, \Memcached $memcached)
    {
        $this->cacheManager = $cacheManager;
        $this->memcached = $memcached;
    }
```

`spec/...`
```php
    function let(CacheManager $cacheManager, \Memcached $memcached)
    {
        $this->beConstructedWith($cacheManager, $memcached);
    }
```

`shell`
```
...

PHP Strict standards:  Declaration of Double\Memcached\P8::getByKey() should be compatible with Memcached::getByKey($server_key, $key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL) in .../vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2

Strict standards: Declaration of Double\Memcached\P8::getByKey() should be compatible with Memcached::getByKey($server_key, $key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL) in .../vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2

...
```

Due all specs are returning green status, makes no sense to me to get this output.

Ideas?

Thanks for your time!

**Comment by stof** [comment]
Well, it looks like the Memcached mock for ``getByKey`` does not match the signature of the parent class. Please report this to Prophecy (and provide the versions for Prophecy, PHP and memcached)

**Comment by DavidGarciaCat** [comment]
Done - new issue reported and environment details added here https://github.com/phpspec/prophecy/issues/310

**Comment by stof** [comment]
OK, looking at what ``ReflectionMethod('Memcached', 'getByKey')`` shows me, it has nothing to do with a ``Memcached::getByKey($server_key, $key, $cache_cb = NULL, &$cas_token = NULL, &$udf_flags = NULL)`` signature. The reflection API knows about ``Memcached::getByKey($server_key, $key, $cache_cb = NULL, $get_flags = NULL)`` instead. So this is a bug in ext-memcached

**Comment by DavidGarciaCat** [comment]
So... should I just ignore that output (at least, for now) due `PHPSpec` returns green status everywhere? 😕

**Comment by stof** [comment]
hmm sorry no, this is the result when using 3.0-beta1, which is the version I got in the ppa. I need to check again what happens.

**Comment by stof** [comment]
PhpSpec being green is probably due to the error_reporting level not including ``E_STRICT`` (which is not part of ``E_ALL`` on PHP 5.5)

**Comment by ciaranmcnulty** [comment]
Because this is reported against Prophecy I'll close here
