### ISSUE TITLE
Error __clone method called on non-object

### ISSUE THREAD

**Issue by Mrkisha** [phpspec/phpspec#1054]
I'm trying to spec Symfony command and I want to have formated output with SymfonyStyle

```php
<?php

namespace Acme\AppBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Style\SymfonyStyle;

class SomeCommand extends ContainerAwareCommand
{
    //....
    protected function execute(InputInterface $input, OutputInterface $output)
    {
        $io = new SymfonyStyle($input, $output);

        $io->title('Feed import initiated');
    }
}
```

```php
<?php

namespace spec\Acme\AppBundle\Command;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;
use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\BufferedOutput;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class SomeCommandSpec extends ObjectBehavior
{
    //...
    function it_fetches_social_feeds(
        ContainerInterface $container,
        InputInterface $input,
        OutputInterface $output,
        SymfonyStyle $symfonyStyle
    ) {
        // With options
        $input->bind(Argument::any())->shouldBeCalled();
        $input->hasArgument('command')->shouldBeCalled();
        $input->isInteractive()->shouldBeCalled();
        $input->validate()->shouldBeCalled();

        $symfonyStyle->title(Argument::any())->shouldBeCalled();

        $this->setContainer($container);
        $this->run($input, $output);
    }
}
```

but I'm getting this error:
```php
exception [err:Error("__clone method called on non-object")] has been thrown.
 0 vendor/symfony/symfony/src/Symfony/Component/Console/Style/SymfonyStyle.php:50
   throw new PhpSpec\Exception\ErrorException("__clone method called on ...")
 1 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:866
   Symfony\Component\Console\Command\Command->run([obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
 2 vendor/symfony/symfony/src/Symfony/Component/Console/Application.php:193
   Symfony\Component\Console\Application->doRunCommand([obj:PhpSpec\Console\Command\RunCommand], [obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
 3 vendor/phpspec/phpspec/src/PhpSpec/Console/Application.php:102
   Symfony\Component\Console\Application->doRun([obj:Symfony\Component\Console\Input\ArgvInput], [obj:Symfony\Component\Console\Output\ConsoleOutput])
 4 vendor/phpspec/phpspec/bin/phpspec:26
   Symfony\Component\Console\Application->run()
 5 vendor/phpspec/phpspec/bin/phpspec:28
   {closure}("3.2.2")
```

on line 50 of SymfonyStyle is:

```php
public function __construct(InputInterface $input, OutputInterface $output)
{
    $this->input = $input;
    /* line 50 */ $this->bufferedOutput = new BufferedOutput($output->getVerbosity(), false, clone $output->getFormatter());
    // Windows cmd wraps lines as soon as the terminal width is reached, whether there are following chars or not.
    $this->lineLength = min($this->getTerminalWidth() - (int) (DIRECTORY_SEPARATOR === '\\'), self::MAX_LINE_LENGTH);

    parent::__construct($output);
}
```

and phpspec is complainig about
```php
clone $output->getFormatter()
```

Am I doing something wrong, or am I missing something?

**Comment by jakzal** [comment]
This is one of reasons why you shouldn't stub/mock 3rd party classes. You're only making assumptions how these classes work since you didn't write them. You're getting the assumptions wrong hence the error. Even if you got the assumptions right you have no guarantees they'll always be true.

Solution: don't stub your command's collaborators. write and integration test for the command instead (not with phpspec). The command should be rather short (just like controllers) and only delegate to the model/service layer. This will make your integration test rather simple.

**Comment by Mrkisha** [comment]
@jakzal

That is what I've ended up doing it. I'm stil leveling up my TDD&BDD skills.

I've seen some open source projects (sylius) write phpspecs for their commands and you mentioned integration tests. I'm confused, which way shoul i go?

**Comment by mheki** [comment]
@Mrkisha completely agree with Jakub, there is no need to use phpspec for your command if you delegate the logic to a service (which you can spec but then you test only your code). 
There is a rule which you can follow `Don't test what you don't own`. 
If you need to test it use integration tests instead.

**Comment by jakzal** [comment]
@mheki the rule is `Don't mock what you don't own` ;) most of the time it's worth to test the integration with 3rd party stuff.

**Comment by mheki** [comment]
@jakzal I need a cup of coffee this morning 😆

**Comment by Mrkisha** [comment]
@jakzal 

I've hread this so many times `Don't mock what you don't own`. Does this mean when ever you have 3rd  party clode in you method, you should only do integration tests?

**Comment by ciaranmcnulty** [comment]
@Mrkisha yes, which will drive you towards decoupling your objects 

If you have an object that has a mixture of domain logic and library interactions, you'll split it into an object that has domain logic (+ is unit tested) that interacts with an interface you define (that is mocked in the unit test), plus an adapter object that translates your interface into the underlying library, that you can integration test.

The advantage is that this introduces a nice extension point for when you start using a different library later
