### ISSUE TITLE
Unable to test preUpdate event listener

### ISSUE THREAD

**Issue by BentCoder** [phpspec/phpspec#1055]
Whether I enable/disable lines in `MessageEventListenerSpec` the test seems to be passing. Please someone tell me how I can test this. Any example will be much apperited or a link.

Thanks

NOTE: The listener itself works fine so there is nothing wrong there.

**PHPSPEC**

```
namespace ........;

use Doctrine\ORM\Event\PreUpdateEventArgs;
use My\Bundle\Entity\Hello;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class MessageEventListenerSpec extends ObjectBehavior
{
    function it_should_whatever(
        PreUpdateEventArgs $event
    ) {
//        $hello = new Hello();
//        $old = 'Old hello';
//        $new = 'New hello';
//
//        $event->getObject()->willReturn($hello);
//        $event->hasChangedField('message')->willReturn(true);
//        $event->getOldValue('message')->willReturn($old);
//        $event->getNewValue('message')->willReturn($new);

        $this->preUpdate($event);
    }
}
```

**EVENT LISTENER**

```
namespace ........;

use Doctrine\ORM\Event\PreUpdateEventArgs;
use My\Bundle\Entity\Hello;
use PhpSpec\ObjectBehavior;

class MessageEventListener
{
    /**
     * @param PreUpdateEventArgs $event
     */
    public function preUpdate(PreUpdateEventArgs $event)
    {
        $entity = $event->getObject();
        if ($entity instanceof Hello) {
            if ($event->hasChangedField('message')) {
                if ($event->getOldValue('message') != $event->getNewValue('message')) {
                    $this->callPrivateMethod(......);
                }
            }
        }
    }
}
```

**Comment by stof** [comment]
The issue is that you don't make any assertion in your spec. So there is no way for it to fail

**Comment by BentCoder** [comment]
Could you please show me a small example so that I can complete it?

**Comment by Sam-Burns** [comment]
What is `callPrivateMethod` supposed to do?

**Comment by ciaranmcnulty** [comment]
Examples that specify behaviour:
http://www.phpspec.net/en/stable/manual/getting-started.html#specifying-behaviour

**Comment by BentCoder** [comment]
@Sam-Burns nothing much so you can assume that it is not there! (Something like below)

```
private function callPrivateMethod($message)
{
   return str_replace('...', '...', $message);
}
```

**Comment by Sam-Burns** [comment]
Well, would it make sense for your spec to say `$this->preUpdate($event)->shouldBe('expected string');`?

**Comment by BentCoder** [comment]
@Sam-Burns I think I directed you wrong. It does this:

```
private function callPrivateMethod($message)
{
   // Modify message ....
   $entity->setMessage($message);
   // That's it! No return
}
```

**Comment by Sam-Burns** [comment]
Then try something like `$entity->setSomething('xyz')-> shouldHaveBeenCalled();` at the end of your test, maybe?

**Comment by BentCoder** [comment]
@Sam-Burns If all the `if` statements `true` then the test **should not pass** because I'm not testing `$entity->set...` lines at all although I'm (the listener) calls those lines. Shouldn't it fail? That's the root of my problem here. Elsewhere (other tests - not in event listeners), spec would raise error saying that `expected calls are .... but these were called ...`.

 @stof What do you exactly mean by "... you don't make any assertion in your spec."? Do you mean the `->willReturn(...)` lines I'm using in my spec above are not "assertion"?

**Comment by avant1** [comment]
@BentCoder `will` calls are not assertions. They are predictions. Line
```php
$event->hasChangedField('message')->willReturn(true);
```

says that when method `$event->hasChangedField()` with argument `'message'` is called (in your event listener code) then it will return `true`.
Assertions methods start with `should` (like `shouldReturn`, `shouldBeCalled`).

If I understand your question correctly, you expect that since no prediction calls (starting from `will`) on `$entity` were made then spec should fail.
But in your spec you create `$entity` by hand:
```php
$hello = new Hello();
```

So it is not special `phpspec` object, it is just instance of `Hello` class. You cannot make predictions on it using `$hello->foo()->willReturn('bar')`. And `phpspec` does not track calls on objects created manually.

If you want to check that some calls on `$entity` were made you should pass it as argument to the example:
```php
class MessageEventListenerSpec extends ObjectBehavior
{
    function it_should_whatever(
        PreUpdateEventArgs $event,
        Hello $entity //<---------------
    ) {
        $old = 'Old hello';
        $new = 'New hello';

        $event->getObject()->willReturn($entity);
        $event->hasChangedField('message')->willReturn(true);
        $event->getOldValue('message')->willReturn($old);
        $event->getNewValue('message')->willReturn($new);

        $entity->setMessage($new)->shouldBeCalled();

        $this->preUpdate($event);
    }
}
```

And somewhere in event listener:
```php
$entity->setMessage($event->getNewValue('message'));
```

**Comment by avant1** [comment]
BTW there is an issue for similar situations which describes how we can improve usage experience for newcomers: #627

**Comment by BentCoder** [comment]
@avant1 I already tried `Hello $entity //<---------------` version as well but nothing changed.

The test below will pass all times which is to me wrong or phpspec works in a strange way or I'm missing something.

```
namespace ........;

use Doctrine\ORM\Event\PreUpdateEventArgs;
use My\Bundle\Entity\Hello;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class MessageEventListenerSpec extends ObjectBehavior
{
    function it_should_whatever(
        PreUpdateEventArgs $event,
        Hello $entity
    ) {
        // Whether I add or remove any of these lines, the test passes either way!
        // $event->getObject()->shouldBeCalled()->willReturn($entity);
        // $event->getObject()->shouldBeCalled();
        // $event->getObject()->willReturn($entity);

        $this->preUpdate($event);
    }
}
```

```
namespace ........;

use Doctrine\ORM\Event\PreUpdateEventArgs;
use My\Bundle\Entity\Hello;
use PhpSpec\ObjectBehavior;

class MessageEventListener
{
    /**
     * @param PreUpdateEventArgs $event
     */
    public function preUpdate(PreUpdateEventArgs $event)
    {
        $entity = $event->getObject();
    }
}
```

**Comment by BentCoder** [comment]
OK. I got it now. @avant1 Thanks for the example and very descriptive answer.
