### ISSUE TITLE
How to configure with global namespace when using psr-4?

### ISSUE THREAD

**Issue by thisleenoble** [phpspec/phpspec#1056]
The documentation states that it's possible to configure PHPSpec without using a namespace but just omitting the namespace: property form the yml file. It doesn't describe any issues with doing that when you're using a psr-4 autoloader.
Using Spec in an established proprietary framework with legacy classes (for now) in a non-standard directory I am unable to get Spec to run without this error:
```
[InvalidArgumentException]                        
  PSR4 prefix doesn't match given class namespace. 
```
If I define a non-null namespace it's all fine but I don't want to do that at this stage. Is there a way to do this or does the documentation need updating to make it clearer that this is not possible?

I've detailed my issue more expansively on this StackOverflow post: http://stackoverflow.com/questions/41753955/how-if-possible-to-configure-phpspec-with-no-namespace-and-psr-4

Apologies if I've used incorrect terminology here and there. I'm only just starting out in my use of Spec so am profoundly ignorant about most of it.

**Comment by unfunco** [comment]
If I'm understanding you correctly, what you're wanting to do is possible, with the following configurations:

Directory structure:
```
classes/
  autoload/
composer.json
phpspec.yml
```

composer.json:
```json
{
    "autoload": {
        "psr-4": {
            "Core\\": "classes/autoload/"
        }
    },
    "require-dev": {
        "phpspec/phpspec": "^3.2"
    }
}
```

phpspec.yml
```yml
suites:
  autoload_suite:
    namespace: Core\
    psr4_prefix: Core\
    src_path: classes/autoload/
```

Running `vendor/bin/phpspec desc Core/Thing` will create a `spec` directory,  
and your specification inside:
```
classes/
  autoload/
spec/
  ThingSpec.php
composer.json
phpspec.yml
```

Then running `vendor/bin/phpspec run` will prompt you to create `Core\Thing` if it doesn't already exist in `classes/autoload`. If it already exists, then you should have one passing example.

**Comment by thisleenoble** [comment]
No, that's the part I've established IS possible. My example on the StackOverlow site that I've got working uses a namespace, but I don't want a namespace if I can avoid it at this stage. If I use the global namespace in my composer file and omit the namespace from the yml file I get the error described, but the PHPSpec documentation says that you're allowed to omit the namespace.

**Comment by unfunco** [comment]
Okay, so you don't want a namespace on your source files? If so, you shouldn't be specifying a PSR prefix within your composer.json or your phpspec.yml, try the following configurations:

composer.json
```json
{
    "autoload": {
        "psr-4": {
            "": "classes/autoload/"
        }
    },
    "require-dev": {
        "phpspec/phpspec": "^3.2"
    }
}
```

phpspec.yml
```yml
suites:
  autoload_suite:
    src_path: classes/autoload
```

The above will still put a namespace on your spec files, i.e. `spec`, but no namespace will be added to files within your sources directory unless you specify a directory when using `desc`.

**Comment by thisleenoble** [comment]
That was it! Thank you.
I already had a null string as my composer file's psr-4 key but I didn't think to omit all the other parameters from the yml file entirely. Null strings didn't work.
