### ISSUE TITLE
shouldThrow matcher does not work with Generators

### ISSUE THREAD

**Issue by carlosV2** [phpspec/phpspec#1057]
Today I came with an interesting problem. It seems like PHP does not execute a Generator code if you don't consume it.

This is not correctly handled in phpSpec. As an example, take a look at this spec:
```
<?php

namespace spec;

use GeneratorTest;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class GeneratorTestSpec extends ObjectBehavior
{
    function it_returns_a_generator()
    {
        $this->getGenerator(false)->shouldIterateAs([1, 2, 3]);
    }

    function it_throws_an_exception()
    {
        $this->shouldThrow()->duringGetGenerator(true);
    }
}
```
And this code:
```
<?php

class GeneratorTest
{
    public function getGenerator($throwException)
    {
        if ($throwException) {
            throw new RuntimeException();
        }

        yield 1;
        yield 2;
        yield 3;
    }
}
```

The expected behaviour would be for both tests to pass. However, because the function is returning a Generator, the code execution is deferred until you start consuming the Generator. As this is not happening in the test, no exception is throw and therefore, phpspec complains about no exception being thrown.

**Comment by carlosV2** [comment]
I've been thinking on potential fixes to this problem but I'm starting to think that not all Generators are not testable.

As an example, take a look at the following code:
```
<?php

class GeneratorTest
{
    public function getGenerator()
    {
        for ($i = 0; $i < 100000000; $i++) {
            yield $i;
        }

        throw new RuntimeException('Reached the end of the generator');
    }
}
```

In order to trigger the exception, phpspec will need to traverse 100.000.000 items which is impracticable in real time.

**Comment by ciaranmcnulty** [comment]
As we discussed offline, something like the following is testable via `$this->shouldThrow()->duringFoo()`:

```
public function foo()
{
    if ($condition) {
        throw new Exception();
    }

    return $this->bar();
}

private function bar() {
    yield 1;
}
```

However exceptions only thrown during the generator itself should correctly _not_ be detected by shouldThrow :-/

Perhaps we need `->shouldThrow()->duringIteration()`?

**Comment by bpolaszek** [comment]
Hello there,

I am completely new to phpspec and in order to contribute to an open-source project already using it, my first spec was to assert that iterating over a generator returned by a method will not throw an exception.

Let's assume the following class (to simplify the example, I directly implement `IteratorAggregate`):

```php
class MyClass implements IteratorAggregate
{
    private $shouldFailWhenIterating;

    public function __construct(bool $shouldFailWhenIterating = false)
    {
        $this->shouldFailWhenIterating = $shouldFailWhenIterating;
    }

    /**
     * @inheritdoc
     */
    public function getIterator()
    {
        yield 1;
        yield 2;
        if (true === $this->shouldFailWhenIterating) {
            throw new \RuntimeException();
        }
        yield 3;
    }
}
```
How do you specify that a `MyClass` object _shouldNotThrow_ an exception when `$shouldFailWhenIterating` is set to ` false`  and that it _shouldThrow_ an exception when `$shouldFailWhenIterating` is set to ` true` ?

I didn't find any way to do this in the documentation, and so i may think it is related to that feature request.

**Comment by ciaranmcnulty** [comment]
I've been doing this (prompted by a conversation with @sroze):

```
$this->getGenerator()->shouldThrow()->duringCurrent();
```

I feel that's verbose enough that we don't need any extra features to support this sort of spec
