### ISSUE TITLE
Unicode chars don't work well in Windows console

### ISSUE THREAD

**Issue by stof** [phpspec/phpspec#106]
Here is a snippet of the phpspec output on Windows. As you can see, it does not look great as the charset of the Windows console is not UTF-8:

![phpspec_charset](https://f.cloud.github.com/assets/439401/441907/2fe38540-b12d-11e2-9aab-53d41293d4fc.png)

**Comment by ciaranmcnulty** [comment]
I'm going to close because I don't know how relevant this is with WSL(2)
