### ISSUE TITLE
Testrunner in PHPStorm throw an error

### ISSUE THREAD

**Issue by pYr0x** [phpspec/phpspec#1062]
i am using PHPStorm 2016.3.1 on windows 10
PHPStorm supports PHPSpec as a testrunner. 
I used composer to install phpspec on my enviroment. i added `phpspec.bat` to the PHPStorm config
![image](https://cloud.githubusercontent.com/assets/1126711/22854540/1927543a-f071-11e6-9b00-54d451f2ad66.png)
i also added a simple `run-configuration`
![image](https://cloud.githubusercontent.com/assets/1126711/22854545/348bbc20-f071-11e6-9957-750ac2f22adb.png)

but i got these error.
![image](https://cloud.githubusercontent.com/assets/1126711/22854552/53802102-f071-11e6-8b06-9b66934038fb.png)

it seems that symfony's event dispachter get a clouse instead of a `EventSubscriberInterace`
i dont know if this bug is caused by phpstorm or phpspec.
used `vendor\bin\phpspec.bat run` on the cmd will throw no error.

i created a simple sample https://github.com/pYr0x/phpspec

**Comment by WillSkates** [comment]
Hi @pYr0x. Looking at the stack trace it seems like the error lies inside of the plugin for your IDE. Are you on the latest version?

**Comment by pYr0x** [comment]
i wrote a issue on the PHPStorm bugtracker.
https://youtrack.jetbrains.com/issue/WI-35034

the issue was that PHPStorm does not handle a `.bat` file (on windows) as the `Path to PHPSpec executable` correct.
