### ISSUE TITLE
willReturn() does not account for nullable types

### ISSUE THREAD

**Issue by fgheorghe** [phpspec/phpspec#1067]
If a function signature has a nullable return type (i.e.: ?int), willReturn will not allow for a null return value.

Not sure why this is the case, but:
        $object->method()->willReturn(null);
Generates:
exception [err:TypeError("Return value of ObjectClass\P14::method() must be of the type integer, null returned")] has been thrown.

This happens against PHP version:
PHP 7.1.1 (cli) (built: Jan 21 2017 13:36:56) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

And PHPSpec version: 3.2.3

**Comment by fgheorghe** [comment]
If it helps, the issue appears to originate in file ClassMirror.php, method reflectMethodToNode,         if (version_compare(PHP_VERSION, '7.0', '>=') && true === $method->hasReturnType()) {
            $returnType = (string) $method->getReturnType();

**Comment by fgheorghe** [comment]
After further digging, it turns out ReflectionMethod -> getReturnType will not account for nullable.

**Comment by avant1** [comment]
There is an existing issue related to that problem in `phophecy` repository: https://github.com/phpspec/prophecy/issues/303
And there is even PR to fix that issue, but it is not merged yet: https://github.com/phpspec/prophecy/pull/311

**Comment by fgheorghe** [comment]
Awesome, thank you - nice fix btw. Had no clue about the allowsNull() method for ReflectionParameter.

**Comment by Sam-Burns** [comment]
@avant1 "And there is even PR to fix that issue, but it is not merged yet" - update: a variant of that PR made it into Prophecy 1.7, released yesterday.
