### ISSUE TITLE
ThrowMatcher using a closure

### ISSUE THREAD

**Issue by wout** [phpspec/phpspec#1069]
To sketch the situation, here is a simplified example of what I'm trying to do. One method on my class returns a closure:

```php
class Adaptor {
  public function ask() {
    return function( $pretty ) {
      if ( $pretty )
        return 'You are pretty in pink';
      else
        throw new Exception( 'You are not pretty at all!' );
    };
  }
}
```

Now, in my spec I want to test both scenarios. The first one is not that hard:

```php
function it_ensures_me_i_am_pretty_in_pink() {
  $am_i = $this->ask();
  $am_i( true )->shouldBe( 'You are pretty in pink' );
}
```

But how can I call the closure using the during method to verify that the exception is thrown?

```php
function it_ensures_me_i_am_not_pretty_at_all() {
  $am_i = $this->ask();
  $am_i->shouldThrow( 'Exception' )->during... /*-> ? <-*/;
}
```

**Comment by avant1** [comment]
Try this:
```php
function it_ensures_me_i_am_not_pretty_at_all()
{
    $am_i = $this->ask();
    $am_i->shouldThrow('Exception')->during__invoke(false);
}
```

You return object of [Closure](http://php.net/manual/en/class.closure.php) class in `ask()` method. And it has `__invoke()` method.
Not very elegant, but should work.

**Comment by wout** [comment]
Not as elegant indeed but works as expected. Thanks!
