### ISSUE TITLE
php7.1 ParseError with private constants

### ISSUE THREAD

**Issue by Gladhon** [phpspec/phpspec#1079]
if I use  `private const BLAH = 'blah';`  in my class, i get an unexpected error when running my specs:
`err:ParseError("syntax error, unexpected 'private' (T_PRIVATE), expecting '='")`

So it seems phpspec ist not php7.1 ready?

**Comment by ciaranmcnulty** [comment]
Hm that's a PHP error.

Are you sure you're running PHP 7.1 when executing PhpSpec?

**Comment by ciaranmcnulty** [comment]
If so can you provide a class/spec that produces this behaviour please?

**Comment by unfunco** [comment]
Private constants work fine with PhpSpec and PHP 7.1:

```json
{
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    },
    "require-dev": {
        "phpspec/phpspec": "^3.2"
    }
}
```

```php
namespace spec;

use PrivateConstant;
use PhpSpec\ObjectBehavior;

final class PrivateConstantSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType(PrivateConstant::class);
    }
}
```

```php
final class PrivateConstant
{
    private const BLAH = '';
}
```

```bash
1 specs
1 example (1 passed)
18ms
```

**Comment by Gladhon** [comment]
seems to be a local docker container problems, thx for answer
