### ISSUE TITLE
Testing function starting with should

### ISSUE THREAD

**Issue by jay-rawal** [phpspec/phpspec#1082]
i'm trying to test function shouldDisplayMap(), but i get the following error. 

`no displayMap([array:0]) matcher found for [obj:AppBundle\Entity\Property].` 

```
function it_should_return_true_when_it_should_display_map()
{
        $this->shouldDisplayMap()
               ->shouldReturn(true);
}
```

```
public function shouldDisplayMap(): bool
{
      return true;
}
```
I have tried this with the lastest stable version (3.2.2) and 3.1.

Can anyone point me in the right direction on how to implement this?

**Comment by ciaranmcnulty** [comment]
You can use `$this->callOnWrappedObject('should', [true])`

**Comment by jay-rawal** [comment]
thanks @ciaranmcnulty that worked.

**Comment by alexlongshaw** [comment]
@ciaranmcnulty I can see this is in the docs here: http://www.phpspec.net/en/2.5.1/cookbook/wrapped-objects.html

Is maybe isn't the clearest place (I didn't think to look there). Would it be beneficial to have a page  for "gotchas", FAQs or maybe something around reserved words/phrases and how to deal with them. I'm happy to write something up if you think it is worthwhile.
