### ISSUE TITLE
[php 7.2] incompatible prototype

### ISSUE THREAD

**Issue by remicollet** [phpspec/phpspec#1094]
Running test suite against 7.2.0-dev which have more strict checking:

`
PHP Fatal error:  Declaration of Double\PhpSpec\Console\ConsoleIO\P83::write($message) must be compatible with PhpSpec\Console\ConsoleIO::write($message, $indent = NULL, $newline = false) in /usr/share/php/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2
`

Yes, quite early report.. ;)

**Comment by ciaranmcnulty** [comment]
At first glance this would appear to be a PHP bug not a PhpSpec bug?

**Comment by ciaranmcnulty** [comment]
(In that PHP isn't supposed to break BC)

**Comment by ciaranmcnulty** [comment]
(will probably still fix it ;-) )

**Comment by remicollet** [comment]
> At first glance this would appear to be a PHP bug not a PhpSpec bug?

Prototype are really different, PHP 7.2 is simply stricter.
(IIRC this have been apply, then reverted in 7.1 to be strictly BC compliant)

**Comment by ciaranmcnulty** [comment]
This also seems to be a Prophecy bug? I'll see if I can reproduce

**Comment by Sam-Burns** [comment]
So is it PhpSpec or Prophecy that this would need to be fixed in?

**Comment by ciaranmcnulty** [comment]
Finally fixed in #1108
