### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by Sam-Burns** [phpspec/phpspec#1101]
Having a build which runs on PHP nightly - and a Composer config which says not to run Composer on PHP7.2 - doesn't seem to be working for us.  What's the best solution?  Add the `--ignore-platform-reqs` to the relevant build?

https://travis-ci.org/phpspec/phpspec/jobs/234507712#L196

**Comment by ciaranmcnulty** [comment]
yep makes sense for the canary build - I guess the nightly flipped to 7.2?

**Comment by stof** [comment]
yep, nightly is 7.2 currently.

I agree about ignoring the platform requirement for nightly (or altering the PHP requirement in the composer.json before running composer)
