### ISSUE TITLE
question about constructors

### ISSUE THREAD

**Issue by SerjoA** [phpspec/phpspec#1112]
hi, iam assigning a new class instance to my private var inside other class
how do i check if a collaborator method of class b was called during class a constructor?

**Comment by Sam-Burns** [comment]
```function it_calls_the_thing(Collaborator $collaborator)
{
    $this->beConstructedWith($collaborator);
    $collaborator->importantMethod()->shouldHaveBeenCalled();
}```

Is this what you are trying to do?

**Comment by MarcelloDuarte** [comment]
I think Serjo is trying to:

```php
class ASpec extends Object Behavior
{
    function it_sets_the_state_of_a_collaborator_at_construction(ClassB $b)
    {
        $this->beConstructedWith($b, 42);
        $b->setSomeState(42)->shouldHaveBeenCalled();
    }
}
```

```php
class A
{
    public function __construct(B $b, $state)
    {
        $b->setSomeState($state);
        $this->b = $b;
    }
}
```

**Comment by SerjoA** [comment]
how come when doing like so: when i set my expectations on the spec class and check if
$ms->getMe has been called during both func's getHim and getHim2
then only the getHim functions passes
getAuthService and authService are the class members that holds MicrosoftAuth instance or var

class:

public function getHim(MicrosoftAuth $ms)
    {
        $ms->getMe("35000451", "sdasd","sdasd","ads");
        $ms->newAdPerformanceReportRequest("35000451", "sdasd","sdasd","ads");
    }

    public function getHim2()
    {
        $this->getAuthService()->getMe("35000451", "sdasd","sdasd","ads");
        $this->authService->getMe("35000451", "sdasd","sdasd","ads");
    }



my spec: 

function it_should_have_type_service(MicrosoftAuth $ms) {
        $this->getHim($ms);
        $ms->getMe("35000451", "sdasd","sdasd","ads")->shouldHaveBeenCalled();
        $ms->newAdPerformanceReportRequest("35000451", "sdasd","sdasd","ads")->shouldHaveBeenCalled();
	    $this->shouldHaveType( MicrosoftService::class );

    }

    function it_should_implement_the_service_interface(MicrosoftAuth $ms) {
//        $ms->newAdPerformanceReportRequest("35000451", "sdasd","sdasd","ads")->shouldBeCalled();

//        $this->getAuthService()->getWrappedObject()->getMe("35000451", "sdasd","sdasd","ads");
//        $this->getHim($ms);
        $this->getHim2();
        $ms->getMe("35000451", "sdasd","sdasd","ads")->shouldHaveBeenCalled();
        $this->shouldImplement(ServiceInterface::class);
    }

**Comment by SerjoA** [comment]
i tried both of the solutions but cant get it to work

**Comment by MarcelloDuarte** [comment]
I fail to see the class construction in the example you gave. Where does the delegation work? At the `getHim` method or at the constructor?

**Comment by SerjoA** [comment]
both at the constructor and in other method.
is there any guide or design principles pdf that php spec enforces on the programmer when starting to build new classes , or about object comminication.
i mean what does phpspec consideres bad practice and good practice?

**Comment by MarcelloDuarte** [comment]
SOLID principles mostly. You can find them elaborated here: https://www.amazon.co.uk/Software-Development-Principles-Patterns-Practices/dp/0135974445. Most of the approach that PhpSpec takes are borrowed from the London school of TDD, also called the Mockist approach. You can find more information here: https://www.amazon.com/Growing-Object-Oriented-Software-Guided-Tests/dp/0321503627. I hope this helps.

**Comment by SerjoA** [comment]
thank you very much for your help
