### ISSUE TITLE
hi a question about design enforcement phpspec enforces 

### ISSUE THREAD

**Issue by SerjoA** [phpspec/phpspec#1114]
question: anyone has a design/architect guides or enforcement rules that phpspec uses/allows when creating new classes and between object communications, for example if a collaborator cant be called in a constructor (because phpspec not allowing to mock it for example) and other stuff that phpspec enforces upon you

**Comment by mlopes** [comment]
phpspec allows you to mock and inject mocks into the constructor of the SUT using `letItBeConstructedWith` and `letItBeconstructedThrough`. I'm possibly not the best person to answer this, but I'm under the impression it makes certain practices easier than others, but I don't think there's a lot that you really can't do if you really really want to. It encourages you to inject dependencies by making it hard to test and mock non-injected dependencies, it encourages the use of interfaces by creating them for you (unfortunately depending on you adding the use statement manually), it encourages expressiveness by providing expressive methods itself, both for the SUT and for the collaborators (Ex: shouldBe, willReturn), and by creating methods with names that emerge naturally from the English language (Ex: a call to a shouldBeArchived matcher  in the spec will cause phpspec to generate a isArchived method in the class).

**Comment by SerjoA** [comment]
thank you very much
