### ISSUE TITLE
All specs taking nearly 3x longer to run since Symfony/Prophecy/phpdocumentor upgrade.

### ISSUE THREAD

**Issue by adamelso** [phpspec/phpspec#1119]
```
$ php --version
PHP 7.1.3 (cli) (built: Mar 19 2017 15:31:52) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.3, Copyright (c) 1999-2017, by Zend Technologies
    with blackfire v1.16.1~linux-x64-non_zts71, https://blackfire.io, by Blackfireio Inc.

$ bin/phpspec --version
phpspec 3.3.0
```

Prior to an upgrade, our entire suite would take around 20 seconds to run:

```
$ bin/phpspec r 

1138 specs
7562 examples (7562 passed)
22322ms
```

Since the upgrade, this has now almost tripled.

```
$ bin/phpspec r 

1138 specs
7562 examples (7562 passed)
56178ms
```

This is what was upgraded:

```
$ composer install --optimize-autoloader
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 2 installs, 9 updates, 1 removal
  - Removing symfony/assetic-bundle (v2.8.0)
  - Updating twig/twig (v1.28.2 => v2.4.3): Loading from cache
  - Updating symfony/symfony (v3.0.9 => v3.2.4): Downloading (100%)         
  - Updating jms/translation-bundle (1.2.3 => 1.3.2): Downloading (100%)         
  - Removing suncat/mobile-detect-bundle (0.10.5)
  - Installing suncat/mobile-detect-bundle (dev-gv-remove-typehint cd7f485): Cloning cd7f4858a2 from cache
  - Updating monolog/monolog (1.19.0 => 1.22.1): Loading from cache
  - Updating symfony/monolog-bundle (2.11.1 => v3.1.0): Loading from cache
  - Updating kriswallsmith/assetic (v1.3.2 => v1.4.0): Downloading (100%)         
  - Installing phpdocumentor/reflection-common (1.0): Loading from cache
  - Installing phpdocumentor/type-resolver (0.2.1): Loading from cache
  - Updating phpdocumentor/reflection-docblock (2.0.4 => 3.1.1): Loading from cache
  - Updating phpspec/prophecy (v1.6.0 => v1.7.0): Loading from cache
```

I attempt to downgrade Prophecy first to try and determine which package is the cause, but it seems to be locked to specific versions of both Symfony and Reflection Docblock.

```
    - phpspec/prophecy v1.6.0 requires phpdocumentor/reflection-docblock ~2.0 -> satisfiable by phpdocumentor/reflection-docblock[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - phpdocumentor/reflection-docblock 2.0.5 conflicts with symfony/symfony[v3.2.4].
```

**Comment by ciaranmcnulty** [comment]
It doesn't look like `phpspec/phpspec` was updated.

Are your specs exercising pure domain objects, or are there infrastructure dependencies?

It might be a good idea to try with blackfire.io or a similar profiling tool that can show a diff between executions

**Comment by adamelso** [comment]
Updated PhpSpec to 3.4.0 but only slight change in execution time.
Nearly all of our classes that are covered by specs are domain objects. It's possible there may have been some infrastructure ones that crept in, I'll have to check.

I attempted to profile with Blackfire but it chokes after running 340 specs, I'll try again with a limited suite to see if can get at least one profile to work with.

**Comment by adamelso** [comment]
`ReflectionMethod::invokeArgs()` and `SebastianBergmann\Exporter\Exporter::recursiveExport()` where highlighted by Blackfire.

![screen shot 2017-07-04 at 11 29 37](https://user-images.githubusercontent.com/5972864/27826752-2a07ffb0-60ac-11e7-86a6-7dc6ef7edf98.png)
![screen shot 2017-07-04 at 11 34 32](https://user-images.githubusercontent.com/5972864/27826957-fe224b8e-60ac-11e7-95e1-256356885228.png)
![screen shot 2017-07-04 at 11 35 01](https://user-images.githubusercontent.com/5972864/27826956-fe21bc64-60ac-11e7-9b2a-b321c664d731.png)

**Comment by adamelso** [comment]
I'll no longer be working on this project that is affected, so I won't be able to assist as much going forward. If no-one else reports the same slowdown in performance, you can close the issue.

**Comment by ciaranmcnulty** [comment]
invokeArgs is basically 'running the spec' so I'd suspect it's something in one of your dependencies
