### ISSUE TITLE
Cannot mock interface that has function named "list"

### ISSUE THREAD

**Issue by tinnt701** [phpspec/phpspec#1128]
I have an interface 
```
interface MyInterface
{
    public function list(string $dir): array;
}
```

And I try to mock it
```
function let(MyInterface $myClass) 
{
        $this->beConstructedWith(
            $myClass
        );
}
```

And I got an error 

> Class Double\MyInterface\P1 contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (MyInterface::list) in /zen/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 2

I change function `list` to `listFiles` and it works.

Btw, I'm using PHP 7.1

Any help or explaination?
Thanks

**Comment by ciaranmcnulty** [comment]
This has been fixed in Prophecy: https://github.com/phpspec/prophecy/pull/337 so should appear in the next prophecy release
