### ISSUE TITLE
TypeError thrown when calling `ExampleEvent::getTime()` on event constructed w/ nullable `$time`

### ISSUE THREAD

**Issue by UrGuardian4ngel** [phpspec/phpspec#1137]
Getting into the world of test-driven development, and this tool makes it _really_ awesome!
So thanks for that.

However, I am getting an exception when running phpspecs via PHPStorm's built-in phpSpec runner (PHP 7.1).

Not sure if this is actually an issue with the PHPStorm wrapper, or an incorrect return type in the library. I'm expecting the latter, so that's why I'm reporting an issue over here, first.

```
# This is the command that was executed when I ran my phpspecs from PHPStorm:
$ IDE_PHPSPEC_EXE=/path/to/project/bin/phpspec /usr/local/opt/php71/bin/php /private/var/folders/zl/rlgvjmrj0g75ndwmc2dcv6dc0000gn/T/ide-phpspec.php run --format=phpstorm --no-ansi --no-interaction -c /path/to/project/phpspec.yml.dist spec/AppBundle/FooSpec.php

##teamcity[enteredTheMatrix]

##teamcity[testSuiteStarted name='AppBundle\Foo' locationHint='phpspec://\spec\AppBundle\FooSpec']
 Fatal error happened while executing the following

    Uncaught TypeError: Return value of PhpSpec\Event\ExampleEvent::getTime() must be of the type float, null returned in /path/to/project/vendor/phpspec/phpspec/src/PhpSpec/Event/ExampleEvent.php:142
Stack trace:
#0 /private/var/folders/zl/rlgvjmrj0g75ndwmc2dcv6dc0000gn/T/ide-phpspec.php(65): PhpSpec\Event\ExampleEvent->getTime()
#1 [internal function]: PhpStormFormatter->beforeExample(Object(PhpSpec\Event\ExampleEvent), 'beforeExample', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 /path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php(212): call_user_func(Array, Object(PhpSpec\Event\ExampleEvent), 'beforeExample', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 /path/to/project/vendor/symfony/event-dispatcher/EventDispatcher.php(44): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'beforeExample', Object(PhpSpec\Event\E in /path/to/project/vendor/phpspec/phpspec/src/PhpSpec/Event/ExampleEvent.php on line 142
```

## Root cause

I looked into the code of both parties (phpspec + PHPStorm's wrapper).

The problem seems to be originating from this code snippet:

```php
<?php // /vendor/phpspec/phpspec/src/PhpSpec/Event/ExampleEvent.php

class ExampleEvent extends Event implements PhpSpecEvent
{
    /**
     * @var float
     */
    private $time;                     // $time can NOT be null

    public function __construct(
        ExampleNode $example,
        float $time = null,            // $time CAN be null
        int $result = null,
        \Exception $exception = null
    ) {
        // ...
        $this->time = $time;
    }

    // ...

    public function getTime(): float  // $time can NOT be null
    {
        return $this->time;
    }
}
```

Also see the usage example (PHPStorm wrapper script), as mentioned below.

It is currently _always_ possible to call `anExampleEvent->getTime()`. So this also covers the case where you used `null` as value for `$time` in the constructor. This will result in the exception I mentioned above.
In my understanding, there should never be a type exception in the getter, when `null` is actually valid as value for the `$time` argument (either as default value, or manually specified) during construction.

Is calling this method in this case, seen as "unexpected behavior"? E.g., is it "user error", the event being used in the wrong way / context, and should it be fixed in the wrapper script instead? Or would this actually classify as a bug within this framework (what would be my understanding).

### Possible fixes

If this is indeed a 'bug' of some kind, I would expect that either:

  - (1) `ExampleEvent::getTime()` gets a `?float` return type; still float, but nullable

  - (2) `ExampleEvent::$time` defaults to '0.0' in the constructor arguments (or during assignment)
    ```
      __constructor(
    -     float $time = null,
    +     float $time = 0.0,
    ```

    or:

    ```
    - $this->time = $time;
    + $this->time = $time ?? 0.0;
    ```

  - (3) `ExampleEvent::getTime()` forces its return value to be a float:
    ```
    - return $this->time;
    + return $this->time ?? 0.0;
    ```

  - ...

## Varia

> It might be worth noting that this exception is _only_ happening while running specs with the `--format=phpstorm` flag.
> Obviously due the snippet pasted below, which is doing the `$event->getTime()` call during `beforeExample`.

### PHPStorm wrapper script for phpspec

A sample from the cause in the (generated ???) PHPStorm wrapper script (for reference purposes):

```php
<?php /private/var/folders/zl/rlgvjmrj0g75ndwmc2dcv6dc0000gn/T/ide-phpspec.php

class PhpStormFormatter extends \PhpSpec\Formatter\ConsoleFormatter
{
    // ...

    public function beforeExample(\PhpSpec\Event\ExampleEvent $event)
    {
        $testName = $event->getTitle();
        $duration = (int)(round($event->getTime(), 2) * 1000);  // < the culprit of this issue >:)
        $duration = 0;
        $params = array(
            'name' => $testName,
            "duration" => $duration
        );

        $className = $event->getSpecification()->getClassReflection()->getName();
        $methodName = $event->getExample()->getFunctionReflection()->getName();
        $params['locationHint'] = "phpspec://\\$className::$methodName";
        $this->printEvent('testStarted', $params);
    }

    // ...
}
```

### Environment configuration

Some additional information about my local setup:

```
$ php71 -v
PHP 7.1.7 (cli) (built: Jul 19 2017 15:58:29) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

$ composer show phpspec/*
phpspec/php-diff v1.1.0 A comprehensive library for generating differences between two hashable objects (strings or arrays).
phpspec/phpspec  4.0.2  Specification-oriented BDD framework for PHP 5.6+
phpspec/prophecy v1.7.0 Highly opinionated mocking framework for PHP 5.3+

# PHPStorm
PHPStorm 2017.2.1
Build #PS-172.3544.41, built on August 2, 2017

Plugins:
  PHPSpec BDD Framework: 172.3544.41
```

### Similar issues

Probably the same kinds of issues would apply in case where `$result = null`, and you're calling `ExampleEvent::getResult()`.

So e.g. a default value or nullable return type could fix these cases as well.

## Next steps

If this issue does not belong in this repo, it can be closed.

Otherwise, I'd be glad to help out on this issue (e.g. PRs, support, ...).
I already made some of the above modifications in my local phpspec vendor files, which seem to fix the my issue.

**Comment by ciaranmcnulty** [comment]
Thanks for reporting, this looks like an issue with the new typehints in PhpSpec 4 - it's possible the underlying problem is happening in other formatters as well

**Comment by bluebaroncanada** [comment]
Is there a way to just disable these example code snippets?

**Comment by stof** [comment]
However, the PhpStorm wrapper is still messy. Getting the time in the before event does not make any sense. We cannot know the execution time of the example before executing it. they should display the duration using the after event instead.

**Comment by stof** [comment]
@ciaranmcnulty AFAIK, we only instantiate with `null` for the `before` event, and getting the time here does not make sense (a formatter doing this is broken itself, as it would always report `0` as duration if we fix the TypeError`).
So my suggestion for the fix is to actually throw a `BadMethodCallException` in the getter explaining that getting the duration in the `before` event does not make any sense.

**Comment by stof** [comment]
@bluebaroncanada the example being run is in `spec/AppBundle/FooSpec.php`. this is not in the vendor directory

**Comment by bluebaroncanada** [comment]
Uncaught TypeError: Return value of PhpSpec\Event\ExampleEvent::getTime() must be of the type float, null returned in C:\Users\james\projects\AuthServer\vendor\phpspec\phpspec\src\PhpSpec\Event\ExampleEvent.php:142
for me

**Comment by stof** [comment]
@bluebaroncanada the code were the error is triggered is part of PhpSpec itself. This does not mean that the spec being run is from the vendor folder. It is just that the code of PhpSpec is there.

**Comment by bluebaroncanada** [comment]
Right.  Now why is it running an example within the directory of the code for PhpSpec?

**Comment by bluebaroncanada** [comment]
Oh.  I getcha.  This is code that runs examples.  Sorry.  For some reason I got it in my head that this was a sample.

**Comment by stof** [comment]
It is **NOT** doing that. It is using PhpSpec code to run the example. This is different. Using Phpspec code while running PhpSpec is totally expected.

The error message you gave does not contain the CLI command being run.

**Comment by UrGuardian4ngel** [comment]
@stof Throwing a `BadMethodCallException` is yet another way of fixing the issue... :)

The comments are a bit confusing, as it looks like half of the conversation is missing? :-/
But just to clarify:
- The problem is coming from PHPStorm wrapper calling the `ExampleEvent::getTime()` without the example being ran
- It would return null (but that's failing, because PHP is expecting a float)

I interpreted getTime as "time elapsed". And like a stopwatch, if you don't start it, it would stay at zero.

But, the other alternative you mentioned with the `BadMethodCallException`, would also make sense in this case (instead of `0.0`). However, that would mean the 'problem' just gets shifted, and that the PHPStorm wrapper (and potentially others) would need to be patched as well. :)

**Comment by bluebaroncanada** [comment]
I deleted my comments which contributed nothing.
