### ISSUE TITLE
Return type hints in specs

### ISSUE THREAD

**Issue by mheki** [phpspec/phpspec#1146]
PhpSpec started its live some time ago but we can still remember some initial questions
- why not camel case?
- why not `public function` 
etc.

That increased readability of specs files and was adopted widely by the community. 
What I've seen recently, though, in some projects, people tend to add return type hints to their spec methods. Resulting with:
```
    function it_does_something_extremely_useful(): void
```
which in my opinion decreases readability and should not happen. Especially in bulk PRs saying "add return type hints accross the system".

Maybe we should give some official recommendation about that? What do you think?

**Comment by stof** [comment]
I agree that the void typehint in spec files does not make sense for readability.

btw, PhpSpec does not recommend camel case. It recommends snake case.

**Comment by mheki** [comment]
whoops I missed `not...` 😶 😉 😛 (updated)

**Comment by ciaranmcnulty** [comment]
How would we recommend it? Is the fact there's no return type on our generated specs enough?

**Comment by stof** [comment]
AFAICT, the "official recommendation" about coding standards is not part of the doc currently. I think it comes from slides from @everzet or @MarcelloDuarte when presenting PhpSpec.

**Comment by ciaranmcnulty** [comment]
Yeah the in the repo it's:

* we drop visibility in documentation + generated specs
* we require `it_` and assume the rest will be snake case in specs

**Comment by ciaranmcnulty** [comment]
I don't think there's any action needed here
