### ISSUE TITLE
Feedback: allow check on properties

### ISSUE THREAD

**Issue by drupol** [phpspec/phpspec#1153]
Hi,

I'm pretty new with PHPSpec and I really like it a lot.

However, I'm missing a feature and I'd like to implement it, here it is:

```php
public function it_can_check_if_a_property_exists() {
      $class = $this->getClassWithNoMethods();
      $this->shouldThrow([Exception])->getting('undefinedProperty', array($class));
}
```

Let me know what you think, if I have good feedback I might work on it very soon.

Thanks!

**Comment by MarcelloDuarte** [comment]
Hi @drupol 

Thanks for your contribution!

To clarify, are you trying to describe that calling `getUnderfinedProperty` would throw, or is it the attempt to access the public property `undefinedProperty` that would throw the exception?

Also what is `getClassWithNoMethods ` doing here?

**Comment by drupol** [comment]
Hi @MarcelloDuarte !

Actually, nj on irc just gave me the solution:

`$this->shouldThrow(...)->during('__get', ['undefinedProperty'])`

I guess we can close the issue :-)
