### ISSUE TITLE
Support for nullable return types in prophesized objects (bump Prophecy to 1.7)

### ISSUE THREAD

**Issue by xFlatlinex** [phpspec/phpspec#1156]
Trying to make a method from a test double (prophesized class) to return null fails with a TypeError.
It seems that Prophecy 1.7 has fixed this small issue [here](https://github.com/phpspec/prophecy/pull/322), so I think bumping the prophecy version to that one should solve this.

**Comment by ciaranmcnulty** [comment]
I don't think our current tagging excludes the latest Prophecy, so anyone doing an update will get 1.7

**Comment by xFlatlinex** [comment]
You're right, thanks! I updated prophecy on it's own and now I got the latest version.
