### ISSUE TITLE
Prophet object case sensitivity bug

### ISSUE THREAD

**Issue by blacksaildivision** [phpspec/phpspec#1157]
Hi there,
I found weird behavior when using Prophet object with `\Redis` class.

Consider following class:
```php
class A
{

    protected $redis;

    public function __construct(\Redis $redis)
    {
        $this->redis = $redis;
    }

    public function getItems()
    {
        return $this->redis->lRange('dummykey', 0, -1);
    }
}

```

Here is the spec:
```php
namespace spec;

use PhpSpec\ObjectBehavior;
use A;

class ASpec extends ObjectBehavior
{
    function let(\Redis $redis)
    {
        $this->beConstructedWith($redis);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(A::class);
    }

    function it_should_return_all_items(\Redis $redis)
    {
        $redis->lRange('dummykey', 0, -1)->willReturn(['item1'])->shouldBeCalled();
        $this->getItems()->shouldReturn(['item1']);
    }
}
```

When running this spec I get following error:
```
  20  - it should return all items
      method call:
        - lrange("dummykey", 0, -1)
      on Double\Redis\P2 was not expected, expected calls were:
        - lRange(exact("dummykey"), exact(0), exact(-1))
```

However if I'll change spec to: ` $redis->lrange('dummykey', 0, -1)->...` it works just fine. Is that behavior normal? 

PHP version: `7.1.8`
PHPSpec version: `4.0.3`

**Comment by avant1** [comment]
Hello.
Are you using [phpredis/phpredis](https://github.com/phpredis/phpredis) extension for Redis? I assume you are.

A quick search over its source code shows that `lRange` method is defined in a [lower case](https://github.com/phpredis/phpredis/blob/a57711caa0838cb5b6dc6a548cfbc2b40dac53e7/redis.c#L392) as `lrange`. I'm not strong in reading PHP extensions code, but seems like `PHP_MALIAS` means "method alias". Correct me if I am wrong.

There are also lower case `lrange` calls in extension tests.

PHP itself allows you to call methods with case that is not equal to case used during method definition: https://3v4l.org/j6vtR

But PHPSpec will not register a call in that case.

**Comment by blacksaildivision** [comment]
Thank you for fast reply! Yes, I'm using https://github.com/phpredis/phpredis extension. I actually did not check source code for that, I was misled by PHPStorm autocomplete which has `lRange` instead of `lrange`!

**Comment by avant1** [comment]
You can try to open a PR against https://github.com/JetBrains/phpstorm-stubs/ repository (where stubs for such built-in classes are stored) to fix this problem.

However extension README uses `lRange` name, so I'm not sure what should be fixed here:
1. PHPStorm stubs
2. Extension README
3. Extension source code
