### ISSUE TITLE
Generation of src files fails with composer_namespace_provider

### ISSUE THREAD

**Issue by unfunco** [phpspec/phpspec#1165]
With the following `composer.json` and `phpspec.yml`:
```javascript
{
  "autoload": {
    "psr-4": {
      "Example\\": "src/"
    }
  },
  "require-dev": {
    "phpspec/phpspec": "dev-master"
  }
}
```
```yml
composer_namespace_provider: true
```

When describing a class for the first time and subsequently generating it, it ends up in an incorrect location if the directory in which it is expected is not already created.

https://github.com/phpspec/phpspec/blob/0489b9eabe9389a530eb5e8b43d343dd62c6367d/src/PhpSpec/NamespaceProvider/ComposerPsrNamespaceProvider.php#L64

Since `realpath` returns false because the directory doesn't exist at this point in time, the default src directory is resolved to `.`, causing the generated spec to fail.

I've opened an issue rather than a PR, since I'm not sure whether it's more advisable to create the directory when creating the file for the first time, or whether it should require that directories specified within the autoloader should exist, and instead throw an exception.

**Comment by ciaranmcnulty** [comment]
The old behaviour was to create the folder, so I don’t have any problems doing that

**Comment by unfunco** [comment]
🔉  I'm happy to take a look at this.

**Comment by greg0ire** [comment]
@unfunco can you please test #1174? I'm not sure if it will fix your issue or not.

**Comment by unfunco** [comment]
The changes in #1175 do not fix my issue unfortunately, I can take a look at what's going on later in the week (I have been moving house the past couple of weeks)
