### ISSUE TITLE
Method mocking doesn't work as expected

### ISSUE THREAD

**Issue by tomhaj** [phpspec/phpspec#1170]
Let start with some code:
```php
$firstOwner = new Owner(); // Owner is currently empty class without fields and methods
$secondOwner = new Owner();

$ownerIdentityPolicy->identifyOwner($firstOwner)->willReturn('abc');
$ownerIdentityPolicy->identifyOwner($secondOwner)->willReturn('xyz');

$this->withOwner($firstOwner);
$this->withOwner($secondOwner);
```

Inside method `withOwner` I call `identifyOwner` and it always return `xyz`. I was expected that for `$firstOwner` it should return `abc` as mocked above.

Now, lets introduce some changes:
```php
$firstOwner = new Owner();
$firstOwner->a = 1; // added
$secondOwner = new Owner();
$secondOwner->a = 2; // added

$ownerIdentityPolicy->identifyOwner($firstOwner)->willReturn('abc');
$ownerIdentityPolicy->identifyOwner($secondOwner)->willReturn('xyz');

$this->withOwner($firstOwner);
$this->withOwner($secondOwner);
```

Now it's works as expected. For `$firstOwner` it returns `abc` and for second one `xyz`. It seems like mocking treat two instance as one.

**Comment by avant1** [comment]
What if you do not create owners by hand but require them as argument to example method? Something like this:
```php
function it_is_awesome(Policy $ownerIdentityPolicy, Owner $firstOwner, Owner $secondOwner)
{

}
```

It should work fine in that case.

However your case seems valid too for me. So probably this should be fixed.

**Comment by ciaranmcnulty** [comment]
This is a prophecy issue so should be raised on phpspec/prophecy
