### ISSUE TITLE
PHPSpec to Assert that a method is declared static

### ISSUE THREAD

**Issue by luyandasiko** [phpspec/phpspec#1179]
I have a presentation this coming friday to demonstrate the power of Object Behaviour testing. However, I have run into an issue as I am a new user myself. Let us consider this scenario:

I have a very basic factory that returns to me an instance of Doctrine's Configuration object.

```php
namespace DoctrineBridge\Factory;

use Doctrine\ORM\Configuration;

class ConfigurationFactory
{
    public static function create()
    {
        return new Configuration();
    }
}
```

Now in my code I have refenced this factory to pull out the object like so, `ConfigurationFactory::create()` which with an assignment to a variable makes the returned object available to me.

Let us say Programmer B needed the same Configuration object and knows about the factory but does not know about the effect of the static` menthod.

Moving right along, let us say this guy decides to remove the static method and our factory class now looks as shown below:

```php
namespace DoctrineBridge\Factory;

use Doctrine\ORM\Configuration;

class ConfigurationFactory
{
    public  function create()
    {
        return new Configuration();
    }
}
```

Obviously this now supposedly changes behaviour unless I do not understand PHP. In all the places where we have used the facty statistically supposedly PHP complains that we are calling a non static method statistically. behaviour has now been changed and I view this as important. Imagine you have `ConfigurationFactory::create` in 1000 places in your code put IoC aside and the application crashed.

I was trying to create a custom matcher though to make sure that my method reports a faulire when running my specification but I do not seem to come right. Below is the funtion I implemented:

```php
public function getMatchers(): array
    {
        return array(
            'shouldBeAStaticMethod' => function($subject){
                $reflect = new \ReflectionClass(get_class($subject));

                $isStatic = false;
                foreach($reflect->getMethods() as $method){
                    if($method->getName() == 'create'){
                        $isStatic = $method->isStatic();
                    }
                }

                return $isStatic;
            }
        );
```

Either I am not suppose to be thinking about this scenario all together or it is that you cannot easily spec this behavior anyhow with PHPSpec something I thing can be done with PHPUnit courtesy of the same implementation as shown above. Can somebody help me with context in here?

To add flavor into this dilemma even when I was done with my `getMatchers` method I still couldn't use it because as you can see I only pass the subject within the closure which is the wrapped object. I am doing something wrong I just do not know what it is.

**Comment by MarcelloDuarte** [comment]
What you want to describe is, technically, not object behaviour. Class (static) methods are not messages sent to objects, they are more like namespaced, globally available, functions.

You could achieve what you want — making sure devs won't redeclare the factory method non-static — by writing the following example:

```php
class ConfigurationFactorySpec extends ObjectBehavior
{
    function it_creates_configuration_objects()
    {
        $this->beConstructedThroughCreate();
        $this->shouldHaveType(Configuration::class);
    }
}
```

Does this look like an acceptable solution to you?

**Comment by luyandasiko** [comment]
Having followed your advice I could be able to get the behaviour out of my test I expected. I am starting to fall inlove with PHPSpec multiple million times than before. I will definitely blog about this one as I think it is a very important aspect of code writing when more people when on the code.

Also the context you've provided was of value to me to understand and correlate the intention of the library versus that which I am trying drive myself towards. Big thanks to you.
