### ISSUE TITLE
Potentially undefined variable

### ISSUE THREAD

**Issue by greg0ire** [phpspec/phpspec#1183]
https://github.com/phpspec/phpspec/blob/7e820c663647f113bd58fa97dfa3bcc366e5362e/src/PhpSpec/Wrapper/Subject/Expectation/ConstructorDecorator.php#L45-L60

`$wrapped` could be undefined on line 60. Not sure what do to about it though.

**Comment by ciaranmcnulty** [comment]
That's in the case an `Exception` is thrown but it doesn't have a className?

I'm not sure how that could occur - maybe the correct strategy would be to `throw $e`?

**Comment by greg0ire** [comment]
Failing as early and noisily as possible sounds good. You could also do this:

```php
<?php
throw new \Exception('wrapped object is null or does not have a classname', 0, $e);
```

**Comment by ddziaduch** [comment]
I am investigating this 🙂

**Comment by ciaranmcnulty** [comment]
Is it that it could be `null`, or that it could be undefined?

As it's defined inside the `try` it may just be that we need to catch `Throwable`? Then it can be defined but `null`?

Not clear what real-world bug this is manifesting

**Comment by ddziaduch** [comment]
From this class perspective:
- `$wrappedObject` can be null,
- `$wrappedObject->getClassName()` can return null.
Both will cause Exceptions

**Comment by ciaranmcnulty** [comment]
oh of course, the `==null` check is in the `catch`

**Comment by ddziaduch** [comment]
Hi guys!

I did some investigation and things are not obvious. Please check the test case:
https://github.com/phpspec/phpspec/blob/master/spec/PhpSpec/Wrapper/Subject/Expectation/ConstructorDecoratorSpec.php#L18
The test specifies that `it_rethrows_php_errors_as_phpspec_error_exceptions` but the code itself does not catch PHP Errors - instances of `\Error` and the test dependencies do not throw it.

So I guess this test should be renamed. The question is, should we handle the `\Error` in this class?

Maybe @MarcelloDuarte has idea, `git blame` shows him as last author, but the commits are from 2013 🙃
