### ISSUE TITLE
Tell what method is not found in ExceptionFactory::methodNotFound()

### ISSUE THREAD

**Issue by umpirsky** [phpspec/phpspec#1194]
In spec I had a typo:

```
$this->foo('bar')->shoulReturn('baz');
```

Typo is:

```diff
- shoulReturn
+ shouldReturn
```

And got error:

```
exception [err:TypeError("Argument 1 passed to PhpSpec\Exception\ExceptionFactory::methodNotFound() must be of the type string, null given, called in phpspec/phpspec/src/PhpSpec/Wrapper/Subject/Caller.php on line 363")] has been thrown.
```

It would be cool if some friendlier error message is thrown, at least to tell what method is not found.

**Comment by stof** [comment]
this TypeError is actually a bug in Phpspec here (when trying to tell you the expected error message)

**Comment by ciaranmcnulty** [comment]
I can't reproduce this, has it been fixed?

**Comment by umpirsky** [comment]
I just gor:

```
exception [err:TypeError("Argument 1 passed to PhpSpec\Exception\ExceptionFactory::methodNotFound() must be of the type string, null given, called in /www/sites/chess.com/current/vendor/phpspec/phpspec/src/PhpSpec/Wrapper/Subject/Caller.php on line 360")] has been thrown.
```

With PHPSpec `5.0.1`.

**Comment by ciaranmcnulty** [comment]
It looks like it's dependent on the class name/namespace - is it possible to share that?

(BTW does chess.com use phpspec? I love that site!)

**Comment by ciaranmcnulty** [comment]
That project uses phpspec 2.0 - are you in the process of upgrading?

**Comment by ciaranmcnulty** [comment]
Your report steps are missing a `git checkout phpspec-1194` :)

**Comment by ciaranmcnulty** [comment]
OK this happens when the method under spec returns a scalar value (null will produce a 'calling method on non-object' message, an object will be checked to see if the method exists).

**Comment by DonCallisto** [comment]
I suppose this can be closed.
