### ISSUE TITLE
Custom matcher for thrown exceptions

### ISSUE THREAD

**Issue by sp-daniel-pinyol** [phpspec/phpspec#1203]
How can I write a matcher so that I can check whether an exception matches my custom requirements?
Something like https://stackoverflow.com/a/11736204/145289 ."spec" is deprecated in phpspec 4.3, right?

thanks

**Comment by jakzal** [comment]
You can write inline matchers: http://www.phpspec.net/en/stable/cookbook/matchers.html#inline-matcher

**Comment by ciaranmcnulty** [comment]
You can also write matcher objects and point to them in the config file
