### ISSUE TITLE
Use statements are not sorted alphabetically

### ISSUE THREAD

**Issue by unfunco** [phpspec/phpspec#1210]
Having been working on a project beginning with the letter T for a year now, and manually editing `use` statements to be alphabetically ordered each time a specification is generated (so that they're consistent with how the IDE inserts them) I wrote [this extension](https://github.com/unfunco/phpspec-sort-use-statements). Would this be a feature suitable for version 5.x if refactored, or is it better off remaining an extension?

**Comment by jdreesen** [comment]
Your link misses an "s" at the end. The correct link is: https://github.com/unfunco/phpspec-sort-use-statements

**Comment by unfunco** [comment]
Whoops! Updated, thanks.

**Comment by ciaranmcnulty** [comment]
This is for whether the subject namespace is before or after the PhpSpec/Prophecy ones?

**Comment by unfunco** [comment]
It is, it could be done with a custom template per project too, but that would assume one root namespace.

**Comment by ciaranmcnulty** [comment]
It makes sense to me in core then - we’d just need to document the existing template somewhere in the docs for people who want more control.

Please feel free to send a PR :-)

**Comment by DonCallisto** [comment]
Can't we simply use [php-cs-fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) and integrate it with CI pipeline?

**Comment by unfunco** [comment]
Closing this issue as it's now merged.
