### ISSUE TITLE
PHP 7.3 new features

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1213]
We've in the past been unstructured in handling new PHP versions. We've got the tests passing, but haven't through about what we'd need to add to PhpSpec.

I've not looked much at the changelog, we should discuss new PHP features in this thread, and what impact they'll have on testability / what new things users will need to test. This will lead to hopefully a load of separate Issues we can work through.

**Comment by ddziaduch** [comment]
v7.3 does not include to much changes https://ayesh.me/Upgrade-PHP-7.3

**Comment by stof** [comment]
Looking at these changes, I don't see anything impacting phpspec

**Comment by ciaranmcnulty** [comment]
I concur - there's some nice little things, but nothing we'd need to add functionality for 👍
