### ISSUE TITLE
No phars being built - should we drop?

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1228]
It looks like the travis phar releasing is failing since 5.0

Should we drop phar releasing, or maybe go further with it using Scoper etc?

**Comment by roukmoute** [comment]
Is there an interest in continuing to create it?
With phpunit this can be understood so that there are no conflicts, but with phpspec, is it the same things?
Personally I don't have this problem.

**Comment by ciaranmcnulty** [comment]
I imagine PHPUnit has very similar trade-offs as we do?  We have a few Symfony dependencies for instance.

Nobody on twitter said they use the phar so I guess we can leave it not being built, for now!

**Comment by stof** [comment]
Well, the phar is not about avoiding conflicts if you don't rename classes in them, but about creating them without any chance to solve them :smile:

**Comment by devsoul** [comment]
@ciaranmcnulty I use .phar on my development machines, and I just noticed that my ansible playbooks are not working because phpspec.phar is missing :)

**Comment by ciaranmcnulty** [comment]
@devsoul ok I guess if 1 person uses it ;-)

**Comment by ciaranmcnulty** [comment]
I turned it back on for the next release
