### ISSUE TITLE
Allow phpSpec to mock methods of the tested class

### ISSUE THREAD

**Issue by VanTanev** [phpspec/phpspec#126]
I came across this today when working on a class that does database manipulations/retrieval through Propel's [Model Criteria](http://propelorm.org/reference/model-criteria.html) classes.
An example use would be:

``` php
class UsesCriteria
{
    public function doSomething()
    {
        $this->getDataFromDb();
    }

    public function getDataFromDb()
    {
        return UserQuery::create()
            ->filterByIsActive(true)
            ->find();
    }
}
```

It makes sense to be able to mock the result of `getDataFromDb()` for the purposes of testing `doSomething()`. 

I implemented an alternative solution [here](https://gist.github.com/CraftyShadow/5622561), and it's what I'll probably end up using for my current project, but I still think this is a feature worth having.

**Comment by stefanotorresi** [comment]
IMHO the response to this feature request is a bit short-sighted.

Not all code we have to deal with is nicely designed, yet we still have to test it.

I'm currently dealing with a scenario where the SUT inherits methods from a parent, which I can't just compose instead of extending because reasons, and I can't mock those incredibly complex parent methods, leaving me with no alternative other than not using PhpSpec to test this specific use case.

**Comment by ciaranmcnulty** [comment]
@stefanotorresi I support your decision to not use PhpSpec for this case

We lean towards supporting 'good' design because we want to encourage new code to be written well. If you're testing old systems you can either change them or indeed use another testing tool

**Comment by stefanotorresi** [comment]
basically you're saying "you can't use phpspec to make your code hugely better, because it assumes it's already good enough to comply to its design constraints".

**Comment by RuslanZavacky** [comment]
I think what I am trying to do a little bit resembles this issue, so though to ask. How are you mocking current date? For example you have a class, which is like:

```php

class TimeManager
{
  ...

  public function getNow()
  {
    return new \DateTime();
  }

  public function getAvailableTimes($dates)
  {
    $now = $this->getNow();

    $availableTimes = [];

    ... some logic here.

    return $availableTimes;
  }

  ...
}
```

Goal is to mock getNow, to return specific date, as some date related calculations are sensitive to the current date.

Thanks!

**Comment by jakzal** [comment]
@RuslanZavacky here's what I do:

```php
interface Clock
{
    public function now(): \DateTimeImmutable;
}
```

Now, make the `Clock` a collaborator of any class that needs access to the current time:

```php
class TimeManager
{
  private $clock;

  public function __construct(Clock $clock)
  {
      $this->clock = $clock;
  }

  public function getAvailableTimes($dates)
  {
    $now = $this->clock->now();

    $availableTimes = [];

    // ... some logic here.

    return $availableTimes;
  }
}
```

In your specs, simply stub the `Clock`:

```php
function it_does_things_with_time(Clock $clock)
{
    $clock->now()->willReturn(new \DateTimeImmutable('2018-08-12 07:00:00'));

    // ...
}
```

As a side effect, you can provide alternative implementations of your clock and do things like faking time in your app.

**Comment by RuslanZavacky** [comment]
Thanks for suggestion @jakzal, will do like that 👍
