### ISSUE TITLE
Case where static constructor returns null not handled

### ISSUE THREAD

**Issue by dantleech** [phpspec/phpspec#1261]
Given the following class:

```php
class Foobar
{
    public static function create(string $bar): ?self
    {
        return null;
    }

    public function bar()
    {
        return 'foo';
    }
}
```

and the spec:

```php
class FoobarSpec extends ObjectBehavior
{
    public function it_should_make_a_foobar()
    {
        $this->beConstructedThrough('create', ['foo']);
        $this->bar()->shouldReturn('foo');
    }
}
```

PHPSpec reports:

```
Foobar                                                                      
   9  - it should make a foobar
      call to a member function bar() on a non-object.
```

Phpspec should probably complain more explicitly `Could not construct test subject` or `Factory method returned `null` instead of `Foobar`.

**Comment by ciaranmcnulty** [comment]
Yep, a simple better message would be an improvement

**Comment by ddziaduch** [comment]
There is already case for that in the code:

1. When you call `beConstructedThrough()` it sets `$factoryMethod` field (https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Wrapper/Subject/WrappedObject.php#L115)
2. You call method expectation which makes new instance via factory method (https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Wrapper/Subject/WrappedObject.php#L200)
3. If the factory method does not return object the exception is thrown (https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Wrapper/Subject/WrappedObject.php#L224)

**Comment by dantleech** [comment]
It seems that code doesn't get called, this is the place that instantiates the object in this case:

https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Wrapper/Subject/Caller.php#L226

**Comment by ddziaduch** [comment]
@dantleech thanks! I am working on the fix

**Comment by ddziaduch** [comment]
Please see #1263
