### ISSUE TITLE
PHP 7.4 support

### ISSUE THREAD

**Issue by maciejmiara** [phpspec/phpspec#1268]
When do you plan to support PHP 7.4?
After GA or earlier?
I'd like to know when to expect it, so I can start using PHP 7.4 as soon as possible.

Thanks for answer

**Comment by ciaranmcnulty** [comment]
The build is currently breaking due to an issue that's either with Prophecy, or how we're using it in the test suite. 

If that starts passing I'll be ok allowing it in composer.json, definitely for version 6 and maybe for version 5 depending what the fix is

**Comment by ciaranmcnulty** [comment]
So the short version is: it depends when someone has time to investigate and fix that issue (https://github.com/phpspec/prophecy/issues/444)

**Comment by ddziaduch** [comment]
@ciaranmcnulty @maciejmiara fixed
