### ISSUE TITLE
phpspec desc failing because of missing Symfony\Component\EventDispatcher\Event

### ISSUE THREAD

**Issue by babarinde** [phpspec/phpspec#1287]
On PHP 7.4 
After installing php spec
and I try doing 
`./vendor/bin/phpspec desc Markdown`
I get the error below
`PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\EventDispatcher\Event' not found in /blah-blah-blah/vendor/symfony/console/Event/ConsoleEvent.php:24`
It looks like It can't find the event class as ConsoleEvent now extends `Symfony\Contracts\EventDispatcher\Event;`
My fix was to bump Symfony console on my composer.json to ^5.0, I don't know if this will break anything

**Comment by ciaranmcnulty** [comment]
Can you give some more detail? how did you install phpspec?

**Comment by babarinde** [comment]
`composer require --dev phpspec/phpspec`

**Comment by ciaranmcnulty** [comment]
This may be fixed by #1307 and phpspec 6.2.0 - can you try?

**Comment by Saeven** [comment]
Can confirm I am seeing the same thing; 6.2.x-dev, 6.2.0 and 6.1.* are all affected from what I can tell.

Fixed by pinning event-dispatcher to 4.4.10.

I can't test pinning to 5.x because of an assetic dependency, ymmv.

**Comment by ciaranmcnulty** [comment]
Ugh this is so annoying; the fact Symfony EventDispatcher changed signature so badly is super annoying

**Comment by ciaranmcnulty** [comment]
@Saeven what specific set of versions *didn't* work?

**Comment by Saeven** [comment]
The 5.x versions are the culprits.  Moving to 4.4.x solves it.  I didn't test lower min versions of 4 (4.3, 4.2, etc).

Hope this helps!

**Comment by ciaranmcnulty** [comment]
Something like your composer.json or a dump of `composer info` would really help if you can...

**Comment by Saeven** [comment]
With pleasure.  Here's a project I'm in right now where I'm fixing this.  ZF3 project.  Configuration shown, works.

In the projects I've repaired just now, it was really simple.  Just needed to make sure this line was in composer.json:

    "symfony/event-dispatcher": "4.4.10",

[composer_info.txt](https://github.com/phpspec/phpspec/files/4800969/composer_info.txt)

**Comment by ciaranmcnulty** [comment]
Thanks 👍

**Comment by ciaranmcnulty** [comment]
@Saeven or @babarinde is there a chance you can share your entire composer.json when it didn't work, please?

**Comment by babarinde** [comment]
Hi @ciaranmcnulty, 
Apologies for the late response on this issue.
I noticed that this issue did not exist on some of my other projects using phpspec, as i did not have to to drop the symfony/console to ^5. and `phpspec desc` works fine
The main difference i see is that then failing composer had php:^7.1 and the other ^7.4

I was trying to recreate the issue before I send in the entire composer.json and it works fine now with phpspec 6.2
recreating with 6.1 also works now
[composer.json](https://gist.github.com/babarinde/47d2e8e34e8a7d41034695268afd1a19)
Thanks

**Comment by Saeven** [comment]
Something must have been fixed along the chain.  

    composer require --dev phpspec/phpspec

Used to yield a broken config, yet now works.

**Comment by babarinde** [comment]
Thanks for chasing this down @ciaranmcnulty , i think it will be safe to close this nwo
