### ISSUE TITLE
Bump prophecy version for next release?

### ISSUE THREAD

**Issue by DonCallisto** [phpspec/phpspec#1289]
Is it worthy to have a bump of Prophecy version (`^1.10`) in order to have performances fixes, in the next release?
If so, let me know and I'll open a PR.

**Comment by ciaranmcnulty** [comment]
Won't anyone installing phpspec get 1.10.0 of Prophecy already?

**Comment by stof** [comment]
The current constraint already allows installing 1.10, and composer installs the highest compatible version by default (`--prefer-lowest` is not something you use when caring about performance of your code). So there is nothing to change to benefit from it.

**Comment by DonCallisto** [comment]
It really depends on the composer.json of the project and composer.json files of all dependencies of the project.
There's good chances that everyone get the new version indeed, but if anyone takes the old one won't probably never notice it.
I'm a little bit doubtful just because the new Prophecy version fix a memory leak.

**Comment by DonCallisto** [comment]
@stof that's true but from my POV as the new version fixes a memory leak, new PHPSpec version should not allow someone to run Prophecy with a well-know issue of this scope.

**Comment by ciaranmcnulty** [comment]
It's a memory leak I've never had an issue with 🤷‍♂

**Comment by DonCallisto** [comment]
@ciaranmcnulty but it is documented (even with Ocramius' memory leak tool) so you can fall on it at anytime when you add a new example or when spec-ing new class.
We didn't had the issue unless, suddenly with just one more example, everything got broken.

**Comment by ciaranmcnulty** [comment]
If someone's using `--prefer-lowest` and getting a memory leak they have a simple resolution...

**Comment by DonCallisto** [comment]
Just for the record, not only `--prefer-lowest`, also other dependency that explicitly demands for `1.9`.
As there's a concrete motivation behind this bump (possible memory leak) with this you can "implicitly notify" others of the change. If someone prefers to stay with potential memory leak *and* previous version of PHPSpec, it's perfectly fine.
BTW ok, I won't debate over, just tryin' to explain my standpoint.

**Comment by stof** [comment]
if another dependency explicitly requires Prophecy 1.9, bumping the requirement in phpspec won't automatically save you. It will more likely force you to stay on an outdated version of phpspec as well.

**Comment by DonCallisto** [comment]
I had the same debate internally with my colleagues and they convinced me those kind of scenarios should be handled.
Now I see "the bigger picture" and you're right.
