### ISSUE TITLE
PHP Spec Home page implies stable version is ^4.0 when Github implies it is 

### ISSUE THREAD

**Issue by john-arcus** [phpspec/phpspec#1293]
## Context

```
$ php --version
PHP 7.3.9 (cli) (built: Sep 10 2019 17:45:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies 
```

I was trying to use `composer update` on a project which currently uses phpsec version 4:
```

"require-dev": {
-        "phpspec/phpspec": "4",
```

## What occurs

I get an error:

```
$ composer install --prefer-source
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for phpspec/phpspec 4.0.0 -> satisfiable by phpspec/phpspec[4.0.0].
    - phpspec/phpspec 4.0.0 requires php ^7.0,<7.2 -> your PHP version (7.3.9) does not satisfy that requirement.
```

I went to the [PHPSpec home page](http://www.phpspec.net/en/stable/):

Where the suggested version of phpspec appears to be "^4.0": 

Create a composer.json file:
```
{
    "require-dev": {
        "phpspec/phpspec": "^4.0"
    },
    "config": {
        "bin-dir": "bin"
    },
    "autoload": {"psr-0": {"": "src"}}
}
```

However, if you look at [the github badges for this project](https://github.com/phpspec/phpspec) it says stable = 6.1

## Expected

I would expect the phpspec Quick start to work without issues for users on the latest stable machines. (Mac OS Catalina bundles PHP 7.3.9 by default now).

The [PHP Spec Quick start guide on the home page](http://www.phpspec.net/en/stable/) could mention that the quick start expects no greater than PHP 7.2 in order to work, or

The [PHP Spec Quick start guide on the home page](http://www.phpspec.net/en/stable/) could suggest a version of PHP Spec that works with the latest version of PHP.

**Comment by ciaranmcnulty** [comment]
Indeed, we should make these changes (docs are in this repo) and add to the check_releases.php script I use when making a release

**Comment by john-arcus** [comment]
Thanks for accepting that this issue. I was not sure if it was an issue of if I was misunderstanding something.

**Comment by ciaranmcnulty** [comment]
Thanks, this is updated now
