### ISSUE TITLE
Argument 2 passed to EventDispatcher::dispatch() must be an instance of Event

### ISSUE THREAD

**Issue by umpirsky** [phpspec/phpspec#1294]
I updated `phpspec/phpspec (5.1.2 => 6.1.1)`. I'm using `symfony/symfony: v4.2.12`.

Started getting:

```
Uncaught TypeError: Argument 2 passed to Symfony\Component\EventDispatcher\EventDispatcher::dispatch() must be an instance of Symfony\Component\EventDispatcher\Event or null, instance of PhpSpec\Event\SuiteEvent given, called in vendor/phpspec/phpspec/src/PhpSpec/Util/DispatchTrait.php on line 25 and defined in vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php:37
    Stack trace:
    #0 vendor/phpspec/phpspec/src/PhpSpec/Util/DispatchTrait.php(25): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('beforeSuite', Object(PhpSpec\Event\SuiteEvent))
    #1 vendor/phpspec/phpspec/src/PhpSpec/Runner/SuiteRunner.php(52): PhpSpec\Runner\SuiteRunner->dispatch(Object(Symfony\Component\EventDispatcher\EventDispatcher), Object(PhpSpec\Event\SuiteEvent), 'beforeSuite')
    #2 vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/EventDispatcher.php on line 37
```

**Comment by dmolineus** [comment]
I also run into this issue. It occurs when symfony contracts is installed using a symfony/event-dispatcher version `< 4.3`. Then the assumption, that the contracts event class should be used is wrong. The fact that symfony contracts is available doesn't mean that the event dispatcher can handle it.

https://github.com/phpspec/phpspec/blob/486aaa736e9e24f3e22a6545f6affb88f98e2602/src/PhpSpec/Event/BaseEvent.php#L8-L15

Maybe the approach of codeception would be better instead:
https://github.com/Codeception/Codeception/commit/15ba342b6511d0557435182d815690aa6b8e6aef

**Comment by dmolineus** [comment]
Is there anything how I could support you providing a fix for it?

**Comment by akuzia** [comment]
May I suggest changes in PR above?

**Comment by john-arcus** [comment]
Does this mean that phpspec does not work with symfony console applications?

**Comment by akuzia** [comment]
No, it does not work with symfony/event-dispatcher < 4.3

**Comment by stof** [comment]
The check might be improved to also check whether the EventDispatcherInterface of the component extends the one from contracts.

**Comment by akuzia** [comment]
@stof pls see #1300
