### ISSUE TITLE
Rename the branches

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1304]
There is some discussion around the branch naming in the community, mostly around what `master` sounds like. This has made me realise that the name doesn't really reflect what we use it for.

I tend to juggle the branches around when there's a new release and this is a good time.

We tend to have 2 active branches: one that's receiving new features and one that's receiving bug fixes (that get rolled forward into the other branch). We then have to document that `5.1` is the bug branch and `master` is the feature branch - it'd be easier if the names reflected that.

What's a good name for this? `bugfix` and `active?`

**Comment by GrahamCampbell** [comment]
I think 5.1 and master are fine branch names, and people are used to that naming scheme, since it is what packagist expects branches to be named (other custom names require branch aliases (including master, but master is the convention among many projects inc phpunit, laravel, symfony)).

**Comment by ciaranmcnulty** [comment]
Feedback I've had is that `master` isn't great. There's not anything particular about the name that makes me want to stick with it because it's neither mastering anything in the sense of controlling, and it's not really a master in the sense of something you take copies of.

If there's a better term I'd switch. Would indeed need to see the impact on packagist but TBH if people are using `dev-master` they can expect breakage

**Comment by drupol** [comment]
I also think that this should not change, even if I understand the reasons. Reasons make senses, but people are used to this naming conventions.

IMHO, the amount of issue this would create doesn't worth the change.

**Comment by GrahamCampbell** [comment]
Maybe if you make 5.1 the default branch, there will be less confusion?

**Comment by drupol** [comment]
> Maybe if you make 5.1 the default branch, there will be less confusion?

That would be a good idea.

**Comment by ciaranmcnulty** [comment]
5.1 is the bugfix branch... should that really be default?

**Comment by drupol** [comment]
I guess he meant `6.0`

**Comment by GrahamCampbell** [comment]
> I guess he meant 6.0

No, there is no 6.0 branch, and nor should there be. I really did mean 5.1. master is 6.1 at the moment (not 6.0).

**Comment by GrahamCampbell** [comment]
Though, tbh, I don't see how there can be much confusion, if it is documented? Maybe add an issue template, like Laravel does.

**Comment by drupol** [comment]
> 
> 
> > I guess he meant 6.0
> 
> No, there is no 6.0 branch, and nor should there be. I really did mean 5.1. master is 6.1 at the moment (not 6.0).

Sorry you're right.

I would vote for keeping `master` and having a `5.0` or `5.1` branch.
