### ISSUE TITLE
Union types support for doubles

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1314]
We will need to consider what to do if an argument is hinted with a union type (see https://github.com/phpspec/phpspec/pull/1313#discussion_r446061984)

**Comment by stof** [comment]
is that for arguments of the spec object ? I would say "fail with an explicit message". If we randomly or arbitrarily choose one part of the union, this will be misleading, as the suite would be testing only a subtype of the collaborator. Such a union type probably need that you actually need separate examples using separate collaborators, to cover the support of a union type in your SUT.

**Comment by ciaranmcnulty** [comment]
Yep I think I agree - would just need a good error message then I suppose?

**Comment by ciaranmcnulty** [comment]
When #1332 is merged it will mean all tests passing on PHP 8

However we will need to remember to do this too!
