### ISSUE TITLE
Appveyor PHP version

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1317]
I've never fully understood how appveyor works... it needs to test using PHP 7.3 on `main` branch now that we have dropped 7.2 support

**Comment by drupol** [comment]
Maybe it would be a good time to think about moving to Github Actions. So we can have Linux, Apple and Microsoft testing in one place.

**Comment by drupol** [comment]
Example of switch to Github actions: https://github.com/friends-of-phpspec/phpspec-code-coverage/pull/25

**Comment by ciaranmcnulty** [comment]
I'm definitely in favour of doing that, if you want to hold my hand through it? :-)

**Comment by ciaranmcnulty** [comment]
It looks like 7.3 is not working on appveyor so I changed it to test against 7.4 - we will have to hope our linux 7.3 tests will catch anything bad
