### ISSUE TITLE
ObjectStateMatcher does not handle null gracefully

### ISSUE THREAD

**Issue by naomigo** [phpspec/phpspec#1321]
I am writing the spec for a function that should return whether a product is in stock.

For ease of example, let's assume the product is in stock:

```php
public function it_should_be_in_stock_if_the_warehouse_has_stock()
{
    $this->shouldBeInStock();
}
```

When I run this test for the first time, the function `isInStock()` does not yet exist. Therefore, after prompting me to create the function, I was expecting PhpSpec to give me an error message along the lines of "expected `true` but got `null`".

However, instead I get:

```cli
[err:TypeError("Argument 3 passed to PhpSpec\Matcher\ObjectStateMatcher::getFailureExceptionFor() must be of the type bool, null given, called in vendor\phpspec\phpspec\src\PhpSpec\Matcher\ObjectStateMatcher.php on line 76")]
```

The reason for this is, as the error suggests, the `bool` type hint on the `$result` parameter of the `getFailureExceptionFor` method. If I remove this type hint then I get something more like what I was expecting to see:

```cli
expected [obj:MyNamespace\Product]::isInStock() to return true, but got null.
```

Would it be possible to amend the code so that it supports `null`?

I reckon if in the `positiveMatch` and `negativeMatch` functions a `null` result defaults to `false` and `true` respectively then this would provide a far better user experience. I guess other considerations might be, what if an array is returned, or an object, etc.

Worth noting also that it would be lovely if the `--fake` command also then worked with this function, which it doesn't at the moment.

Thought I'd raise this as an issue first, before going ahead and looking at creating a PR, in case there were very specific reasons why the code currently acts the way that it does.

**Comment by ciaranmcnulty** [comment]
Yes it looks like the type hint is in error (a lot were added automatically).

We should be able to cope with object state matcher methods returning anything, and show appropriate messages

**Comment by ciaranmcnulty** [comment]
A PR to the 6.2 branch would be very welcome indeed :)

**Comment by naomigo** [comment]
Thanks Ciaran, I've created PR #1323 (scarily close to the issue number - random coincidence?!), so please take a look.

**Comment by ciaranmcnulty** [comment]
Issues and PRs share the same ID sequence so it's no coincidence :-)

**Comment by naomigo** [comment]
Ahhh, oh well!

**Comment by naomigo** [comment]
I have just created a PR to add support for the "fake" option when using the object state matcher, PR #1324
