### ISSUE TITLE
Changes to namespace tokenisation in PHP8

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#1322]
https://wiki.php.net/rfc/namespaced_names_as_token

If this passes the stream wrapper probably needs to change

**Comment by jdreesen** [comment]
> If this passes the stream wrapper probably needs to change

It already passed the vote and is accepted.

**Comment by GrahamCampbell** [comment]
I suppose Ciaran meant, if they actually implement it in time for 8.0. ;)

**Comment by ciaranmcnulty** [comment]
Actually I pasted the wrong link :)

Thanks @jdreesen for pointing out

It's the code in https://github.com/phpspec/phpspec/blob/main/src/PhpSpec/CodeAnalysis/TokenizedTypeHintRewriter.php that will need to be evaluated

**Comment by GrahamCampbell** [comment]
Ah, that makes a lot more sense now! ;)

**Comment by GrahamCampbell** [comment]
I doubt that their RFC will be accepted. Their argument about helping tooling is incorrect. The problem has already been solved (by existing tooling), and the change will only serve to break all existing tooling...

**Comment by ciaranmcnulty** [comment]
This broke spec loading see #1325

**Comment by ciaranmcnulty** [comment]
Need to check if it also breaks the tokenised spec rewriting

**Comment by ciaranmcnulty** [comment]
Yep it's completely broken TokenizedTypeHintRewriterSpec
