### ISSUE TITLE
Cannot specify expected exception on subject constructor

### ISSUE THREAD

**Issue by jmikola** [phpspec/phpspec#134]
_Relocated comment from https://github.com/phpspec/phpspec2/issues/46 (using the same issue title)._

I have a very simple class that throws an exception if its single array argument is too small. The corresponding test method in my spec class is as follows:

```
function its_constructor_should_require_at_least_two_position_elements()
{
    $exception = new \InvalidArgumentException('Position requires at least two elements');

    $this->shouldThrow($exception)->during('__construct', array(array(1)));
}
```

Depending on whether I typehint the constructor argument in my implementation class, I'll see one of the following errors:
- error: Argument 1 passed to GeoJson\Geometry\Point::__construct() must be of the type array, none given in...
- warning: Missing argument 1 for GeoJson\Geometry\Point::__construct() in...

According to `phpspec --version`, I'm using `2.0.1-PREVIEW` (from a fresh Composer installation).

**Comment by seggen-ibuildings** [comment]
For posterity's sake, you can use `duringInstantiation()` in PHPSpec 2.4.1 (and perhaps earlier):

``` php
    function it_should_not_be_empty()
    {
        $this->beConstructedWith([]);
        $this->shouldThrow(InvalidArgumentException::class)->duringInstantiation();
    }
```
