### ISSUE TITLE
Documentation outdated? what about phpspec itself?

### ISSUE THREAD

**Issue by bogdan-dubyk** [phpspec/phpspec#1355]
It's   more a question not an issue report:) It looks like the documentation http://www.phpspec.net is a bit outdated, at leas I can see that on the Extensions page, most of extension are not supported anymore and not working with a new phpspec version. And now I'm confused, is it make sense to use phpspec nowadayes:) 

Don't think that I want to say something bad about it, I really like the idea of specification and I like the phpspec itself. But I did not work with it for a some time, and now I'm starting new project and not sure if I should use it. Can you convince me of that?:)

**Comment by ciaranmcnulty** [comment]
It's hard to track the extensions, maybe we should remove it from the docs?

I can't really comment about usage, we get about 8k installs/day according to packagist
