### ISSUE TITLE
Cannot test on PHP 8.1 (nightly)

### ISSUE THREAD

**Issue by sagikazarmark** [phpspec/phpspec#1356]
The `shivammathur/setup-php` supports PHP 8.1 as a nightly PHP target, but phpspec requires `^7.3 || 8.0.*` so tests cannot be run against that version. I know this is yet another flame topic in the community (`^7.3 || 8.0.*` vs `>=7.3`), but I didn't find anything related on the issue tracker, so I thought I'd bring it up.

I'm a little bit out of practice with PHP and Composer, so apologies for the noise if there is a solution (that doesn't require messing up the entire CI config).

**Comment by ciaranmcnulty** [comment]
I'd advise using composer 2's `--ignore-platform-req=php` flag for this

**Comment by sagikazarmark** [comment]
Hm, I tried --ignore-platform-req known from composer 1. Is it different if I add =php?

**Comment by jdreesen** [comment]
https://php.watch/articles/composer-ignore-platform-req

**Comment by GrahamCampbell** [comment]
In composer 1 you can use `--ignore-platform-reqs`, which also ignores extension requirements. The ability to only ignore the PHP requirement is a composer 2 feature.

**Comment by GrahamCampbell** [comment]
Also, if ignoring the php reqs causes issues, you can also tell composer to pretend the PHP version is something other than the runtime version.

**Comment by sagikazarmark** [comment]
Thanks a lot for the responses!
