### ISSUE TITLE
New failures since upgrade to PHP 8

### ISSUE THREAD

**Issue by drupol** [phpspec/phpspec#1375]
Hi,

I upgraded to PHP8 and I'm having issues with some tests now. Those issue were not existing in PHP 7.4.19.

See more context here: https://github.com/loophp/collection/discussions/103

I think it's definitely an issue with PHPSpec.
Look, I'm currently working for work and I'm having the same kind of issue, see:

![image](https://user-images.githubusercontent.com/252042/120457489-c9052380-c396-11eb-9a88-320c2f6f06c9.png)

The test can be found here: https://github.com/ecphp/cas-bundle/blob/master/spec/EcPhp/CasBundle/Security/Core/User/CasUserProviderSpec.php#L72

**Comment by kelunik** [comment]
The issue is https://github.com/phpspec/phpspec/blob/eb0d939b235f6091a8439a2a2fc144c9e0d5f569/src/PhpSpec/Runner/Maintainer/ErrorMaintainer.php#L95 not checking properly for error suppression. It needs to use a bit mask as documented on PHP.net, as PHP 8 does no longer suppress fatal errors with @.

**Comment by kelunik** [comment]
See https://www.php.net/manual/en/function.set-error-handler

**Comment by drupol** [comment]
I'll submit a PR in 1 or 2 hours. We need this for work.
