### ISSUE TITLE
Deploying a .phar version of PHPSpec

### ISSUE THREAD

**Issue by mirandaguillaume** [phpspec/phpspec#1410]
Hi ! I was wondering if a .phar package of PHPSpec could be made ? 
I'm trying to reduce my dependencies on the Symfony and PHP version of my tools and it would actually help in not having every dependencies of PHPSpec up to date with my project dependencies.

Thx in advance.

**Comment by garrettw** [comment]
Check out the [releases](https://github.com/phpspec/phpspec/releases) page.
