### ISSUE TITLE
PHP 8.2 deprecation warning: Creation of dynamic property PhpSpec\Loader\StreamWrapper::$context is deprecated 

### ISSUE THREAD

**Issue by TysonAndre** [phpspec/phpspec#1434]
Internally, https://www.php.net/stream_wrapper_register works by adding a property `context` to the instance of the StreamWrapper

Adding a declared `/** @var resource|null */ public $context;` would work around this (or `#[\AllowDynamicProperties]`)

```
php > class FakeStreamWrapper {}
php > stream_wrapper_register('fake', FakeStreamWrapper::class);
php > file('fake://foo');
Deprecated: Creation of dynamic property FakeStreamWrapper::$context is deprecated in php shell code on line 1
Warning: file(fake://foo): Failed to open stream: "FakeStreamWrapper::stream_open" call failed in php shell code on line 1
```

When running test suites (e.g. of phpspec/prophecy) with php 8.2, errors such as these are seen (from opening files, which instantiates streamwrapper and adds the dynamic property `context`)

```
Deprecated: Creation of dynamic property PhpSpec\Loader\StreamWrapper::$context is deprecated in .../vendor/phpspec/phpspec/src/PhpSpec/Loader/ResourceLoader.php on line 61
Deprecated: Creation of dynamic property PhpSpec\Loader\StreamWrapper::$context is deprecated in .../vendor/phpspec/phpspec/src/PhpSpec/Util/MethodAnalyser.php on line 58

**Comment by gquemener** [comment]
Fixed by https://github.com/phpspec/phpspec/pull/1435

**Comment by andypost** [comment]
also it needs to allow 8.2 for composer, otherwise tests wont run

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/prophecy[1.9.0, ..., v1.10.3] require php ^5.3|^7.0 -> your php version (8.2.0-dev) does not satisfy that requirement.
    - phpspec/prophecy[1.11.0, ..., 1.11.1] require php ^7.2 -> your php version (8.2.0-dev) does not satisfy that requirement.
    - phpspec/prophecy[1.12.0, ..., 1.13.0] require php ^7.2 || ~8.0, <8.1 -> your php version (8.2.0-dev) does not satisfy that requirement.
```

**Comment by gquemener** [comment]
I have introduced such a change: https://github.com/phpspec/phpspec/pull/1435/files#diff-5c3fa597431eda03ac3339ae6bf7f05e1a50d6fc7333679ec38e21b337cb6721R17

**Comment by andypost** [comment]
I mean the `prophecy` said it it's not compatible so testing can't run on 8.2

**Comment by gquemener** [comment]
Yup, I've opened a [PR](https://github.com/phpspec/prophecy/pull/571) on prophecy to support 8.2, but it also requires phpspec (in dev). So one of those PR must be merged first so that the other starts passing.

**Comment by andypost** [comment]
It could be closed as https://github.com/phpspec/phpspec/pull/1435 been commited

**Comment by rogervila** [comment]
Let's wait for a new version to be released with 8.2 support before closing this Issue

**Comment by rogervila** [comment]
Hi @ciaranmcnulty, is there anything we can do on our side to help in releasing a new `7.x` version from `master` branch with PHP 8.2 support? 
Thank you!

**Comment by rogervila** [comment]
I made a PR to fix CI issues on the main branch (https://github.com/phpspec/phpspec/pull/1437)
