### ISSUE TITLE
PHP 8.3 support

### ISSUE THREAD

**Issue by rajeshreeputra** [phpspec/phpspec#1450]
What's the plan to provide support for PHP 8.3, which is scheduled for release on November 23, 2023, with the first RC version set to be release on August 31, 2023.

**Comment by rajeshreeputra** [comment]
Created [PR](https://github.com/phpspec/phpspec/pull/1449) attaching results:
<img width="1479" alt="Screenshot 2023-08-24 at 12 59 11 PM" src="https://github.com/phpspec/phpspec/assets/19570710/856de68b-e051-429c-95a5-20d3af108f6b">

**Comment by zrajic** [comment]
@ciaranmcnulty Are there any news on support for PHP 8.3? Thank you

**Comment by JurRutten** [comment]
+1 on this, any news?

**Comment by mneuville** [comment]
@ciaranmcnulty Do you have any news about php8.3 support? 🙏

**Comment by Keimpy** [comment]
+1

**Comment by jesperveldhuizen** [comment]
+1

**Comment by ciaranmcnulty** [comment]
Release 7.5.0 supports PHP 8.3 👍
