### ISSUE TITLE
Documentation site is down

### ISSUE THREAD

**Issue by ash-m** [phpspec/phpspec#1470]
https://www.phpspec.net is reporting:

> # Error 1014
> Ray ID: 8af9be107bf87c1c • 2024-08-07 19:41:08 UTC
> 
> ## CNAME Cross-User Banned
> 
> What happened?
> You've requested a page on a website that is part of the [Cloudflare](https://www.cloudflare.com/5xx-error-landing/) network. The host is configured as a CNAME across accounts on Cloudflare, which is not allowed by Cloudflare's security policy.
> 
> What can I do?
> If this is an R2 custom domain, it may still be initializing. If you have attempted to manually point a CNAME DNS record to your R2 bucket, you must do it using a custom domain. Refer to [R2's documentation](https://developers.cloudflare.com/r2/data-access/public-buckets/#connect-your-bucket-to-a-custom-domain) for details.
> 
> [Visit our website](https://www.cloudflare.com/5xx-error-landing/) to learn more about Cloudflare.

**Comment by ash-m** [comment]
Not sure who is administering the DNS for this, maybe @mdavis1982 (no idea, but authoritative origin has 'matt' in it :P)

Can someone look into this please? @ciaranmcnulty @MarcelloDuarte 

Thanks

**Comment by mdavis1982** [comment]
@ash-m It's not me, I'm afraid. I think @ciaranmcnulty was last managing the project, but also @MarcelloDuarte may know!

**Comment by jdreesen** [comment]
It works without the `www.`, see: #1475

**Comment by ash-m** [comment]
@jdreesen I see; weirdly, in-private browsing redirects `phpspec.net/` (with a trailing slash) to `www`. I guess it's just a caching problem. 

Thank you for the update.
