### ISSUE TITLE
PhpSpec not loading my classes on custom autoload namespace mapping

### ISSUE THREAD

**Issue by rodrigodiez** [phpspec/phpspec#150]
My first issue on GitHub so please be merciful ;)

**Summary**: PhpSpec is not finding my classes when trying to run examples against them. I'm forced to provide them separately because PhpSpec create them in a dir that doesn't match my needs

**Complete info**: I'm trying to develop some distributable components with PhpSpec. My project tree looks like this:

```
project
|-src/
|--FooClass.php
|-spec/
|--FooVendor/
|---Component/
|----FooComponent/
|-----FooClassSpec.php
|-composer.json
```

Since I try to make my project distributable I configured my project composer to load the component namespace from the `src/` dir like this:

``` json
# composer.json
"autoload": {
    "psr-0": { "FooVendor\\Component\\FooComponent": "src" }
},
```

My exame class looks like:

``` php
// src/FooClass.php
namespace FooVendor\Component\FooComponent;

class FooClass
{

}
```

Running `bin/phpspec`outputs:

```
FooVendor\Component\FooComponent/FooClass
  10  ! it is initializable
      class FooVendor\Component\FooComponent\FooClass does not exist.

                       100%                        1

1 example (1 broken)
8ms


Do you want me to create `FooVendor\Component\FooComponent\FooClass`
for you? [Y/n]
```

**Comment by FellowsDevel** [comment]
Add

```
suites:
   acme_suite:
       namespace:  Acme
       psr4_prefix:  Acme
       src_path:  src/Acme

``` 
to your phpspec.yml file


https://laracasts.com/discuss/channels/testing/when-i-try-to-setup-phpspec-for-psr-4-the-files-it-creates-are-not-placed-in-the-correct-namespace-folder
