### ISSUE TITLE
Shared Examples

### ISSUE THREAD

**Issue by hlegius** [phpspec/phpspec#343]
Hi folks!

There is any way to achieve **shared examples** like [RSpec](https://relishapp.com/rspec/rspec-core/v/3-0/docs/example-groups/shared-examples) does?

I read in #45 that v1 had that feature. If v2 has, I'd like to know how it works to write a doc for it.

Thanks!

**Comment by laland** [comment]
Oh, i need this feature so much...

**Comment by ciaranmcnulty** [comment]
This can be achieved using Traits.

I'm not sure repetitive examples are something we should encourage, it sounds like duplication of effort to me. I'm open to proposals with a clear use case though
