### ISSUE TITLE
[RFC] Data providers

### ISSUE THREAD

**Issue by drgomesp** [phpspec/phpspec#347]
I was recently checking out a talk from @MarcelloDuarte – [Test, Transform, Refactor](http://www.slideshare.net/marcello.duarte/test-transform-refactor), where there was some spec examples for an arabic to roman numeral converter algorithm close to this:

``` php
function it_returns_I_for_1()
{
    $this->fromArabic(1)->shouldReturn("I");
}

function it_returns_II_for_2()
{
    $this->fromArabic(2)->shouldReturn("II");
}

function it_returns_III_for_3()
{
    $this->fromArabic(3)->shouldReturn("III");
}

function it_returns_IV_for_4()
{
    $this->fromArabic(4)->shouldReturn("IV");
}

function it_returns_V_for_5()
{
    $this->fromArabic(5)->shouldReturn("V");
}
```

I was wondering that maybe this would be a perfect use case for data providers, but I'm not sure it's interesting inside the scope of BDD or phpspec itself.

What do you guys think?

**Comment by dramentol** [comment]
> Spec is not a testing tool and data providers is something that you mostly use for testing purpose but sometimes its hard to designe something without few examples.
> For example take a look at [this spec](https://github.com/coduo/php-to-string/blob/master/spec/Coduo/ToString/StringSpec.php). It could be much simpler:
> 
> ```
> <?php
> 
> namespace spec\Coduo\ToString;
> 
> use PhpSpec\ObjectBehavior;
> 
> class StringSpec extends ObjectBehavior
> {
>     /**
>      *  @dataProvider positiveConversionExamples
>      */
>     function it_convert_input_value_into_string($inputValue, $expectedValue)
>     {
>         $this->beConstructedWith($inputValue);
>         $this->__toString()->shouldReturn($expectedValue);
>     }
> 
>     public function positiveConversionExamples()
>     {
>         return array(
>             array(1 => '1'),
>             array(1.1 => '1.1'),
>             array(new \DateTime, '\DateTime'),
>         )
>     }
> }
> ```
> 
> I tried to implement data providers support as extension but it seems to be impossible because spec assumes that any argument of a example is a [Collabolator](https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Wrapper/Collaborator.php) or null.
> I'm just afraid that after implementing this feature people will start to use PHPSpec as a testing tool and their will write code first

That's probably why behat has data providers.
