### ISSUE TITLE
Is is possible to use PHPspec with non PSR-0/4 compliant code?

### ISSUE THREAD

**Issue by JHKennedy4** [phpspec/phpspec#383]
I have a large existing codebase that I would like to be able to test with phpspec. Thus far, I've been unsuccessful in getting phpspec to find my classes as they do not comply with any autoloading standard (it's a mess).

Is there a way to configure phpspec to use custom paths that are not PSR compliant?

**Comment by samsonasik** [comment]
if we have project that uses travis as CI, it doesn't work, and keep shows 0 specs, but works interestingly, it works locally... not sure if it a travis issue due read psr4_prefix config: https://twitter.com/samsonasik/status/648897902438428672
