### ISSUE TITLE
Online version of the doc

### ISSUE THREAD

**Issue by stof** [phpspec/phpspec#448]
What is the online version of the doc currently ? I saw some comments about ReadTheDocs in some PRs, and the doc is indeed rendered at http://phpspec.readthedocs.org/en/latest/ (and updated regularly as the last update is today).
However, the website still presents the documentation at http://www.phpspec.net/docs/introduction.html which looks much older

**Comment by stof** [comment]
@ciaranmcnulty @MarcelloDuarte  is there any news about changing the DNS ?

**Comment by MarcelloDuarte** [comment]
@ciaranmcnulty you should have the authorisation key on your email

**Comment by stof** [comment]
@ciaranmcnulty can you work on changing the phpspec.net DNS to make it point to the uptodate website on RTD rather than the old outdated one ?

**Comment by ciaranmcnulty** [comment]
Transfer is still pending, will do as soon as I get a notification it's complete.

**Comment by stof** [comment]
Closing. Se #582

**Comment by stof** [comment]
@ciaranmcnulty Can you also update the phpspec2-site repo description to mark it as obsolete (and updating the readme saying that everything is now in the phpspec repo itself) ?
