### ISSUE TITLE
Versioning Policy

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#562]
So, semver 2.0 says:

```
Given a version number MAJOR.MINOR.PATCH, increment the:

MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
```

My question is, as a specification tool what is our 'API'?

Is it:

  1. the methods used inside specs written by users
  2. all of 1 PLUS methods used by extensions
  3. all of 1 PLUS methods we decide are stable and mark with an @api annotation (Symfony-style)

If the answer is 1 then it makes BC policy adherence very easy, but makes life hard for extension writers
If the answer is 2 then it makes moving forwards refactoring the current design very difficult without rapidly incrementing the version number (problematic for branding perhaps)
If the answer is 3 then we need to go through the code marking extension points and possibly defining some clearer interfaces

Either way I would like to see agreement on which approach is preferred, and then commitment to sticking to the BC policy.

**Comment by everzet** [comment]
Because we never committed for a clean extension API, I'd go with 1. But that might be too rough of a move for people that did create extensions. Can we somehow identify how many extensions there are? If there's less than 5-10, then 2 and 3 do not matter as much.

**Comment by ciaranmcnulty** [comment]
There are >10 but I suspect some are old / no longer used. There certainly isn't a huge ecosystem.

We could adopt a 'tagged API only' policy and encourage extension writers to PR `@api` annotations onto the methods they are using. This would be a good way to encourage discussion about what is and is not supported for future.

@shanethehat and @jamescowie probably have a good perspective on how this would go down with extension developers.

**Comment by shanethehat** [comment]
I think that from MageSpec's point of view, the main pain points are things like Caller, which are large and so difficult to modify the behaviour of. Cleaning up the API and over time moving to the use of annotations to indicate 'safe' extension points sounds like it would be sensible, but there are definitely areas of the codebase that need breaking down to make that possible.

I would like to see us using interfaces for all of those core objects so that extensions can more easily swap out functionality in the container.

**Comment by ciaranmcnulty** [comment]
i guess now I'm lead maintainer I can be more opinionated?

I don't think we can commit to supporting semver, which isn't necessarily an issue as the project never actually stated it was using that scheme.

However, as @everzet put it in a recent conversation, the current policy is 'don't be an asshole to extension writers'.

I will write a versioning policy, the bullet points are:

* It's basically semver
* We won't break user specs
* We won't break internal APIs between patch versions
* BUT we may break internal APIs between minor versions if after discussion there is no sensible way to maintain compatibility, we commit to documenting the changes w/ migration suggestions, and we survey known extensions to assess impact.

This has some implications for extensions' composer dependencies, that we should proactively help with.

It should be a target that PhpSpec 3.0+ will use semver, and if we get to a point where we can do a 2.x LTS release then we will adopt semver from then onwards.

**Comment by ciaranmcnulty** [comment]
I wrote this up in the Wiki:

https://github.com/phpspec/phpspec/wiki
