### ISSUE TITLE
Remove deprecated function calls

### ISSUE THREAD

**Issue by WouterJ** [phpspec/phpspec#580]
Using Symfony 2.7@dev components, these deprecated errors are triggered when simply running `phpspec desc`:

* Deprecated: "Symfony\Component\Console\Helper\DialogHelper" is deprecated since version 2.5 and will be removed in 3.0. Use "Symfony\Component\Console
\Helper\QuestionHelper" instead.
* Deprecated: The ability to pass file names to Yaml::parse() was deprecated in 2.7 and will be removed in 3.0. Please, pass the contents of the file in
stead.

You should lower the error reporting level or increase dependencies to newer 2.5.*.\

**Comment by ciaranmcnulty** [comment]
Looking inside Console\IO, there are three methods that use `DialogHelper`: `ask`. `askAndValidate`, and `askQuestion`.  Of these only the last is actually used inside the codebase, and has a decent API. The first two are unused and are tightly coupled to the `DialogHelper` API.

It makes sense to me to deprecate the first two unused methods and not implement a `QuestionHelper`version of them.

**Comment by ciaranmcnulty** [comment]
The deprecated calls are now removed, and there is a travis build to warn us if any more turn up in unstable symfony versions.
