### ISSUE TITLE
Documentation migration

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#582]
@MarcelloDuarte can you please change the DNS so that phpspec.net points to readthedocs.org

This should just be a case of adding a CNAME to phpspec.readthedocs.org

**Comment by stof** [comment]
@ciaranmcnulty ping

**Comment by ciaranmcnulty** [comment]
@MarcelloDuarte It might be worth adding the CNAME on your DNS, if the transfer is going to take much longer. Or maybe a temp redirect on the existing site?

**Comment by ciaranmcnulty** [comment]
update: My registrar still says 'this transfer is in progress'

**Comment by ciaranmcnulty** [comment]
This now works for me; there may be some propagation delay

**Comment by stof** [comment]
@ciaranmcnulty there is actually a big issue here: http://www.phpspec.net indeed points to the new documentation, but http://phpspec.net still points to the old website

**Comment by ciaranmcnulty** [comment]
@stof Both resolve to readthedocs for me. You may have some caching happening?

```
;; ANSWER SECTION:
www.phpspec.net.	92	IN	CNAME	phpspec.readthedocs.org.
phpspec.readthedocs.org. 91	IN	A	162.209.114.75

;; ANSWER SECTION:
phpspec.net.		299	IN	A	162.209.114.75
```

**Comment by ciaranmcnulty** [comment]
@stof does it work for you yet?

**Comment by MarcelloDuarte** [comment]
@ciaranmcnulty in the composer example I still see `"phpspec/phpspec": "~2.0"`. I guess it's just that the docs haven't been updated?

**Comment by ciaranmcnulty** [comment]
Yep, although that's will still get you the latest version
