### ISSUE TITLE
Class does not exist loop

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#585]
This is a FAQ: If an autoloader is not configured, users get trapped in a loop where they are prompted to create the class, suite reruns, class does not exist,users are re-prompted.

This can be solved by checking class_exists directly after writing the file, although currently there's not a neat place to do this.

**Comment by codereviewvideos** [comment]
To add a little extra helper here, make sure your composer.json is as per the docs: 

http://www.phpspec.net/en/latest/

And also, run `composer dumpautoload` after making any adjustments. Solved it for me :)
