### ISSUE TITLE
composer installation is failing

### ISSUE THREAD

**Issue by gondo** [phpspec/phpspec#586]
in my composer i have `"phpspec/phpspec": "~2.0"` as per http://www.phpspec.net/#getting-started-with-phpspec
however im getting error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - phpspec/phpspec 2.1.0 requires phpspec/php-diff ~1.0.0 -> no matching package found.
    - phpspec/phpspec 2.0.1 requires phpspec/php-diff ~1.0.0 -> no matching package found.
    - phpspec/phpspec 2.0.0 requires phpspec/php-diff ~1.0.0 -> no matching package found.
    - Installation request for phpspec/phpspec ~2.0 -> satisfiable by phpspec/phpspec[2.0.0, 2.0.1, 2.1.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
```

checking `phpspec/phpspec` composer.json i see that it requires `"phpspec/php-diff": "~1.0.0",` https://github.com/phpspec/phpspec/blob/master/composer.json#L23

but such package doesn't exist according to https://packagist.org/packages/phpspec/php-diff
only `1.0.1`, `1.0.2`, `dev-master`

**Comment by stof** [comment]
We should add a branch-alias for the dev-master version of php-diff

**Comment by GrahamCampbell** [comment]
:+1:

**Comment by stof** [comment]
I just submitted https://github.com/phpspec/php-diff/pull/6

I don't know who are the maintainers for this repo though (there is a bunch of old pending PRs which have not been reviewed)
