### ISSUE TITLE
Divide by zero in ProgressFormatter

### ISSUE THREAD

**Issue by cxj** [phpspec/phpspec#596]
664$ phpspec run spec/Cxj/AdvisoryLockSpec.php

Warning: Division by zero in /Users/chris/disk2/work/phpspec/vendor/phpspec/phpspec/src/PhpSpec/Formatter/ProgressFormatter.php on line 90
                                                   0
0 specs
0 examples
0ms

665$ ls -l spec/Cxj/AdvisoryLockSpec.php
-rw-r--r--  1 cxj  users  899 Dec 29 14:21 spec/Cxj/AdvisoryLockSpec.php

666$ phpspec -V
phpspec version 2.1.0

**Comment by ciaranmcnulty** [comment]
Thanks for reporting this, it's fixed in 2.1.1
