### ISSUE TITLE
Add method visibility to generated classes

### ISSUE THREAD

**Issue by pedrochaves** [phpspec/phpspec#600]
I don't know if someone already asked this, but I did a quick search here on the old issues here and could not find anything related, so here it goes:

Is there a reason why the default `it_is_initializable` method of the generated spec does not have its visibility explicit (as `public`)?
I think it would be nice to add the method visibility to the default `it_is_initializable` method as good practice (as the PSR2 recommends), and leave for the programmer to remove it to improve the legibility depending on the case. Unless there's a different reason other than legibility that I am missing here.

What do you guys think?

**Comment by whatthejeff** [comment]
https://github.com/phpspec/phpspec/pull/590#issuecomment-67995169

**Comment by pedrochaves** [comment]
Whoa, I don't know how I missed it, sorry :(

I understand the motives now, thank you.

**Comment by whatthejeff** [comment]
No problem :)
