### ISSUE TITLE
Progress bar always displaying 100%

### ISSUE THREAD

**Issue by james75** [phpspec/phpspec#602]
Great work on 2.1.1 our progress bar now moves which is nice. However is still is always displaying 100% ???

![screen shot 2015-01-09 at 14 58 33](https://cloud.githubusercontent.com/assets/975619/5681384/15fe7f42-9810-11e4-8f6b-638734c65ad6.png)

**Comment by ciaranmcnulty** [comment]
The number is 'of examples so far'. We don't actually know the number of examples until after execution so the bat's width is based on progress at the specs level

**Comment by james75** [comment]
I see so what is the 100% on the bar used to indicate then?

**Comment by ciaranmcnulty** [comment]
Percentage of executed examples that passed

**Comment by everzet** [comment]
@james75 percentage of the colour it is on.

**Comment by ciaranmcnulty** [comment]
100% is good

**Comment by james75** [comment]
got it :) thank you for clarification

**Comment by everzet** [comment]
@james75 progress bar is replacement for:

```
100% passing
0% failing
0% erroring
0% pending
212 specs
```
