### ISSUE TITLE
Can't test classes that are created in Spec file.

### ISSUE THREAD

**Issue by willharrison** [phpspec/phpspec#607]
I am trying to test an abstract base class, so I have created a mock class to extend this ABC.  I put the mock class above my Spec class.  However, all test pass regardless of whether or not they should for these test.  Is this supposed to happen?

For example, if I comment out `$this->beConstructedWith($model)`, the test still passes.

    <?php

    namespace spec\Blog\Repository;

    use Blog\Repository\AbstractRepository;
    use Illuminate\Database\Eloquent\Model;
    use PhpSpec\ObjectBehavior;
    use Prophecy\Argument;

    class MockAbstractRepository extends AbstractRepository {

        function __construct(Model $model)
        {
            $this->model = $model;
        }
    }

    class AbstractRepositorySpec extends ObjectBehavior
    {

        function let(Model $model)
        {
            $this->beConstructedWith($model);
        }

        function it_is_initializable()
        {
            $this->shouldHaveType('MockAbstractRepository');
        }
    }

**Comment by jakzal** [comment]
Use `beAnInstanceOf` to change the class you're speccing.

```php
namespace spec\Blog\Repository;

use Blog\Repository\AbstractRepository;
use Illuminate\Database\Eloquent\Model;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class MockAbstractRepository extends AbstractRepository
{
    public function __construct(Model $model)
    {
        $this->model = $model;
    }
}

class AbstractRepositorySpec extends ObjectBehavior
{

    function let(Model $model)
    {
        $this->beAnInstanceOf(MockAbstractRepository::class);
        // or
        // $this->beAnInstanceOf('spec\Blog\Repository\MockAbstractRepository');

        $this->beConstructedWith($model);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(MockAbstractRepository::class);
    }
}

```

**Comment by willharrison** [comment]
Doing this does not fix the issue.  I can still comment out `beConstructedWith()` and receive a passing test.

**Comment by ciaranmcnulty** [comment]
this is probably the same issue as #601.You will find that when you test actually behaviours (not shouldHaveType) you will start triggering the real constructor.

**Comment by willharrison** [comment]
I have other tests in the Spec, I just didn't list them, for preference to brevity.  These tests all pass regardless of if they are supposed to.

For example, if I change `$this->all()->shouldReturn(true)` to `$this->all()->shouldReturn(false)`, this test should fail.  However, it still passes.

    function it_should_use_model_to_get_all(Model $model)
    {
        $model->all()->shouldBeCalled()->willReturn(true);
        $this->all()->shouldReturn(true);
    }

**Comment by willharrison** [comment]
I found the issue.  The mock class needs to be defined under the Spec class.
