### ISSUE TITLE
Mock doesn't implement Interface correctly 

### ISSUE THREAD

**Issue by kanedo** [phpspec/phpspec#620]
Hi,
I'm trying to mock a Interface which is implemented like this:
```php
interface HTTPInterface {

  /**
   * returns content of the url given as parameter
   *
   * @param string $url
   *
   * @return string
   */
  public function getUrlContents( $url );
}
```

the application uses an dependency injector `$app` which returns the wanted HTTP class (implementing the Interface). My spec looks like this:
```php
    function it_should_export_sites( ConfigStore $configStore, HTTPInterface $httpHelper, FileSystem $fileSystem ){
        // [...]
        $app = AppContainer::getInstance();
        $app['extension.static_exporter.helper.http'] = $httpHelper;

        $this->setAppContainer( $app );

        $this->exportSites();
    }

```

When I run the spec I get the following error:
```
error: Argument 1 passed to Sitemap::setHTTPAdapter() must implement interface
     HTTPInterface, instance of PhpSpec\Wrapper\Collaborator given
```

What went wrong? I also tried to mock it on my own but it didn't work.

**Comment by ciaranmcnulty** [comment]
Try:

```php
$app['extension.static_exporter.helper.http'] = $httpHelper->getWrappedObject()
```

**Comment by stof** [comment]
Inside the spec, arguments are not the real mock. they are PhpSpec Collaborator objects. If you need to pass it explicitly to a method which is not wrapped by PhpSpec, you need to call ``getWrappedObject()``.

**Comment by stof** [comment]
And note that this is an opiniated choice. If you cannot run the spec of your class without changing the global scope here, it is a design smell for your class, and PhpSpec explicitly wants to point such smells by making them hard to spec

**Comment by kanedo** [comment]
Hi,
first of all `getWrappedObject()` does what I wanted. 
But thanks @stof for pointing that out. I now see the design flaw and how to refactor it!
