### ISSUE TITLE
www-less domain not working

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#624]
Need to set up forwarding, that readthedocs.org doesn't support.

A small cloud instance serving 301s should suffice

**Comment by ciaranmcnulty** [comment]
I think I've been able to add this redirect via my DNS provider, but would be good if someone else can confirm it's working for them?

**Comment by avant1** [comment]
If I understand problem correctly, everything working fine for me now:
```
people@people:~$ curl -I phpspec.net
HTTP/1.1 302 Moved Temporarily
Date: Sun, 25 Jan 2015 06:48:36 GMT
Connection: keep-alive
Location: http://www.phpspec.net/
Server: cloudflare-nginx
```

**Comment by ciaranmcnulty** [comment]
Great, thanks. I'll change that to a 301 if it's redirecting to the right place.
