### ISSUE TITLE
ObjectBehavior::offsetUnset() tries to return void method result.

### ISSUE THREAD

**Issue by Dragonrun1** [phpspec/phpspec#626]
OffsetUnset from ArrayAccess is a void method but ObjectBehavior is using a return statement with it. 

Didn't do pull request since just need to change the one line by dropping the return off the front of it.

**Comment by ciaranmcnulty** [comment]
Thanks for raising this, it looks like a simple change.

We'll need to do a little checking to make sure nobody is calling this and using the return value.

**Comment by Dragonrun1** [comment]
Actually doesn't matter if they are since void is the default return value from a method except if you return something else.
