### ISSUE TITLE
Generating private constructors

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#631]
This was included in @thecrimpmaster's PR but got dropped to be re-addressed later.

After a named constructor is generated from beConstructedThrough, we should offer to generate a private constructor.

 * Would you like me to add a private constructor to User for you? [Y/n]

This would only trigger if there was no existing `__construct`

**Comment by everzet** [comment]
Yes. Empty `private` constructor without arguments.

**Comment by everzet** [comment]
And while you're on it - make default class template to have `final` keyword.

**Comment by ciaranmcnulty** [comment]
@everzet let's have the conversation about final again... separate issue plz.

**Comment by ciaranmcnulty** [comment]
yes constructor would be:

```
    private function __construct(){}
```
