### ISSUE TITLE
Composer's autoload included twice

### ISSUE THREAD

**Issue by gnugat** [phpspec/phpspec#634]
Hi everyone,

I'm using phpspec and [Puli](http://docs.puli.io/en/latest/) in the following project: https://github.com/gnugat/medio.

When running the specifications, I get a notice warning:

    PHP Notice:  Constant PULI_FACTORY_CLASS already defined in /home/foobar/medio/vendor/autoload.php on line 8

At first I thought Puli was at cause, but the only thing it does is adding a constant in the autoload file. After a check, I've discovered that phpspec includes this file twice. Is it an issue? If not I can ake a PR on Puli to double check if the constant already exists.

**Comment by henrikbjorn** [comment]
Seems like there is two cases of autoloading defined here https://github.com/phpspec/phpspec/blob/master/bin/phpspec#L6

**Comment by ciaranmcnulty** [comment]
One is trying to load the project's auto loader, the other is trying to load phpspec's auto loader.

These are only different in the case of a global PhpSpec install, or when using the phar

**Comment by ciaranmcnulty** [comment]
There's certainly some cleanup possible there in terms of checking the paths checked in the 2nd half aren't duplicating paths in the first half, it's grown fairly haphazardly over time. I'd be nervous of change there without additional integration test coverage.

**Comment by stof** [comment]
Is Puli defining a constant directly in vendor/autoload.php when using it ? This should be reported as a bug in Puli. the vendor/autoload.php file generated by Composer is explicitly designed to be included as many times as you want (as it gives you access to the autoloader instance)

**Comment by gnugat** [comment]
@stof: yes, that's what [Puli's Composer plugin](https://github.com/puli/composer-plugin) does.
So you think it should check if it's already defined? I'll close this issue and open one in the Puli's dedicated bug tracker.

**Comment by ciaranmcnulty** [comment]
I wonder why we aren't doing `require_once` - performance?

**Comment by stof** [comment]
@ciaranmcnulty yes, because we know about the Composer contract so it is safe to avoid the extra checks of the _once version.

And the reason for the composer contract is that it is the only way to give access to the classloader by returning it from the file. If you require_once, you don't receive the classloader when the file inclusion is skipped (because of already done previously) but ``true`` instead.
