### ISSUE TITLE
Problem Testing Constructor Exceptions

### ISSUE THREAD

**Issue by mdavis1982** [phpspec/phpspec#642]
I've got a constructor that accepts two `double` parameters. It fires off the setting to two different methods and each has the potential to throw an exception. I can't get my specs to pass, no matter what I do.

The full code is here: https://gist.github.com/mdavis1982/50ea2507d3603fabed59

Removing either one of the two tests makes the other one pass.

**Comment by ciaranmcnulty** [comment]
```php
        if ($longitude < 180 || $longitude > 180) {
            throw new InvalidLongitudeException();
        }
```

Your only valid longitude is exactly 180..., you probably want to check for `< -180`

**Comment by mdavis1982** [comment]
Gah! I'm an idiot! :smile: 

Thanks, @ciaranmcnulty!

**Comment by ciaranmcnulty** [comment]
The tests were telling you what was happening ;-)

**Comment by mdavis1982** [comment]
It's a bit weird that one of them still passed though... And removing either one made the other one pass

**Comment by ciaranmcnulty** [comment]
What may be confusing the issue is that your first spec won't be failing; shouldHaveType doesn't actually cause instantiation

**Comment by mdavis1982** [comment]
Yes... That, and the expected exception class type was truncated
