### ISSUE TITLE
ObjectBehavior does not load generated classes

### ISSUE THREAD

**Issue by maxcal** [phpspec/phpspec#645]
I´m trying to follow along the steps in the [Getting Started](http://www.phpspec.net/en/latest/manual/getting-started.html) section of the manual.

I have a fresh project folder with only a composer.json file containing phpspec 2.1.1.

When I run:
```
    vendor/bin/phpspec desc TagHelper
    vendor/bin/phpspec run
```
I get prompted to create the class:
```                                                                    
  Do you want me to create `TagHelper` for you?                       
                                                               [Y/n] 
Y
Class TagHelper created in /Users/maxcal/projects/TagHelper/src/TagHelper.

```
But phpspec does not seem to be able to load the class since the spec errors `class TagHelper does not exist.` and again prompts me to create the class. 

Answering N, and re-running `phpspec run` does not seem to change anything.

**Comment by ciaranmcnulty** [comment]
Do you have an autoloader set up in the composer.json?

**Comment by maxcal** [comment]
No, I did not have one setup. 

Adding a autoloader resolved the issue although it might be nice to have a note in the readme.

I was assuming that phpspec took care of autoloading generated classes.

```
   "autoload": {
    	"classmap": ["src/"]
    }
``

**Comment by ciaranmcnulty** [comment]
No, we rely on the project having an autoloader.

There is an open issue to improve the error message #585
