### ISSUE TITLE
Not possible to test exception handler

### ISSUE THREAD

**Issue by egeriis** [phpspec/phpspec#650]
I have tried various solutions, but from an answer on StackOverflow to a couple of attempt to write a functioning test, it seems that it's not possible to test exception handlers with phpspec.

Is it feasible to implement a solution for this or is it by design impossible?

My broken test method:

```php
class ClientSpec extends ObjectBehavior
{
    function it_should_catch_exceptions(Config $config)
    {
        $e = new Exception('test exception');
        $this->catchException($e)->shouldBeCalled();
        throw $e;
    }
}
```

More details: http://stackoverflow.com/questions/28876489/how-to-test-exception-handler-with-phpspec/

**Comment by ciaranmcnulty** [comment]
I'm not sure where you are expecting the exception to be called - you're throwing it from within the spec, so there is no registered handler. You're also injecting a Double of a `Config` object but doing nothing with it.

What behaviour of `Client` are you trying to spec?

**Comment by egeriis** [comment]
The `Config` is not relevant for this test, it's legacy from another test.

When `Client` is instantiated it will call `set_exception_handler` and point it towards it's own `catchException` method.

**Comment by stof** [comment]
@egeriis if you are specifying an exception handler, you should call ``$this->catchException($e)`` and assert what it does.

Throwing an exception will not trigger your own exception handler in this case but the PhpSpec one (and it is not a spec anymore if you expect it to call your own handler but a functional test, which is not what PhpSpec is aimed at)

**Comment by egeriis** [comment]
I want to spec that the `Client` should set an exception handler upon construction.

This works:

```php
    function it_should_register_exception_handler()
    {
        $expectedHandler = [$this->getWrappedObject(), 'catchException'];
        $this->exceptionHandler()->shouldReturn(set_exception_handler(null));
    }
```

**Comment by ciaranmcnulty** [comment]
As @stof says this is verging on end-to-end testing so isn't something PhpSpec will explicitly support.
