### ISSUE TITLE
Mock a Closure as method argument

### ISSUE THREAD

**Issue by chentsulin** [phpspec/phpspec#653]
For testing Laravel 5 middleware

```php
class AfterMiddleware implements Middleware {
    public function handle($request, Closure $next)
    {
        $response = $next($request);
        // Perform action
        return $response;
    }
}
```
I try to mock `$next` in different way, but no anyone works.
`$next()` can't  mock like a method call.

Is it possible to mock a Closure?

**Comment by stof** [comment]
What is the issue you get exactly ?

**Comment by chentsulin** [comment]
```php
function it_should_set_something_to_response_header(Request $req, Response $res, Closure $next) {
        //....
        $next($req)->willReturn($res); // this line
        //....
}
```
will get a `Fatal error: Function name must be a string`

**Comment by Taluu** [comment]
Why bother with a mock when you can create your own closure ?

**Comment by ciaranmcnulty** [comment]
Indeed this is not something that is directly supported by Prophecy, it'll be easier to make a real closure

```php
$next = function() {
    return $res->getWrappedObject();
}
```

**Comment by ciaranmcnulty** [comment]
The solution to this is to use a real callback. If this isn't appropriate please raise a feature request against `phpspec/prophecy`

**Comment by ghola** [comment]
The solution provided by @ciaranmcnulty works fine for some situations but not for those in which you want to assert that a callable has been called. My solution for such a scenario was to create an invokable class like so:

```php
class MockableCallable
{
    public function __invoke()
    {
        return $this->invoke();
    }

    public function invoke()
    {

    }
}
```

and then in my test i would do something like:

```php
function it_tests_callable_being_called(MockableCallable $next)
{
    $next->invoke()->shouldBeCalled();
    
    // the rest of the code that actually triggers the call of the callable
}
```
