### ISSUE TITLE
Autoloader requirement is poorly documented

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#655]
We should make it explicit in the docs how PhpSpec uses the project's autoloader and does not have its own.

**Comment by MarcoDeBortoli** [comment]
@ciaranmcnulty @richardmiller on this topic... is there a way to tell PhpSpec to don't use the `src` folder at all and have a project layout like:

```bash
.
├── app/
├── lib/
├── spec/
├── composer.json
├── composer.lock
└── phpspec.yml.dist 
```

**Comment by richardmiller** [comment]
This is a bit better documented now at http://www.phpspec.net/en/latest/cookbook/configuration.html 
You should be able to set src_path to 'app' to get this to work.

**Comment by MarcoDeBortoli** [comment]
I know, I tried having two src_path app and lib respectively for each suite but it didn't quite work. I'll try again fresh to make sure I did everything fine, if it fails again I'll push the code so you can have a look maybe. I'll keep you posted, thanks.

**Comment by ciaranmcnulty** [comment]
@MarcoDeBortoli What does this have to do with Autoloaders?

**Comment by richardmiller** [comment]
Probably meant for #556
