### ISSUE TITLE
PHP7 and EngineExceptions

### ISSUE THREAD

**Issue by mbeccati** [phpspec/phpspec#656]
Since the introduction of engine exceptions, argument type mismatch E_RECOVERABLE_ERRORs now throw EngineExceptions, which end up as E_ERRORs and can't be intecepted by the error handler set up in ErrorMaintainer.php.

I might be wrong, but I don't think that a similar behaviour can be achieved with exceptions at all.

**Comment by stof** [comment]
#659 seems to be the same issue

**Comment by mbeccati** [comment]
@stof yes it is

**Comment by stof** [comment]
OK, I'm closing this issue in favor of #659 even if it is the oldest one, because there is more context in #659.
