### ISSUE TITLE
Extended diff for mock call with exact parameters

### ISSUE THREAD

**Issue by avant1** [phpspec/phpspec#658]
Hello.

I think it would be nice if wrong mock call arguments (defined as exact values) could be outputed in a more detailed way.
For now, if exact value is string and it's length is more than 50 characters, only first 50 characters are displayed (even in verbose mode) for both expected and actual arguments (see https://github.com/phpspec/prophecy/blob/master/src/Prophecy/Util/StringUtil.php#L57)
And we get output like
```
  18  ! it can handle event
      method call:
        Double\Acme\Context\P2->set("data", "some really long string, containing more than 50 "
...)
      was not expected.
      Expected calls are:
        - set(exact("data"), exact("some really long string, containing more than 50 "...))
```
which is pretty useless if difference between strings is after 50 character. Even if difference is in first characters, it is not always easy to find it, cause strings are not aligned:
```
  18  it can handle event
      expected "some really long strin, c"..., but got "some really long string, "....

      @@ -1,1 +1,1 @@
      -some really long strin, containing more than 25 characters
      +some really long string, containing more than 25 characters
```

If I understand source code correctly, extended expected and actual arguments diff can be implemented as extension (via replacing default *formatter.presenter* by one which can detect `\Prophecy\Exception\Call\UnexpectedCallException`) and generating diffs for arguments.

I found no existing extensions which implement similar functionality. I could try to create one.
But I think it makes sence to be implemented in core. What do you think?

**Comment by ciaranmcnulty** [comment]
:+1: It makes sense to me to improve the reporting in core. Do you want to try it?

**Comment by avant1** [comment]
I'd love to.
Probably, I can find free time during next week.
