### ISSUE TITLE
Testing Named Constructor Exception Handling

### ISSUE THREAD

**Issue by mdavis1982** [phpspec/phpspec#663]
I'm wondering how I can test a named constructor throwing an exception.

For example, when not using a named constructor, I can do the following:

```php
function it_should_throw_an_exception_when_constructing_with_an_invalid_message()
{
    $this
        ->shouldThrow(InvalidMessageException::class)
        ->during('__construct', [self::INVALID_MESSAGE]);
}
```

But I can't do this when testing a named constructor.

Also, when trying to test that the object is initializable, I get an error:

```php
function let()
{
    $this->beConstructedWith('withPlainText', [self::VALID_MESSAGE]);
}

function it_is_initializable()
{
    $this->shouldHaveType('App\Email\Message');
}
```

And the error is:

```
  21  - it is initializable
      method App\Email\Message::__construct not visible.
```

**Comment by mdavis1982** [comment]
I'm an idiot... This works fine if you do it properly :smile: 

Closing!

**Comment by everzet** [comment]
For future references - `$this->beConstructedThrough()` is a way to do it properly :)
