### ISSUE TITLE
Second autoload check not working in Laravel

### ISSUE THREAD

**Issue by RyanHavoc** [phpspec/phpspec#668]
Hi,

So I trying to use phpspec with Laravel (also I have laravel sat in a sub-folder). I get this:

    $ phpspec
    You must set up the project dependencies, run the following commands:
    curl -s http://getcomposer.org/installer | php
    php composer.phar install

If I edit vendor/bin/phpspec to this:

    #!/usr/bin/env php
    <?php

    define('PHPSPEC_VERSION', '2.1.1');

    if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
        require $autoload;
    } elseif (is_file($autoload = getcwd() . '/../../autoload.php')) {
        require $autoload;
    }

    //if (is_file($autoload = __DIR__ . '/../vendor/autoload.php')) {
    //    require($autoload);
    //} elseif (is_file($autoload = __DIR__ . '/../../../autoload.php')) {
    //    require($autoload);
    //} else {
    //    fwrite(STDERR,
    //        'You must set up the project dependencies, run the following commands:' . PHP_EOL .
    //        'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
    //        'php composer.phar install' . PHP_EOL
    //    );
    //    exit(1);
    //}

    $app = new PhpSpec\Console\Application(PHPSPEC_VERSION);
    $app->run();

It works as expected. I assume because phpspec is included in the Laravel autoload.php file.

How do I get it to work with the second if uncommented?

**Comment by ciaranmcnulty** [comment]
You're typing phpspec without a path? What folder are you in when you run it?

If it's resolving to `vendor/bin/phpspec` I would expect it to find the autoload.php

**Comment by RyanHavoc** [comment]
I have vendor/bin included in my $PATH. Behat for example works fine.

I'm running phpspec from the root of my Laravel folder. If I do:

    $ which phpspec
    vendor/bin/phpspec

The second if (on my machine) is looking here:

    die(__DIR__ . '/../vendor/autoload.php');
    /Users/RyanT/Code/pmh.local/laravel/vendor/bin/../vendor/autoload.php

And here:
    die(__DIR__ . '/../../../autoload.php');
    /Users/RyanT/Code/pmh.local/laravel/vendor/bin/../../../autoload.php

Before elsing to the standard error...

**Comment by ciaranmcnulty** [comment]
And there is a file in `vendor/autoload.php`? 

This may well be a bug, most people run phpspec from `bin/phpspec`

**Comment by RyanHavoc** [comment]
Yes there is an vendor/autoload.php. I can confirm that if I run:

    $ vendor/phpspec/phpspec/bin/phpspec

It works. I had to chmod +x on it first though.

**Comment by RyanHavoc** [comment]
Just tried running through the different tools in Laravels vendor/bin:

behat = works
phpspec = error above
phpunit = very similar issue to phpspec
psysh (i.e. php artisan tinker) = works

**Comment by ciaranmcnulty** [comment]
I guess there should be a third condition in the 2nd if to catch this case then... it seems messy though.

**Comment by RyanHavoc** [comment]
Agreed. This works though:

    #!/usr/bin/env php
    <?php

    define('PHPSPEC_VERSION', '2.1.1');


    if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
        require $autoload;
    } elseif (is_file($autoload = getcwd() . '/../../autoload.php')) {
        require $autoload;
    }


    if (is_file($autoload = __DIR__ . '/../vendor/autoload.php')) {
        require($autoload);
    } elseif (is_file($autoload = __DIR__ . '/../../../autoload.php')) {
        require($autoload);
    } elseif (is_file($autoload = __DIR__ . '/../autoload.php')) {
        require($autoload);
    } else {
        fwrite(STDERR,
            'You must set up the project dependencies, run the following commands:' . PHP_EOL .
            'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
            'php composer.phar install' . PHP_EOL
        );
        exit(1);
    }

    $app = new PhpSpec\Console\Application(PHPSPEC_VERSION);
    $app->run();

Should I update my pull-request?

**Comment by ciaranmcnulty** [comment]
Make a new one please

**Comment by GrahamCampbell** [comment]
I think phpunit had this brought up recently. They decided not to implement a simelar fix.

**Comment by RyanHavoc** [comment]
I was just checking phpunit and it does have a similar issue. Requires an additional:

    __DIR__ . '/../autoload.php'

For the autoload. Would appear that it's only broken when phpunit and phpspec are ran from vendor/bin.

When ran from their package folder they work...

**Comment by stof** [comment]
@RyanHavoc can you show what ``vendor/bin/phpspec`` contains ? Is it a symlink to ``vendor/phpspec/phpspec/bin/phpspec`` or a regular file ? And if it is a regular file, what is its content ?

**Comment by RyanHavoc** [comment]
@stof it's a regular file, as if it's been copied in from vendor/phpspec/phpspec/bin/phpspec as it's a duplicate.

Here's the contents by default:

    #!/usr/bin/env php
    <?php

    define('PHPSPEC_VERSION', '2.1.1');


    if (is_file($autoload = getcwd() . '/vendor/autoload.php')) {
        require $autoload;
    } elseif (is_file($autoload = getcwd() . '/../../autoload.php')) {
        require $autoload;
    }


    if (is_file($autoload = __DIR__ . '/../vendor/autoload.php')) {
        require($autoload);
    } elseif (is_file($autoload = __DIR__ . '/../../../autoload.php')) {
        require($autoload);
    } else {
        fwrite(STDERR,
            'You must set up the project dependencies, run the following commands:' . PHP_EOL .
            'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
            'php composer.phar install' . PHP_EOL
        );
        exit(1);
    }

    $app = new PhpSpec\Console\Application(PHPSPEC_VERSION);
    $app->run();

**Comment by stof** [comment]
@RyanHavoc If it is a copy of ``vendor/phpspec/phpspec/bin/phpspec``, you have a major bug in your setup. Copying the file to a different location indeed breaks all file references in it. and this is **not** what composer is doing when creating ``vendor/bin/phpspec``. It either creates a symlink or a proxy bin file (forwarding the call to the original file).
So check your stack to determine which tool overwrote the file created by Composer with a broken one.

**Comment by RyanHavoc** [comment]
@stof Odd. I didn't actually place the files in there myself... I'm using this with Laravel, I'll try rebuilding it.

**Comment by stof** [comment]
Well, if Laravel overwrites the bin files generated by composer in a way breaking them, it should be reported as a critical bug in Laravel.

**Comment by RyanHavoc** [comment]
@stof I delete out all the vendor packages and the composer.lock and installed everything from scratch. This time phpspec is a symlink and working...

I can't think of anything i've done that would have caused them to be copied files rather than symlinks. I did notice a slight increment in the Laravel version number when it downloaded it again though. Maybe they fixed this issue.

**Comment by ciaranmcnulty** [comment]
Laravel doesn't have a committed `vendor` folder so I don't think it's a bug there. It would be good if you can reproduce how this has happened... was it at any point copied to an FS that doesn't support symlinks, or FTPed, or ZIPed etc?

**Comment by RyanHavoc** [comment]
I'm using Homestead (so Vagrant) locally. I wonder if something got screwed up with the file syncing...?

Other than that it hasn't been FTPed or ZIPed.

**Comment by stof** [comment]
it may be related to the file syncing, indeed
