### ISSUE TITLE
@mixin annotation for spec classes

### ISSUE THREAD

**Issue by avant1** [phpspec/phpspec#677]
Description and discussion of *@*mixin annotation can be found here:
https://youtrack.jetbrains.com/issue/WI-1730

It would be very useful for PHPStorm users to have this annotation in spec classes. Adding this annotationallows to use code completion, refactoring (renaming methods), "go to method".
As I know, it is supported only by PHPStorm, so there is no benefit for those who do not use that IDE (or do not use IDE at all). But also there is no harm too :smile:

For my active projects I've edited specification template file in `vendor` dir. But I'm not sure that *@*mixin annotation is widely known, and I'm sure that modification of vendors code is not a good idea.

Can I create pull request for this feature, or it would be better done as extension?

**Comment by ciaranmcnulty** [comment]
There are still lots of problems with phpstorm even using this - it's also not really true; the SUS isn't a mixin of the spec

It's probably better if PhpStorm just starts supporting PhpSpec, IMO

**Comment by stof** [comment]
I think a PhpSpec plugin enhancing the autocompletion for PhpSpec would be better. ``@mixin`` is wrong: the magic methods correspond to names of the SUS, but return values don't. So you would still not have the proper completion for assertions.
Btw, someone writing such a plugin should also consider supporting the Prophecy autocompletion in other contexts (PHPUnit 4.5+ for instance)

**Comment by ciaranmcnulty** [comment]
The problem with writing a plugin is AFAIK there's no history of PhpStorm adopting community plugins into core; with Behat they implemented integration themselves with some help from Konstantin. I've talked to them a couple of times about it and they'll add PhpSpec integration 'when there is enough demand'

**Comment by svemir** [comment]
Voted for phpspec support here: https://youtrack.jetbrains.com/issue/WI-22670

**Comment by stof** [comment]
@ciaranmcnulty the community plugin for Behat was making PhpStorm crash on boot. This is a valid reason not to adopt it in core.
For Symfony2, Jetbrains recommends the awesome community plugin (they even use it as example in their blog post announcements about each improvement of the plugin API since a long time)

**Comment by ciaranmcnulty** [comment]
Yeah I mean they have a split between 'recommending plugins' and 'building themselves in core', they don't adopt plugins into the core distribution
