### ISSUE TITLE
Simple less than / greater than matchers?

### ISSUE THREAD

**Issue by wheelsandcogs** [phpspec/phpspec#678]
Is there a reason there are default matchers for:
 * equality
 * count
 * type
 * string end
 * string start

but no default matchers for:
 * less than
 * less than or equal to
 * greater than
 * greater than or equal to

I'm assuming this is by design, but I can't work out why?

**Comment by jakubzapletal** [comment]
I agree with @ciaranmcnulty , you should mostly (always) know exact output. In your case I would create factory for DateTime object and injected as a service, then you can easily expect exact DateTime object as a result.

**Comment by ciaranmcnulty** [comment]
In this example you might want something like `shouldBeBefore`, which can be achieved with an inline Matcher.

However your test doesn't strike me as great, the start date could be set to `1970-01-01` for instance.

My preference in most time-bound testing is to externalise the time element and treat the clock as an infrastructure layer, as @jakubzapletal is suggesting.

**Comment by ciaranmcnulty** [comment]
i don't think 'fuzzy' matchers are something we want in core - they can be done with inline matchers, or I suggest an extension would be more appropriate

**Comment by zygous** [comment]
I was just looking for these matchers too.

My use case is implementing some comparison methods. I don't care what number the method returns as long as it's either negative, positive or zero, and I think the actual numbers are implementation details and therefore shouldn't be specified exactly.

Of course, as I type this I realise I'd be just as happy with shouldBeNegative() and shouldBePositive(), and that PhpSpec itself has a Behat feature implementing shouldBePositive() as an inline matcher. So, all's good (but perhaps it's worth "promoting" shouldBeNegative() and shouldBePositive() to "real" matchers...).
