### ISSUE TITLE
Custom path for specs to live in one directory and my models to live in another

### ISSUE THREAD

**Issue by webkenny** [phpspec/phpspec#689]
Forgive me as I know this was somewhat discussed in #156 but I am totally perplexed. I didn't want to necro a very old issue. Assume an abridged directory structure like this in a custom Silex project that already has App as a namespace in `composer.json`:

```
*Project Root*
- src
 - App
  - Entity
   - Word.php
- tests
 - behat
 - phpspec
    - spec
 ...
 ...
- web
- composer.json
...
```

Also assume I want to test the Word class... I would like to put my specs inside `tests/phpspec/spec/WordSpec.php` and the class it is referring to in `App/Entity/Word.php`

So I spun up a `phpspec.yml` in my project root, as the doc seems to suggest, which looks like this:

```
suites:
    words:
        namespace: 'App'
        spec_path: 'tests/phpspec/'
        src_path: 'app/'
```

Now I run the nifty `desc` function. This (sort of) works with:
```
$ phpspec desc App\Model\Word
Specification for AppModelWord created in /path/to/project/tests/phpspec/spec/AppModelWordSpec.php.
```

I say sort of because I would expect it to be called `WordSpec` but that's splitting hairs AFAIC.

Lastly, I run the tests because my Word class already exists:

```
Minmi:silexicon ksilanskas$ phpspec run
AppModelWord
  10  - it is initializable
      class AppModelWord does not exist.

                                      100%                                       1
1 specs
1 example (1 broken)
10ms

[Do you want me to create `AppModelWord` for you?]
```

So the basic question is: **How does one tell phpspec that the specs, etc. should live in one directory while the classes it describes live in another?**

Am I missing some fundamental obviousness here about how this works? I'm happy to help improve the documentation around this to make it more clear if I can just find out what I am doing wrong.

**Comment by webkenny** [comment]
I'm so sorry for wasting cycles. I'll see myself out. Silly misunderstanding of what was what in the docs. Simply making a small change to my yml file fixed it. Here it is for those that encounter this in the future:

```
suites:
    app_suite:
        namespace: 'App\Entity'
        spec_path: 'tests/phpspec/'
```

Because, recall that src_path is always src by default. See [this section of the documentation](http://www.phpspec.net/en/latest/cookbook/configuration.html#spec-and-source-locations) for the details and read it twice.

I'll see myself out. :)

**Comment by ciaranmcnulty** [comment]
When you type:

```
phpspec desc App\Model\Word
```

The reason you get 'AppModelWorld' is that is the string phpspec receives as its argument - your shell thoughtfully removes the backslashes for you as possible escape codes.

Unfortunately because this happens before the tool is even invoked, we cannot tell where you wanted the delimiters placed.

You can instead use either:

```
phpspec desc 'App\Model\Word'
```

or 

```
phpspec desc App/Model/Word
```

(depending on your shell)

**Comment by webkenny** [comment]
Thanks for the reply. I realized only minutes after posting that I wasn't reading the documentation correctly. phpspec is an excellent tool and I appreciate your work and response. Have a good weekend!

**Comment by ciaranmcnulty** [comment]
Don't worry about opening the issue, it helps us see which areas of docs are unclear
