### ISSUE TITLE
RFE display PHP version used during test

### ISSUE THREAD

**Issue by remicollet** [phpspec/phpspec#692]
Hi,

Could you please consider adding the PHP version used in the output.

This will be useful for multi-version environment, especially when using module environment, and for bug report, when the reporter copy/paste the output.

FYI, this have be implemented in phpunit https://github.com/sebastianbergmann/phpunit/pull/1682

**Comment by ciaranmcnulty** [comment]
Adding extra information in the formatter is something I'm not keen to do in the core codebase. 

This is something an extension could do, however I'm not clear why the system executing the tests doesn't know what PHP version it's using?

**Comment by remicollet** [comment]
>...however I'm not clear why the system executing the tests doesn't know what PHP version it's using?

Because when you have multiple parallel installed versions, such as the ones provided by SCL in RPM distributions.

I know other distro only provide a single PHP version, so, I understand you don't care... :(

**Comment by ciaranmcnulty** [comment]
I understand it's a valid use case for you, but I don't want to add extra output for all other users.

Like I said this may be a good idea for an extension, or you can probably use the `--bootstrap` option to include a script that outputs this information for you.
