### ISSUE TITLE
Renaming a namespace. (caching?)

### ISSUE THREAD

**Issue by bweston92** [phpspec/phpspec#695]
I made a full package for my project that handled some generic stuff. Later I changed the namespace (PSR-4 from `ABC\Package` to `DEF\Package`). Every file got updated including `composer.json` and `phpspec.yml`.

However the machine I renamed everything on no longer works, it says the namespace doesn't exist, so I tested it on my other machine and everything works perfectly. Is there some sort of cache?

**Comment by ciaranmcnulty** [comment]
If you make a change to composer autoloading you have to run the dump-autoloading composer command (or update or install)
