### ISSUE TITLE
Possible Infinite loop on case insensitive filesystem

### ISSUE THREAD

**Issue by gsdevme** [phpspec/phpspec#698]
Working with an existing namespace you can end up miss typing the wrong case and get into an infinite loop on the class not existing on a case insensitive filesystem.

To solve it, it could read the spec filepath back before creating the actual class to silently fix the error for the user or just throw an error to alert the user to there mistake. 

Maybe it should know its already tried to create it even, rather than looping

![Image](http://imgr.es/36VS)

Notice the `namespace` & `shouldHaveType` are wrong however its in the correct Folder due to the folder already existing

![image](http://imgr.es/36VT)

Happy to go fix this.

**Comment by ciaranmcnulty** [comment]
This is definitely something that needs fixing. 

To cut off one dead end: I tried adding a class_exists check and found that composer caches the result, which stops that approach from working, ie class_exists will still return false after the file is written out.

The best approach will be to pass knowledge of which files have been written out to the next execution.

**Comment by ciaranmcnulty** [comment]
Actually your comment is about a specific autoloading failure but I think we should solve the generic case (eg no auto loader configured at all)
