### ISSUE TITLE
Creating Mocks in Spec files

### ISSUE THREAD

**Issue by wheelsandcogs** [phpspec/phpspec#701]
I'm creating a Serializer class that can convert to and from JSON. It has a deserialize() method which takes a JSON string, and an FQCN to create a hydrated class using the JSON data:

```php
/**
 * Hydrate an object from serialized data.
 *
 * @param string $data   The data to deserialize
 * @param string $type   The FQCN of the class to deserialize to
 * @param string $format The format the data is in (e.g. json)
 *
 * @return object
 */
public static function deserialize($data, $type, $format)
{
    switch (strtolower($format)) {
        case 'json':
            $object = new $type;
            // hydrate the object

            break;
    }
}
```

When I use the FQCN of an existing class (e.g. an Entity) it works fine, but I don't want to tie my spec to an Entity. I can't use \stdClass because my deserializer only hydrates properties that exist in the class and ignores everything else by design, so I've tried creating a Mock class at the top of the file:

```php
namespace spec\PW\Access\ODM\Serializer;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class MockDocument
{
    private $id, $html;
    public function setId($id) { $this->id = $id; }
    public function setHtml($html) { $this->html = $html; }
}

class SerializerSpec extends ObjectBehavior
{
    function it_can_deserialize_a_json_object()
    {
        $json = '{ "id":"1", "html":"<p>Foo<\/p>" }';

        $expected = new MockDocument();
        $expected->setId('1');
        $expected->setHtml('<p>Foo</p>');

        $this->deserialize($json, 'spec\PW\Access\ODM\Serializer\MockDocument', 'json')->shouldBeLike($expected);
    }
}
```
Unfortunately phpspec then ignores my SerializerSpec completely - I assume it's ignoring the file if the first class found doesn't end in "Spec"?

Is there a way to create a new Class just for the spec that the Serializer class will be able to instantiate from the FQCN (i.e. not modifying the method to pass an instance)?

**Comment by stof** [comment]
You could define your MockDocument after the SerializerSpec in the file, and it should work fine.

The other solution is to put your MockDocument in a separate file and make it autoloadable (through the ``autoload-dev`` composer setting for instance)

**Comment by wheelsandcogs** [comment]
I could've sworn I tried that earlier and it didn't work, but I've just tried again and it works, doh.

Cheers.
