### ISSUE TITLE
shouldReturn and multile strings

### ISSUE THREAD

**Issue by huglester** [phpspec/phpspec#703]
Hello Everyone.

I have come to one problem. I am building some module generator, and the problem I came up with, making multine strings go green is quite difficult... 
Maybe there is a way, that I can 'echo' real actual output from method (without diff or something).
So I just can copy/paste it to the function?

because writing something like this with many spaces and bigger methods is quote hard. Or maybe I am missing something:
```php
    function it_composes_single_fillable_array()
    {
        $this->getFillableFields()->shouldReturn("
        'question',
        'answer',
        'is_active',
    ");
    }
```

Sometime you just type line by line and run tests in parallel so you can 'align them'

Thank you!

**Comment by avant1** [comment]
> Maybe there is a way, that I can 'echo' real actual output from method (without diff or something).

You can use `ObjectBehavior::getWrappedObject()` for that. It will return object under specification.
So, your spec could look like

```php
    function it_composes_single_fillable_array()
    {
        $actual = $this->getWrappedObject()->getFillabeFields();
        
        $this->getFillableFields()->shouldReturn("
        'question',
        'answer',
        'is_active',
    ");
    }
```

Spaces troubleshooting sometimes can be rather hard. Usually I put actual return string to file and view it with all symbols (spaces, new lines, carriage return) being shown. 
Hope this helps.

**Comment by huglester** [comment]
Thank you, that, indeed may help! I probably should file_put_contents later, so it will, for sure be easier to debug. Thank you! I think we can close this?

**Comment by avant1** [comment]
Sure, feel free to close issue if it is solved.
