### ISSUE TITLE
Cannot test final class extending Exception

### ISSUE THREAD

**Issue by sagikazarmark** [phpspec/phpspec#704]
I met with an interesting issue during testing a final class: I generated the spec using the describe command which automatically generated the `it_is_initializable` test.

When I ran the test the following exception occured:

```
  18  ! is initializable
        exception [exc:ReflectionException("Class CLASS is an internal class marked as final that cannot be instantiated without invoking its constructor")] has been thrown.
```

The class itself does not have a constructor, its parent has.

I added a `beConstructedWith` in the `let` method, but the exception still existed.

The "solution" was simply adding a method call before `shouldHaveType` which instantiates the class, for example: `$this->getWrappedObject();`

Am I missing something or this is a bug?

The relevant code:

``` php
    function let()
    {
        $this->beConstructedWith('Message', 0);
    }

    function it_is_initializable()
    {
        $this->getWrappedObject();
        $this->shouldHaveType('CLASS');
    }
```

I am on the latest stable.

**Comment by ciaranmcnulty** [comment]
Interesting, can you give some detail about what the object you're testing is and what it extends?

**Comment by sagikazarmark** [comment]
Here is the full class:

``` php
use Psr\Http\Message\ResponseInterface;

/**
 * Thrown if an HTTP error occures
 */
final class HttpException extends \RuntimeException implements TransportException
{
    /**
     * @param ResponseInterface $response
     *
     * @return self
     */
    public static function createFromResponse(ResponseInterface $response)
    {
        return new self('An HTTP error occurred: ' . $response->getReasonPhrase(), $response->getStatusCode());
    }
}
```

`TransportException` is just an empty interface

**Comment by ciaranmcnulty** [comment]
Ohh there is some weird special case around exceptions. You could try `return new static` maybe.

I don't have time to reproduce right now I'm afraid but maybe someone else can debug it.

**Comment by sagikazarmark** [comment]
If you take a look at the spec code I pasted, you can see that the problem has nothing to do with the named static constructor.

Even the initialization fails.

**Comment by ciaranmcnulty** [comment]
I mean that the way Exceptions handle overridden constructors has some special logic around it that is different to how PHP normally works, IIRC.

**Comment by sagikazarmark** [comment]
Ah, I see. Well, this hack solved the problem (for now). But I guess it is a bug then.

**Comment by jon-acker** [comment]
@sagikazarmark I've tried to recreate your error, with the same spec and class (with the exception that I was not using ResponseInterface) and I could not recreate the error:
```php
final class SomeExtendedClass extends \RuntimeException implements SomeInterface
{
    public static function createFromResponse($response)
    {
        return new self('An HTTP error occurred');
    }
}
```

```php
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class SomeExtendedClassSpec extends ObjectBehavior
{
    function let()
    {
        $this->beConstructedWith('Message', 0);
    }
    
    function it_is_initializable()
    {
        $this->shouldHaveType('PhpSpec\SomeExtendedClass');
    }
}
```
I'm on latest master .

**Comment by sagikazarmark** [comment]
The full code can be found here: https://github.com/fxmlrpc/transport

I tried it with master as well with no luck. Only extra information I could find is that code coverage is enabled in the config.

**Comment by sagikazarmark** [comment]
A new info: works fine on 5.5, the issue only occurred on 5.6. I am using phpbrew, just installed a fresh PHP 5.6.6 and the issue still occurs.

**Comment by ciaranmcnulty** [comment]
This makes sense and I can reproduce the problem.

The following works in PHP5.5 but not in PHP5.6:

```php

class SomeExceptionSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType('SomeException');
    }
}


final class SomeException extends \Exception
{
}

```

**Comment by ciaranmcnulty** [comment]
This behaviour is delegated to Doctrine\Instantiator but we seem to use it differently when instantiating because of `shouldHaveType` and `getWrappedObject`.

This inconsistency was pointed out in #601 but hasn't yet been addressed

**Comment by sagikazarmark** [comment]
Is it possible to workaround the problem and call `getWrappedObject` from an extension? That way spec tests wouldn't need any change, only the configuration. Much cleaner and easier to remove.

**Comment by ciaranmcnulty** [comment]
We should fix it internally in `Subject`

**Comment by sagikazarmark** [comment]
Yeah, I only meant it as a temporary fix.

**Comment by ciaranmcnulty** [comment]
The way you've solved it with `getWrappedObject` will probably continue to work.

**Comment by sagikazarmark** [comment]
I know, but wanted to avoid it if possible.

**Comment by ciaranmcnulty** [comment]
I'm fairly confident this is an error in `doctrine\instantiator` and have opened a PR with a fix.

**Comment by ciaranmcnulty** [comment]
This is now fixed by `doctrine\instantiator` 1.0.5, which is compatible with our tagging.

The next version of PhpSpec should depend on this.

@sagikazarmark Can you please do a composer update and check that the error has been fixed for you?

**Comment by ciaranmcnulty** [comment]
(Thanks @ocramius BTW)

**Comment by Ocramius** [comment]
yw \o/

**Comment by Ocramius** [comment]
Ref: doctrine/instantiator#20

**Comment by sagikazarmark** [comment]
It is fixed, thanks.

**Comment by ciaranmcnulty** [comment]
Fantastic.
