### ISSUE TITLE
Generating factory methods.

### ISSUE THREAD

**Issue by hendore** [phpspec/phpspec#705]
Please, forgive me if I am doing something wrong. I have the following example in my Order spec.

```php
function it_can_be_constructed_from_a_cart(CartInterface $cart)
{
    $this->beConstructedThrough('fromCart', [$cart]);
}
```

When running the spec, I'm not asked if I want to create the Order::fromCart(CartInterface $cart) method. The example runs and passes, even without the static method ever existing?

**Comment by jakubzapletal** [comment]
It's because you defined how you want to initialize the object but didn't call any matcher or anything what would start the initialization. The initialization can be run for example by `$this->getWrappedObject()`.
```php
function it_can_be_constructed_from_a_cart(CartInterface $cart)
{
    $this->beConstructedThrough('fromCart', [$cart]);
    $this->getWrappedObject();
}
```

**Comment by hendore** [comment]
Thank you @jakubzapletal that works, however I realised I could return anything from the factory method and the example would still pass, so instead of using getWrappedObject I'm asserting the object under test is of a specific type.

```php
function it_can_be_constructed_from_a_cart(CartInterface $cart)
{
    $this->beConstructedThrough('fromCart', [$cart]);
    $this->shouldHaveType('Checkout\Order');
}
```

Thanks.

**Comment by ciaranmcnulty** [comment]
Thanks for answering this @jakubzapletal!
