### ISSUE TITLE
Creating a collaborator without passing a param

### ISSUE THREAD

**Issue by wheelsandcogs** [phpspec/phpspec#707]
Is there a way to create a collaborator without passing it in as a param?

I need a helper function that creates a new collaborator each time it is called, but I need to pass other params into the helper, e.g. something like:

```php
class MySpec extends ObjectBehaviour
{
	function it_does_something()
	{
	    $this->mockStripeRequest($method, $path, $params, $mockResponse);

	    $order->setStripeFee($amount)->shouldBeCalled();
	    $this->someFunctionThatUsesStripeAPI($order);
	}

	protected function mockStripeRequest($method, $path, $params, $mockResponse)
	{
		$client = Collaborator::beADoubleOf('Stripe\HttpClient\ClientInterface');

		$client->request($method, $path, $data)
			->willReturn([json_encode($response), 200]);

		Stripe\ApiRequestor::setHttpClient($client->getWrappedObject());
	}
}
```

Basically I need a mocked $client, but I can't pass it in...

**Comment by ciaranmcnulty** [comment]
I'd type hint the collaborator in it_does_something and then pass it as a param to mockStripeRequest

**Comment by wheelsandcogs** [comment]
I've tried this, but I have more than one example, and I need a fresh $client for each example.

**Comment by wheelsandcogs** [comment]
Oh wait, I could create a new client in each example, I see.

**Comment by ciaranmcnulty** [comment]
Yeah exactly. You can of course make the prophet object explicitly if you need to, see the phpspec/prophecy docs

**Comment by wheelsandcogs** [comment]
If anyone needs to do this, as @ciaranmcnulty says just use the Prophet object and remember to call `->reveal()` instead of `->getWrappedObject()`.

```php
$client = $this->prophet->prophesize('Stripe\HttpClient\ClientInterface');
$client->request(...)->willReturn(...);
ApiRequestor::setHttpClient($client->reveal());
```

**Comment by stof** [comment]
Anyway, you could just get the client through the normal creation of collaborators. Examples are isolated. Collaborators are not shared between examples.
