### ISSUE TITLE
Array type hint in constructor raises invalid argument exception

### ISSUE THREAD

**Issue by Sukhrob** [phpspec/phpspec#710]
In class file:

    public function __construct(array $array)
    {
        $this->array= $array;
    }

In spec file:

    function let(array $array) // Tried with and without "array" type hint
    {
        $this->beConstructedWith($array);
    }

Raises
error: Argument 1 passed to __construct() must be of type array, object given.

**Comment by avant1** [comment]
phpspec assumes that everything you want to get in example (or let/letgo methods) arguments is a "mock" (or a spy, i'm actually not good at terminology) of actual object you will use in that example.

When you don't type hint `let` method argument, special object (which is instanceof `\stdClass`) is being passed to your constructor. But if `__construct` of actual class has `array` type hint, then php will generate error (cause object is not array obviously).

When you type hint spec method argument as `array`, special object is being passed to spec method too, and error is being raised for the same reason.

You can solve this problem passing regular array (created manually) to `beConstructedWith`.
Your spec file could contain:
```php
function let()
{
    $this->beConstructedWith(array());
}
```
Usually constructor array parameter infuences the object behaviour, so it makes sense to pass different arrays and test them separately. So usually you don't ask phpspec "just give me any array I could create my object". But if you need "any array" - you can easily create empty array manually. 

Also I agree it is a bit confusing for phpspec newcomers. Probably more verbose error should be raised when example argument is type hinted as array.

**Comment by Sukhrob** [comment]
You are right, @avant1. Thanks
