### ISSUE TITLE
Add Config option to auto-add files to git

### ISSUE THREAD

**Issue by kayladnls** [phpspec/phpspec#720]
I propose a config option in phpspec.yml that allows for the generated spec file to be automatically added to git when you run `phpspec desc Some/Class/Name`

Thoughts?

**Comment by ciaranmcnulty** [comment]
Sounds reasonable I guess. And something similar after creating new classes/interfaces?

We could make it a generic hook for 'a command to run after a file is generated' rather than git-specific

**Comment by kayladnls** [comment]
Oh yes, that's a much better solution. Would we be able to pass a variable (the name of the file just created) to the command? 

I want to avoid having to use `git add --all`

**Comment by ciaranmcnulty** [comment]
Yeah I'm sure some placeholder could be inserted.

I'm just thinking about whether this makes sense in the core rather than in an extension.

**Comment by kayladnls** [comment]
It's something I run into constantly. If it's not a larger issue, I'd be happy to write an extension for it.

**Comment by ciaranmcnulty** [comment]
Having thought about it it's a bit out of scope for the core too. If @shanethehat's #723 is merged (no reason why not right now) there'll be an event an Extension can hook into to do this, if you're up for working on one.
