### ISSUE TITLE
Drop support for PHP 5.3.x

### ISSUE THREAD

**Issue by shanethehat** [phpspec/phpspec#725]
Travis just failed one of my PRs because I used short array syntax. I was surprised that phpspec still tests against 5.3 because the version is completely obsolete and we should be discouraging its use.

How do people feel about dropping support for 5.3.x?

**Comment by ciaranmcnulty** [comment]
I would drop 5.3.x in a minor release (maybe 2.3.0) if I didn't think it would break people's expectations.

My reading of SemVer is that it's about API changes, not about dependency changes. However, some projects wait for major versions before doing this stuff. Zend for instance don't, and drop PHP versions during minor release.

I'm definitely going to be dropping old PHP versions in 3.0.0 but that's not on the roadmap just yet. I'd be interested to hear opinions on whether dropping the completely out-of-date 5.3.x  would be antisocial.

**Comment by jon-acker** [comment]
Dropping php 5.3.x in version 3.0.0 sounds like a sensible idea. I'm sure there's a hell of a lot of code that uses the older array() notation.

**Comment by ciaranmcnulty** [comment]
Dropping in 3.0.0 is a done deal.

The open question is dropping 5.3.x in a minor 2.x version.

**Comment by shanethehat** [comment]
I wonder how many users of phpspec are actually fixed to 5.3.x? Probably quite a few when you consider legacy production environments. That's not to say that you'd be excluding them exactly though, they could always pin to 2.2.x if that's their requirement and they can't upgrade, but by forcing them to take action we might push a few into upgrading PHP instead.

**Comment by ciaranmcnulty** [comment]
We'd change the `php` requirement in composer so those people wouldn't get upgraded anyway unless they forced it.

Maybe that's an option if we commit to bugfixes for the release prior to dumping 5.3?

**Comment by sroze** [comment]
As PhpSpec is mainly used in development environment, I'd consider that the minimum PHP version can be bumped as part of a minor version update, especially given that PHP 5.3 is now extremely old to be present on many dev or CI environments.

**Comment by ciaranmcnulty** [comment]
Legacy projects will keep getting compatible versions and their CI will pass (unless I go crazy and start deleting tags).

I guess it's whether there are 5.3 projects under active development.

**Comment by GrahamCampbell** [comment]
:+1: for dropping php 5.3 in 3.x. phpunit is dropping 5.3, 5.4, and 5.5 in it's 5.x release and will be dropping 5.6 in it's 6.x release.

**Comment by richardmiller** [comment]
Is there any reason not to be dropping 5.4 as well?

**Comment by shanethehat** [comment]
I don't think there is. Like Ciaran said, we can pin the version in composer to protect people on old versions. I also don't think that it needs to wait for a major version bump, this isn't breaking the API.

**Comment by richardmiller** [comment]
I don't have a strong opinion on whether this should mean a major version bump. If it does need a major version bump then bump the major version :)

**Comment by GrahamCampbell** [comment]
> Is there any reason not to be dropping 5.4 as well?

Yes. It's no longer receiving security updates from the php core team very shortly.

**Comment by richardmiller** [comment]
That's the reason for dropping it

**Comment by GrahamCampbell** [comment]
That's a good reason as far as I'm concerned. I don't know about you, but I'm not prepared to run code that I know has massive vulnerabilities in it.

**Comment by shanethehat** [comment]
5.4 is supported until September: http://php.net/supported-versions.php

**Comment by shanethehat** [comment]
It'll be dead by the time we've finished discussing it :wink:

**Comment by richardmiller** [comment]
I think that it should be dropped, I was asking if there were any reasons not to.

phpspec supporting 5.4 isn't forcing anyone to use 5.4 though.

**Comment by GrahamCampbell** [comment]
I'd really like to see php 5.3 dropped, but I'm not that fussed about 5.4 for now.

**Comment by bamarni** [comment]
:+1: for dropping 5.4 support too, it would allow to update the [specification template](https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/CodeGenerator/Generator/templates/specification.template) with a use statement and `$this->shouldHaveType(ClassName::class)`, thus showing an example of how to avoid FQCN as strings in specs.

**Comment by adamelso** [comment]
@bamarni Bear in mind this won't work when you're specing a new class as PHP will complain that the class does not exist (yet).

**Comment by stof** [comment]
@adamelso no. ``Foo::class`` is resolved at compile-time and does not care about undefined classes. It does not autoload the class

**Comment by adamelso** [comment]
@stof That's true. Even so, it's probably not good practice [for the reasons outlined in this Sylius PR](https://github.com/Sylius/Sylius/pull/3736#discussion_r47912695).

**Comment by ciaranmcnulty** [comment]
I'm not convinced at all by that PR, FYI.

Anyhow if you didn't see it, PhpSpec 5.x will continue to support 5.3 Actively until around June, then in bug fix mode until summer 2017. 

PhpSpec 3.0 will only support 5.6 and 7.0+ and will be released around June 2016.

See https://github.com/phpspec/phpspec/wiki#roadmap

**Comment by bamarni** [comment]
@adamelso : I had been switching to this and phpspec is still able to create the new class file when missing. Anyways that's not the topic of this issue, thanks for the info about roadmap @ciaranmcnulty :+1:

**Comment by pamil** [comment]
@adamelso @ciaranmcnulty the main reason behind leaving string FQCNs in `it_is_initializable()` method was the ease of maintenance - changing to `::class` would require everyone contributing to modify their templates or automatically generated specs manually. If PhpSpec uses `::class` in the default templates, I'm almost sure that Sylius will adopt the same convention too.

**Comment by stof** [comment]
@pamil they even said it explicitly, so no need to assume: https://github.com/Sylius/Sylius/pull/3736#issuecomment-165737301

**Comment by ciaranmcnulty** [comment]
I intend to make `::class` the default in 3.0 unless
there is a good reason

**Comment by sroze** [comment]
I would actually remove this `shouldHaveType` thing... That's more testing PhpSpec that something else IMO.

**Comment by ciaranmcnulty** [comment]
@sroze if there's no assertion we don't instantiate the class so class generation doesn't happen.

**Comment by avant1** [comment]
Support for PHP versions prior to 5.6 was removed in *3.0*, so the issue can be closed.

**Comment by ciaranmcnulty** [comment]
Thanks ;-)
