### ISSUE TITLE
stalls then spits out a never ending stack trace

### ISSUE THREAD

**Issue by dadamssg** [phpspec/phpspec#738]
I've been using phpspec to do most of my testing for a while now. I've never run into this before. In one of my specs, if i try to call a method on a mock object, phpspec stalls then starts spitting out a never ending stack trace forcing me to Control+C the task. 

Here's the class being tested.

```php
<?php

namespace Acme\Project\Domain\Statistic\Middleware;

use Acme\Project\Domain\Statistic\Naming\ObjectNamer;
use Acme\Project\Domain\Statistic\Gatherer;
use SimpleBus\Message\Bus\Middleware\MessageBusMiddleware;

class CommandStatisticsMiddleware implements MessageBusMiddleware
{
    /**
     * @var ObjectNamer
     */
    private $namer;

    /**
     * @var Gatherer
     */
    private $gatherer;

    /**
     * @param ObjectNamer $namer
     * @param Gatherer $gatherer
     */
    public function __construct(ObjectNamer $namer, Gatherer $gatherer)
    {
        $this->namer = $namer;
        $this->gatherer = $gatherer;
    }

    /**
     * {@inheritdoc}
     */
    public function handle($command, callable $next)
    {
        $name = $this->namer->name($command);

        $this->gatherer->increment($name);
        $this->gatherer->time($name, function () use ($next, $command) {
            $next($command);
        });
    }
}
```

And the spec

```php
<?php

namespace Spec\Acme\Project\Domain\Statistic\Middleware;

use Acme\Project\Domain\Statistic\Command\CommandNamer;
use Acme\Project\Domain\Statistic\Gatherer;
use Acme\Project\Domain\Statistic\Middleware\CommandStatisticsMiddleware;
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class CommandStatisticsMiddlewareSpec extends ObjectBehavior
{
    function let(ObjectNamer $namer, Gatherer $gatherer)
    {
        $this->beConstructedWith($namer, $gatherer);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(CommandStatisticsMiddleware::CLASS);
    }

    function it_gathers_increment_stat(ObjectNamer $namer, Gatherer $gatherer)
    {
        $command = new \stdClass();
        $next = function ($arg) {};

        $namer->name($command)->willReturn($statName = "foobar");

        $gatherer->increment($statName)->shouldBeCalled();

        $this->handle($command, $next);
    }
}
```

I tried to pipe the stack trace to a file but php ran out of memory which makes me think there may be a recursion issue or it might have something to do with the `callable` typehint(?). I don't think i've spec'd a class with that before.

**Comment by ciaranmcnulty** [comment]
Ok I can see what's happening. This is a Prophecy issue.

As soon as you describe one method call on a double (in this case `$gatherer->increment(...)`) you have to describe them all. You have not described that `$gatherer->time(...)` will be called so Prophecy is throwing an exception.

For some reason, the output where Prophecy shows you what the expected and actual calls were is causing the failure - there's probably some problem showing you `$time, $next, [$command]`, especially if `$next` is callable.

Short term you can solve this by describing the call to `->time()`

**Comment by dadamssg** [comment]
unfortunately not. I just tried this the same thing happened. 

```php
<?php

class CommandStatisticsMiddlewareSpec extends ObjectBehavior
{
    function let(ObjectNamer $namer, Gatherer $gatherer)
    {
        $this->beConstructedWith($namer, $gatherer);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType(CommandStatisticsMiddleware::CLASS);
    }

    function it_gathers_increment_stat(ObjectNamer $namer, Gatherer $gatherer)
    {
        $command = new \stdClass();
        $next = function ($arg) {};

        $namer->name($command)->willReturn($statName = "foobar");

        $gatherer->increment($statName)->shouldBeCalled();
        $gatherer->time($statName, function () {})->shouldBeCalled();

        $this->handle($command, $next);
    }
}
```

**Comment by ciaranmcnulty** [comment]
Sorry, possibly I confused the issue by not noticing you were describing the `time()` call

**Comment by dadamssg** [comment]
ahh no you didn't. I realized i had some minor changes in my original post and edited it. The code in my original post is what i tried first and the code in the second one is what i tried and got the same result. Sorry for the confusion.

**Comment by ciaranmcnulty** [comment]
Yees, the comparison of lambdas isn't working correctly. This works for me:

```php
$gatherer->time($statName, Argument::any())->shouldBeCalled();
```

It seems the callables a) aren't equal in Prophecy's eyes and b) it has issues showing you the error message.

**Comment by dadamssg** [comment]
Ah yeah you're right.That works for me too. Strange. Thanks for looking into this!

**Comment by ciaranmcnulty** [comment]
If I get a chance I'll raise with Prophecy, otherwise feel free to yourself. It's something we need to fix for sure.
