### ISSUE TITLE
Behat test fails randomly

### ISSUE THREAD

**Issue by nsitbon** [phpspec/phpspec#740]
the scenario 'Generating a class outside of autoloadable paths gives a warning' in features/code_generation/developer_generates_class.feature fails randomly. 
I found the issue came from the terminal width. With some widths the word 'autoload' is split (see screenshot) causing the test to fail.
![phpspec](https://cloud.githubusercontent.com/assets/1663411/8618574/ea13fd50-270f-11e5-9872-4cd68f097f37.jpg)
I don't really know if the test should be rewritten of if it is a beat issue.
I'm running the tests on Mac OS X (last version) with iterm 2.

**Comment by ciaranmcnulty** [comment]
That formatting is pretty dodgy indeed, thanks for reporting. Either the behat test can get more liberal or the tool can format the message more intelligently.

**Comment by avant1** [comment]
Changing console application terminal dimensions (method *\Symfony\Component\Console\Application::setTerminalDimensions*) probably will help with that issue. But that more looks like a hack, not a solution.

**Comment by ciaranmcnulty** [comment]
The actual output should wrap better IMO



—
