### ISSUE TITLE
It won't create method for me if the class followed by a comment.

### ISSUE THREAD

**Issue by erdemkeren** [phpspec/phpspec#741]
Hello, here is an example php file structure:

    <?php
        namespace Foo;

        class Bar
        {
            [...]
        }

    // End of bar class.

And the spec:

    <?php
        class BarSpec extends ObjectBehavior
        {

            function it_is_initializable()
            {
                $this->shouldHaveType('Foo\Bar');
            }

            function it_calls_a_method_to_do_sth()
            {
                $this->doSth();
            }
            
        }
        
If you are describing a class inside a file structure like that, phpspec will endlessly ask to create the undefined method for you, but it won't be able to do it. Like this:

> Foo/Bar
>  9  - it calls a method to do sth
>      method Foo\Bar::doSth not found.
>
>                        50%                              1
> 1 specs
> 1 examples (1 passed, 1 broken)
> 1ms
>
>
>  Do you want me to create
>  `Foo\Bar::doSth()` for you?
>                                                 [Y/n]
> Y
>   Method Foo\Bar::doSth() has been created.
> 
> Foo/Bar
>  28  - it calls a method to do sth
>      method Foo\Bar::doSth not found.
>
>                        50%                              1
> 1 specs
> 1 examples (1passed, 1 broken)
> 2ms
>
>
>  Do you want me to create
>  `Foo\Bar::doSth()` for you?
>                                                 [Y/n]
> Really?
> fooproj [master] $

**Comment by ismatkurt** [comment]
+1

**Comment by shanethehat** [comment]
Which version of phpspec are you using? This might be fixed in the 2.3.0 beta because the logic for placing the new method was rewritten.

**Comment by erdemkeren** [comment]
Hmm I'll check it out. Using 2.1 at the moment.

**Comment by erdemkeren** [comment]
I updated to 2.3.0 beta; yes, the behavior changed but still buggy. When I add the comment at the end of the file, it placed the new function between the namespace and the use lines, causing a syntax error like;

    <?php
    namespace Foo\Bar;

    use Foo\Baz;
    use Foo\Qux;
    use Foo\Ba

        public function bugOnMethodCreate()
        {
            // TODO: write logic here
        }

    rBaz;
    use ...;

    /**
     * Class starts here
     */
    class Quux 
    {
        // Class body here.
    }

    // End of quux class.

**Comment by ciaranmcnulty** [comment]
Hanks for catching it. I don't think we need to fix in older versions because the model is so different but it should be fixed for 2.3

**Comment by shanethehat** [comment]
@erdemkeren that's bizarre, well found. So that I can recreate it please could you post the complete spec and class examples? I didn't see the same behaviour on a really trivial test, so there must be something I'm missing.

```
<?php

namespace spec\PhpSpec;

use PhpSpec\ObjectBehavior;

class TestSpec extends ObjectBehavior
{
   function it_should_break()
   {
       $this->breakClass()->shouldReturn('oops');
   }
}
```

```
<?php
namespace PhpSpec;

use Symfony\Component\DependencyInjection\ParameterBag;
use Symfony\Component\Yaml\Exception\RuntimeException;

/**
 * Class starts here
 */
class Test
{
    // Class body here.
}

// End of test class.
```

**Comment by erdemkeren** [comment]
Thanks, Here is an example which will cause some trouble (not fatal, but that was chance).

Pave the way for it:
File: Dev/app/Contracts/TestCalculatorInterface.php

    <?php

    namespace Dev\Contracts;

    interface TestCalculatorInterface
    {
	
    }

File: Dev/app/Contracts/TestRepositoryInterface.php

    <?php

    namespace Dev\Contracts;

    interface TestRepositoryInterface
    {
    
    }

File: Dev/spec/Services/TestServiceSpec.php

    <?php

    namespace spec\Dev\Services;

    use PhpSpec\ObjectBehavior;
    use Prophecy\Argument;
    use Dev\Contracts\TestCalculatorInterface;
    use Dev\Contracts\TestRepositoryInterface;

    class TestServiceSpec extends ObjectBehavior
    {
	    function let(TestCalculatorInterface $testCalculator, TestRepositoryInterface $testRepository)
	    {
		    $this->beConstructedWith($testCalculator, $testRepository);
	    }

        function it_is_initializable()
        {
            $this->shouldHaveType('Dev\Services\TestService');
        }

        function it_should_create_the_method_for_me_if_it_doesnt_exists()
        {
    	    $this->methodToBeCreated();
        }
    }

File: Dev/app/Services/TestService.php

    <?php

    /**
     * This file is a part of the phpspec test for
     * the issue #741@github.
     *
     * Date: 14 July 2015
     * Hour: 10:50
     */
 
    namespace Dev\Services;

    use Dev\Contracts\TestCalculatorInterface;
    use Dev\Contracts\TestRepositoryInterface;


    /**
     * The class being tested,
     * originally created by phpspec.
     *
     * @author Hilmi Erdem KEREN
     * @package Dev
     */
    class TestService
    {
	
        /**
         * The test repository.
         *
         * @var Dev\Contracts\Repositories\Eloquent\TestRepositoryInterface
         */
        protected $testRepository;

        /**
         * Another dependency.
         *
         * @var Dev\Contracts\Calcs\TestCalculatorInterface
         */
        protected $testCalculator;

        /**
         * Init the test service.
         *
         * @param TestCalculatorInterface $testCalculator
         * @param TestRepositoryInterface $testRepository
         */
        public function __construct(TestCalculatorInterface $testCalculator, TestRepositoryInterface $testRepository)
        {
            $this->testCalculator = $testCalculator;
            $this->testRepository = $testRepository;
        }

    }

    // End of the test class.

And here is the result when I run '$ phpspec r' from terminal:

    <?php

    /**
     * This file is a part of the phpspec test for
     * the issue #741@github.
     *
     * 

        public function methodToBeCreated()
        {
            // TODO: write logic here
        }

    Date: 14 July 2015
     * Hour: 10:50
     */
 
    namespace Dev\Services;


    use Dev\Contracts\TestCalculatorInterface;
    use Dev\Contracts\TestRepositoryInterface;
    [...]

Btw, because it created the method between comment lines, a fatal error is not triggered and phpspec endlessly asks to create the method. Like this:

    <?php

    /**
     * This file is a part of the phpspec test for
     * the issue #741@github.
     *
     * 

        public function methodToBeCreated()
        {
            // TODO: write logic here
        }



        public function methodToBeCreated()
        {
            // TODO: write logic here
        }



        public function methodToBeCreated()
        {
            // TODO: write logic here
        }

    Date: 14 July 2015
     * Hour: 10:50
     */
    [...]

**Comment by erdemkeren** [comment]
And that also continue to happen when I remove the comment at the end of file.
