### ISSUE TITLE
PHP_CodeSniffer_Exception

### ISSUE THREAD

**Issue by pc-paul** [phpspec/phpspec#742]
Getting this message when using Laravel 5.1 

This is my composer.json

    "require": {
	    	"laravel/framework": "5.1.*",
             "vlucas/phpdotenv": "~1.0",
	     	"dingo/api": "0.9.*@dev",
             "lucadegasperi/oauth2-server-laravel": "~4.0",
             "mitulgolakiya/laravel-api-generator": "1.3.*",
             "dingo/blueprint": "0.1.*@dev",
	     	"barryvdh/laravel-ide-helper": "^2.0"

	    },
	"require-dev": {
		"phpunit/phpunit": "~4.0",
		"phpspec/phpspec": "~2.0"
	},

[10-Jul-2015 17:53:37 Europe/Berlin] PHP Fatal error:  Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Class Generic_Sniffs_NamingConventions_CamelCapsFunctionNameSniff not found' in C:\xampp\php\pear\PHP\CodeSniffer\Standards\PSR1\Sniffs\Methods\CamelCapsMethodNameSniff.php:16
Stack trace:
#0 C:\xampp\php\pear\PHP\CodeSniffer.php(652): include_once()
#1 C:\xampp\php\pear\PHP\CodeSniffer.php(438): PHP_CodeSniffer->setTokenListeners('PSR1', Array)
#2 C:\xampp\php\pear\PHP\CodeSniffer\CLI.php(551): PHP_CodeSniffer->process(Array, 'PSR1', Array, false)
#3 C:\xampp\php\phpcs(37): PHP_CodeSniffer_CLI->process()
#4 {main}
  thrown in C:\xampp\php\pear\PHP\CodeSniffer\Standards\PSR1\Sniffs\Methods\CamelCapsMethodNameSniff.php on line 16

**Comment by ciaranmcnulty** [comment]
What you do to cause this stack trace?

**Comment by pc-paul** [comment]
Seems to be only when I hit a 500 error.

**Comment by ciaranmcnulty** [comment]
What makes you think it is related to PhpSpec?

**Comment by pc-paul** [comment]
You're right, sorry, long day. 
Think the issue is that PHP_CodeSniffer not compatible with current version of PhpSpec. Another user had a similar issue and it was suggested downgrading to a version of PhpSpec before 2.0. Is there still a version before 2.0 out there?

**Comment by ciaranmcnulty** [comment]
1.2 was the last stable tagged version.

You're saying this is happening when a fatal error occurs in your application? PhpSpec is not executed at that point.

**Comment by pc-paul** [comment]
If my api returns a 200, nothing written to the PHP error log. Only when I hit a 500.

**Comment by pc-paul** [comment]
Going to try with 1.2 just to see if that helps.

**Comment by ciaranmcnulty** [comment]
So you see CodeSniffer error message in your logs when you hit a 500 page and you're reporting it here because..? ;-)

**Comment by ciaranmcnulty** [comment]
I'm going to close this, please re-report if you have anything firm tying it to phpspec.

**Comment by pc-paul** [comment]
FYI, 1.2 solved my problem, but issue not with PHPsec. Thanks for your help. Sorry for wasting your time.
