### ISSUE TITLE
phpspec allows creation of namespaces with reserved words

### ISSUE THREAD

**Issue by mareg** [phpspec/phpspec#746]
Steps to reproduce:
1. Describe class `Namespace\StringCalculator`:

``` bash
$ bin/phpspec Namespace\\StringCalculator
Specification for Namespace\StringCalculator created in /home/marek/Workspace/kata/spec/Namespace/StringCalculatorSpec.php.
```
1. Run `phspec`:

```
$ bin/phpspec spec/Namespace/StringCalculatorSpec.php
0 specs
0 examples 
0ms
```

**Comment by ciaranmcnulty** [comment]
So this is because `Namespace` is a reserved word?

Rather than trying to prevent creation I think the best strategy is to show an error when this occurs (rather than skip the step)

**Comment by m1n0** [comment]
Should this throw an exception and stop the suite or just inform the user about the issue?
