### ISSUE TITLE
Can not find appropriate suite scope for class

### ISSUE THREAD

**Issue by crmpicco** [phpspec/phpspec#759]
I am just starting out with PhpSpec. When I do this:
```
bin/phpspec desc src/CRMPicco/GolfBundle/Controller/CourseGuideController
```
I get the following error:
```
  [PhpSpec\Exception\Locator\ResourceCreationException]
  Can not find appropriate suite scope for class `src/CRMPicco/GolfBundle/Controller/CourseGuideController`.
```
I created an empty `CourseGuideController` class in that directory so the class exists.

My `phpspec.yml`:
```
suites:
    CRMPiccoGolfBundle: { namespace: CRMPicco, spec_path: src/CRMPicco/GolfBundle }
```
`CourseGuideController.php`:
```
namespace CRMPicco\GolfBundle\Controller;

class CourseGuideController
{

}
```

**Comment by ciaranmcnulty** [comment]
You don't need to include the `src` prefix; the command takes the name of the Class being specified

**Comment by crmpicco** [comment]
@ciaranmcnulty Great, thanks for the quick reply.
