### ISSUE TITLE
Notice: Undefined index: HOME while running phpspec via Jenkins on Windows Server.

### ISSUE THREAD

**Issue by adamelso** [phpspec/phpspec#760]
So this is by no means fatal to running phpspec in this setup, I see the successful results of the run command. However if it's worth addressing, I get this PHP notice appear twice: once before and after execution.

> [exec] Notice: Undefined index: HOME in C:\Program Files (x86)\Jenkins\jobs\xxxx-develop\workspace\vendor\phpspec\phpspec\src\PhpSpec\Console\ContainerAssembler.php on line 265

https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Console/ContainerAssembler.php#L279

**Comment by avant1** [comment]
The same notice occurs when running phpspec using gitlab CI multi runner:

> PHP Notice:  Undefined index: HOME in D:\path\to\project\vendor\phpspec\phpspec\src\PhpSpec\Console\Application.php on line 243

The file and line are not the same because my project still uses phpspec 2.0.1 (see https://github.com/phpspec/phpspec/blob/2.0.1/src/PhpSpec/Console/Application.php#L243)

**Comment by ciaranmcnulty** [comment]
This seems solved by #796

**Comment by adamelso** [comment]
:+1:  I can confirm that since updating to 2.4, our Jenkins server no longer complains about this.

**Comment by ciaranmcnulty** [comment]
Great, thanks for confirming
