### ISSUE TITLE
Reporter truncates expected result so so that it is not readable.

### ISSUE THREAD

**Issue by lukasoppermann** [phpspec/phpspec#762]
Hey,

I get errors like this:

```
✘ should automatically add an about link
        expected [array:1] to have value "http://dev.formandsystem...." for about
        key, but found "http://dev.formandsystem....".
```

As you can imagine, this is not very handy, could you maybe add an option to not truncate at all?

**Comment by mheki** [comment]
Thanks for reporting @lukasoppermann. If you expect string and increase verbosity level (`-v`), you will see full strings compared. Looks like this doesn't work properly for arrays.
