### ISSUE TITLE
Incorrect spec file fails silently

### ISSUE THREAD

**Issue by icambridge** [phpspec/phpspec#767]
I have a file named `GuessUserTokenSpec.php` with the following content.

```php
<?php

namespace spec\Company\Bundle\ApiV6Bundle\Security\Authentication\Token;

use PhpSpec\ObjectBehavior;
use Symfony\Component\Security\Core\Authentication\Token\AbstractToken;

class GuestUserTokenSpec extends ObjectBehavior
{
    function it_is_an_authentication_token()
    {
        $this->shouldHaveType(AbstractToken::class);
    }
}
```

Which fails silently to execute because I typo'd the filename. I would like to to fail loudly.

**Comment by skyellin** [comment]
Looks like the same as this issue: https://github.com/phpspec/phpspec/issues/354

**Comment by ciaranmcnulty** [comment]
Yep I'm going to close this report on the grounds of duplication, discussion can continue on #354
