### ISSUE TITLE
Support PHP7 Exceptions in ThrowMatcher

### ISSUE THREAD

**Issue by ChadSikorra** [phpspec/phpspec#769]
Since PHP7 a new `\Throwable` interface (See https://wiki.php.net/rfc/throwable-interface) has been added. The current `ThrowMatcher` doesn't support it. For example, when trying to see if some code will throw a `\TypeError` exception, such as...

```
$this->shouldThrow(new \TypeError())->duringAdd('foobar');
```

...you will get the following message:

```
 wrong argument provided in throw matcher.
        Fully qualified classname or exception instance expected,
        Got [obj:TypeError].
```

Full qualified class name does not work either, as it only catches `\Exception`.

**Comment by ChadSikorra** [comment]
I have a fix for this I could submit, but I'm not sure what to do with the specs. Currently the spec for ThrowMatcher will not work for PHP 7 because of issue https://github.com/phpspec/phpspec/issues/659. I could adjust the specs to use phpdoc notation, but I'm not sure if that is to be the suggested route to go or if someone was working on a separate fix for that.

**Comment by ciaranmcnulty** [comment]
Someone is working on a separate fix for that, but how exactly to support specs for PHP7 features is an open question.

**Comment by ciaranmcnulty** [comment]
One workaround for now is:

```php

try {
   // code you want to test goes here

   throw new \Exception('oops you didn't throw the TypeError');
}
catch (\TypeError $e) {}

```
