### ISSUE TITLE
shouldHaveType is green when throw exception

### ISSUE THREAD

**Issue by gimler** [phpspec/phpspec#771]
When i throw a exception in my factory method all checks are green.
```
        $this->beConstructedThrough('factory', [['test', 'key']]);
        $this->shouldThrow('\InvalidArgumentException')->duringInstantiation();
        $this->shouldHaveType('Guzzle\Azure\Storage\Client');
```

I think the last one should be fail?

**Comment by stof** [comment]
well, assertions currently don't actually trigger instantiation (because of weirdness required for ``shouldThrow`` in the current implementation). So there is nothing triggering the actual instantiation here (because ``duringInstantiation`` also triggers it separately in a special way)

**Comment by ciaranmcnulty** [comment]
I don't think it should fail, the SUS does have that type (even if it's not intantiatable in a particular scenario).
