### ISSUE TITLE
Update broke existing specs

### ISSUE THREAD

**Issue by guiwoda** [phpspec/phpspec#774]
My specs had the `let()` method documented with PHPDoc syntax. After doing a `composer update`, all specs that were documente without FQCN in `@param` tags were reporting a "Class [ClassName] not found" error.

Is this parsing of the PHPDoc block in the `let()` method a new feature?
If it is, is it documented somewhere?

Cheers

**Comment by stof** [comment]
it is not a new feature. Using phpdoc to configure collaborators is available since the first (beta) release of PhpSpec 2.

**Comment by guiwoda** [comment]
Weird it never broke that spec before, then.

**Comment by ciaranmcnulty** [comment]
Currently the Annotation format requires the FQCN (and has always IIRC).
