### ISSUE TITLE
Type hint pre-generated constructors/methods

### ISSUE THREAD

**Issue by icambridge** [phpspec/phpspec#776]
I think it would be cool if we could have the methods being generated come with type hints if we know them. For example I create a mock of `CachingInterface` and I pass it to a method that is going to be generated for that method to already have the type `CachingInterface`.

**Comment by avant1** [comment]
There is an extension that implements this functionality: https://github.com/ciaranmcnulty/phpspec-typehintedmethods

[Here](https://github.com/ciaranmcnulty/phpspec-typehintedmethods#who-should-use-this) can be found reasons why is it not added to the core and link to [original discussion](https://github.com/phpspec/phpspec/issues/230).

**Comment by icambridge** [comment]
I should just search more often...
