### ISSUE TITLE
Can't test the state of objects used as arguments on method calls, that later change state

### ISSUE THREAD

**Issue by toby-griffiths** [phpspec/phpspec#789]
I've encountered the problem today, where I want to test that an injected service is called with an object as an argument, but, following this, the object is modified and then another call to the injected service is made.

The test is failing, as it appears that the expectations of the argument on the first method call are not performed until the end, by which time the object has been modified (as it's passed by reference).

Is there a way of getting this to work without cloning the object within my code, before modifying it?

I looked at cloning the argument in the Unwrapper class as shown in [this gist](https://gist.github.com/toby-griffiths/1d0e85d33f3092a42d54), which worked, however it caused (only) the following PHPSpec test to fail…

`spec/PhpSpec/Exception/ExceptionFactorySpec::85` - it creates a property not found exception.

Any ideas on how to fix or work around this would be greatly appreciated.

Thanks

**Comment by ciaranmcnulty** [comment]
Can you give an example of a test that this causes problems with, please?

**Comment by toby-griffiths** [comment]
I think I may have resolve this.  I think the problem was that I was using ->shouldBeCalled()->willReturn()

I've removed the ->shouldBeCalled() and the test behaves as expected.

I've updated the code now, but if you think it's useful, I'll dig it out of the git logs?

**Comment by ciaranmcnulty** [comment]
It would be good to have a clear reproducible case please
