### ISSUE TITLE
Object in let and object in test-statement are equal

### ISSUE THREAD

**Issue by haneev** [phpspec/phpspec#790]
I don't know whether it is a feature or a bug. But object `$currentUser` in `let` and `$newUser` in a `it_statement` are equal. 

```php
// This is just an example
class PermissionCheckSpec extends ObjectBehavior {

function let(User $currentUser) {
$user->getId()->willReturn(5);
$this->beConstructedWith($currentUser);
}

function it_should_not_work_on_another_user(User $newUser) {
$newUser->getId()->willReturn(10);
$this->isAllowed('edit', $newUser)->shouldReturn(false)
}

// Func isAllowed should do something like this
// function isAllowed($action, User $user) {
// return $action === 'edit' && $user->getId() == $this->currentUser;
// }
}
```

The problem is that `$currentUser` and `$user` are the same object. This can be checked using `spl_object_hash`. In this example this is not expected behaviour. So, it can be a bug or just the way phpspec handles objects.

**Comment by ciaranmcnulty** [comment]
They should be different, as it's determined by the argument name.

Bear in mind that `spl_object_hash` is not always correct if one object has gone out of scope...

**Comment by haneev** [comment]
When i was working on a solution, it occurred to me that my tests were not failing anymore. After trying to reproduce this bug, it seems like this is now working as i expected and it does not happens to be bug anymore. I will close this ticket.
