### ISSUE TITLE
Object have type when it does not exist.

### ISSUE THREAD

**Issue by lzakrzewski** [phpspec/phpspec#798]
It is my object:

``` php
<?php

class TestObject
{
    public function __construct()
    {
        throw new \Exception("I don't want to exist.");
    }
}
```

This is my spec:

``` php
<?php

namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class TestObjectSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType('TestObject');
    }
}
```

Test summary:

``` bash
1 specs
1 example (1 passed)
6ms
```

For me the instance of  `TestObject` was not created (because of an exeption), but for `phpspec` it have type.

Is this the expected behavior? For me this behavior is wrong and misleading.

**Comment by ciaranmcnulty** [comment]
You're correct, shouldHaveType does not trigger instantiation.

The class does exist, it's just you haven't got an example where instantiation works. It's debatable whether this is good behaviour but it is semi-intended...

**Comment by Lucaszz** [comment]
The same result with:

```php
<?php

namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class TestObjectSpec extends ObjectBehavior
{
    function it_can_be_constructed()
    {
        $this->beConstructedWith();

        $this->shouldHaveType('TestObject');
    }
}
```

```bash 
1 specs
1 example (1 passed)
8ms
```

**Comment by ciaranmcnulty** [comment]
similarly beConstructedWith doesn't cause instantiation

**Comment by krymen** [comment]
This behaviour is missleading imho. Each test should work on an instance of a class. `$this` in a test method indicates an instance not a class.

**Comment by jon-acker** [comment]
If you want to trigger the instantiation of your class, you can call $this->getWrappedObject(), this will force instantiation, but I would exactly what your use-case is apart from be able to test an throwing an exception inside the constructor, for which you can do this:
```php
namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class TestObjectSpec extends ObjectBehavior
{
    function it_throws_an_exception_during_construction()
    {
        $this->shouldThrow(new \Exception("I don't want to exist."))->duringInstantiation()
    }
}
```
