### ISSUE TITLE
getWrappedObject from Listener? (working on ZF2 extension)

### ISSUE THREAD

**Issue by Saeven** [phpspec/phpspec#804]
I know this question might have a ZF2 bias, but I'm wondering if there's a built-in means to support a bootstrapping to make the application service manager available to the tests.

In this case, if I exclude objects that depend on services, I'd be limiting my coverage to a very strong degree.

Thanks for your help.

**Comment by ciaranmcnulty** [comment]
There deliberately is not a way to couple to a specific framework component like this.

However it's something that could probably be provided by an extension (see https://github.com/magetest/magespec and https://github.com/BenConstable/phpspec-laravel for examples in other frameworks). I'm not currently aware of a Zend Framework extension.

**Comment by Saeven** [comment]
Thanks for answering so quickly Ciaran!

I've got a phpunit bootstrap, ported it over using the phpspec-laravel project you linked, and have it firing.  I'm not familiar with the innards of phpspec, but it looks to me that all I need to do now, is inject the bootstrapped service manager into the test container.

```
    /**
     * Setup the ZF2 extension.
     *
     * @param  \PhpSpec\ServiceContainer $container
     * @return void
     */
    public function load(ServiceContainer $container)
    {
        chdir(__DIR__);

        self::chroot();
        self::initAutoloader();

        $zf2ModulePaths = array(dirname(dirname(__DIR__)));

        if (($path = static::findParentPath('vendor'))) {
            $zf2ModulePaths[] = $path;
        }
        if (($path = static::findParentPath('module')) !== $zf2ModulePaths[0]) {
            $zf2ModulePaths[] = $path;
        }

        $app_config = require getcwd() . '/config/application.config.php';


        // use ModuleManager to load this module and it's dependencies
        $config = array(
            'module_listener_options' => array(
		        'config_glob_paths'    => array(
		           getcwd() .'/config/autoload/{,*.}{global,local}.php',
		        ),
		        'module_paths' => array(
		            getcwd() . '/module',
		            getcwd() . '/vendor',
		        ),
		    ),
            'modules' => $app_config['modules'],
        );

        $serviceManager = new ServiceManager(new ServiceManagerConfig());
        $serviceManager->setService('ApplicationConfig', $config);
        $serviceManager->get('ModuleManager')->loadModules();

        // how do I stuff $serviceManager this into my test container?

    }
```

The crux is on the last line there.

Is there a simple solution?

Thanks!
Alex

**Comment by Saeven** [comment]
also, can I supplant methods?  I'd need to get the service manager into whatever is returned by:
$this->getServiceLocator() within the tested classes...

Thanks again!

**Comment by Saeven** [comment]
Ok!  I worked on it a bit this weekend, admittedly after a few too many drinks!

I've got things working, with an extension here:
https://github.com/Saeven/phpspec-zf2

But there are some niceties I'd like to integrate...

For example, there are two specific calls I need to make on controller types, my tests end up looking like this:

```
<?php

namespace Spec\Application\Controller;

use PhpSpec\ZendFramework2\ZF2ObjectBehavior;
use Prophecy\Argument;

class IndexControllerSpec extends ZF2ObjectBehavior
{
    function it_returns_a_view()
    {
        $this->getWrappedObject()->setServiceLocator( $this->getServiceLocator() );
        $this->getWrappedObject()->setPluginManager( $this->getServiceLocator()->get('ControllerPluginManager'));

        $this->indexAction()->shouldReturn('Zend\View\Model\ViewModel');
    }
}
```

I thought that a listener would be appropriate, but it seems as though the getWrappedObject isn't available at the beforeSpecification event:

https://github.com/Saeven/phpspec-zf2/blob/master/src/PhpSpec/ZendFramework2/Listener/ZendFramework2Listener.php#L42

Is there any way I can tap into the wrapped object from a listener?

Thanks!
Alex

**Comment by Saeven** [comment]
Alright, I think I've got it (no drinking!).  I created objects that the specs can extend, so that I can call setup function before the views.

It'd be really nice if there were a means to modify the specification's wrapped object through a listener.  Checking through the events, it looks as though the objects that are passed in the events (e.g., beforeSpecification) don't actually impact the specification at all.

Then I could:

```
/**
     * Run the `beforeSpecification` hook.
     *
     * @param  \PhpSpec\Event\SpecificationEvent $event
     * @return void
     */
    public function beforeSpecification(SpecificationEvent $event)
    {
        $spec = $event->getSpecification();
        
        //if( the wrapped object is an instance of a controller ){
        //    perform controller setup on the wrapped object
        //}
    }

```

**Comment by Saeven** [comment]
An update, I did get one working for Zend Framework 2.
https://github.com/Saeven/phpspec-zf2
