### ISSUE TITLE
%paths.config% parameter isn't substituted

### ISSUE THREAD

**Issue by DonCallisto** [phpspec/phpspec#805]
I've notice that if a run with a different configuration then the standard one (I didn't tried with standard one to be honest, but we need to keep it elsewhere from standard path so ... ) the variable `%paths.config%` isn't substituted.

You can notice it by moving `phpspec.yml` file away from `.` and run `bin/phpspec desc Path\To\YourClass -c Path\To\Your\File`

it will alway create a folder, at `.` level, called `%paths.config%`

**Comment by shanethehat** [comment]
Which version of phpspec (and php) does this happen with?

**Comment by DonCallisto** [comment]
@shanethehat nevermind, it was an "out-dated" version of PHPSpec. I've resolved it updating the bundle :) You can close this
