### ISSUE TITLE
Discussion: Correct way for testing a method that uses a named constructor?

### ISSUE THREAD

**Issue by javierseixas** [phpspec/phpspec#810]
Hi everybody,
I know that phpspec guides through a good code design, and instantiating objects inside methods (instead of using dependecy injection) could mean some code smell, but I'm facing some doubts when working with [named constructors](http://verraes.net/2014/06/named-constructors-in-php/). I have the following classes:

```php
class User
{
    ...
    private function __construct($id, $name) { 
        $this->id = $id;
        $this->name = $name;
    }

    public static function named($name) { 
        return new self(
            Uuid::uuid4()->toString(), 
            $name
        );
    }
}

class SignUpHandler
{
    ...
    public function handle ($command)
    {
        // $command is just a DTO with an attribute $name
        $user = User::name($command->name());
        $this->myInjectedUserRepository->add($user);
    }
}
```

And I'd like to test my `SignUpHandler` with the following spec:

```php
class SignUpHandlerSpec
{
    public function it_should_add_a_user(CreateUser $command, UserRepositoryInterface $userRepository)
    {
        $name = "javier";
        $command->name()->willReturn($name);

        $user= User::named($name);

        $userRepository->add($user)->shouldBeCalled();

        $this->handle($command);
    }
}
```

When I run the spec it fails cos I'm generating a new `uuid` with each instance, so the attribute `$id` in the expected `$user` I'm generating in the spec, mismatch the created one generated during the method process.

There is any way to make it pass? Any better way to test the `handle` method or any better approach to test methods with named constructors?

Thanks for any help :)

**Comment by jon-acker** [comment]
Is the users name never accessed? Often you'd have something like a __toString() method on the User class, in which case you could have partially matched the two $user objects using
```php
$userRepository->add(Argument::which('__toString', $name)->shouldBeCalled();
```
Since you're basically want to confirm that add() was called with a User with a specific name. 

As you pointed out, since the UUID is generated on construction, there's no point in matching the two $user objects completely. If you just want to check that an object of the same type was passed, you could match using Argument::type('User')

I believe it should be possible to use a combination of the custom matcher Argument::that(callback) with Reflection to check that the passed argument matches certain criteria though I've not tried this.

**Comment by jon-acker** [comment]
Here's an example of how you can use Prophecy matchers to do this, if you *really* need to:
```php
    function it_calls_add_with_user(\TestInterface $testInterface)
    {
        $user = User::named('jon');

        $testInterface->add(Argument::that(function($arg) use ($user) {
            return $this->usersMatchOnName($arg, $user);
        }))->shouldBeCalled();

        $this->test();
    }

    private function usersMatchOnName($user1, $user2)
    {
        $nameProperty = (new \ReflectionClass(User::class))->getProperty('name');
        $nameProperty->setAccessible(true);
        return $nameProperty->getValue($user1) === $nameProperty->getValue($user2);
    }
```

**Comment by javierseixas** [comment]
Thanks @jon-acker for your suggestion and example. I didn't know it was possible to do such a things with Prophecy. I evolved your proposal and I finally coded a new `TokenInterface` implementation that would compare each property in the passed class, except the ones specified as ignorables. My spec looks like this:
```php
class SignUpHandlerSpec
{
    public function it_should_add_a_user(UserRepositoryInterface $userRepository)
    {
        $user= User::named("javier", "seixas");

        $ignorableProperties = ["id"];
        $userWrappedByIgnorable = new IgnorableExactValueToken($user, $ignorableProperties);

        $userRepository->add($userWrappedByIgnorable)->shouldBeCalled();

        $this->handle($command);
    }
}
```
And the new `ValueToken looks like this:

```php
class ExactIgnorableValueToken implements TokenInterface
{
    ...

    public function scoreArgument($argument)
    {
        $propertiesValue = (new \ReflectionObject($this->value))->getProperties();
        $propertiesArgument = (new \ReflectionObject($argument))->getProperties();

        if (count($propertiesArgument) !== count($propertiesValue)) {
            return false;
        }

        foreach ($propertiesValue as $key => $property) {
            if (in_array($property->getName(), $this->ignorableFields)) {
                continue;
            }
            $property->setAccessible(true);

            if ($property->getValue($this->value) != $property->getValue($argument)) {
                return false;
            }
        }

        return 10;
    }
}
```
With this new `ExactIgnorableValueToken`, I can reuse the logic of exact matching some fields, and ignoring that dynamic ones.

**Comment by ciaranmcnulty** [comment]
I'll close this as you have an answer
