### ISSUE TITLE
Symfony 3 Compatible Release

### ISSUE THREAD

**Issue by weaverryan** [phpspec/phpspec#811]
Hi guys!

I see the `composer.json` file has long been updated to support Symfony 3 dependencies. But, there's no stable release yet (it *is* included, however on the 2.4.0-RC1). Since that's an RC, will it be released quite soon? Symfony 3.0 is scheduled to be released early next week.

Thanks!

**Comment by GrahamCampbell** [comment]
I expect it'll be released quite soon, based on previous habits.

**Comment by weaverryan** [comment]
Indeed - previous releases seem to come 5-7 days after the RC1, which would be right now. That would be awesome (and well-planned!)

**Comment by mheki** [comment]
@ciaranmcnulty any thoughts about it?

**Comment by ciaranmcnulty** [comment]
I was aiming to have 2.4.0 released before PHP 7; I hadn't been thinking about the Symfony release cycle.

There's no reason it can't be this weekend aside from the fact I'm on vacation so may not be able to support any bugs. Given nothing has been reported in RC1 that seems low risk.

Expect a release in the next couple of days, depending on hotel wifi :-)

**Comment by weaverryan** [comment]
:+1: thanks :)

**Comment by weaverryan** [comment]
Thanks @ciaranmcnulty!
