### ISSUE TITLE
Silent loader failing in 2.4

### ISSUE THREAD

**Issue by tomphp** [phpspec/phpspec#816]
I've just installed 2.4 and found that if you have a supporting class defined in a spec file, and the supporting class either implements an undefined interface or doesn't correctly define the methods in an interface it implements - then the phpspec loader fails silently and phpspec exits with a 255 exit code.

Example: Including the following spec in your test suite will cause phpspec to fail silently and now run any tests:

```php
<?php

namespace spec;

use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

class SomethingSpec extends ObjectBehavior
{
    function it_is_initializable()
    {
        $this->shouldHaveType('Something');
    }
}

class ExampleClass implements NotDefinedInterface
{
}
```

**Comment by sroze** [comment]
@tomphp are you running the suite with PHP 5 or 7?

**Comment by tomphp** [comment]
@sroze 7 but I've tried 5 and had the same response.

**Comment by Elfiggo** [comment]
@tomphp @sroze Thanks for reporting it, I will take a look.

**Comment by Elfiggo** [comment]
Hi @tomphp would you be able to add your error_reporting level here?
It will help with the investigation?

**Comment by tomphp** [comment]
@Elfiggo it's currently set to `E_ALL`. Are you not able to reproduce? I can try and make some time to take a look at it myself if you're not able to recreate the same behaviour.

**Comment by Elfiggo** [comment]
@tomphp I have been able to reproduce.

I have used your code for the Behat scenario to prove it works. I do see the error if I use a different formatter such as the "junit" one.

The fix is in this PR https://github.com/phpspec/phpspec/pull/819

Thanks for getting back to me.

**Comment by tomphp** [comment]
@Elfiggo: Awesome! Thanks for taking the time to investigate and fix!

**Comment by ciaranmcnulty** [comment]
As 819 is now merged I'll close.
