### ISSUE TITLE
Re-runner doesn't work on Windows

### ISSUE THREAD

**Issue by chrisemerson** [phpspec/phpspec#817]
When running specs, if you are prompted to (eg) create a class or method, the re-runner fails on windows and the specs must be run again manually. I'm using git bash but the result is the same on the windows command line too.

I've tried to have a look at this myself, but there are several issues compounded and I'm having trouble working out the best way forward.

First of all, environment variables are being set in a way which isn't supported on Windows. As a result, an error appears "'PHPSPEC_EXECUTION_CONTEXT' is not recognized as an internal or external command, operable program or batch file.". You can use 'cmd /c "SET <envvar>=<envvalue> && <command>"' to get around this apparently, though for my testing I had just removed this part of the command for the moment.

After that, the command is failing because I have spaces in the path to my PHP executable which aren't being handled correctly, and I get the error "'C:\Program' is not recognized as an internal or external command, operable program or batch file.". My PHP executable is at C:\Program Files\PHP\php.exe

**Comment by avant1** [comment]
There is an existing issue for this problem: #773

**Comment by avant1** [comment]
I've started working on it, but there is a lot of failed tests on windows for now. I wanted to make existing tests pass on windows before implementing fix for this problem (CI env for windows was added in #797)

But I don't know when will I find time to work on it.

**Comment by chrisemerson** [comment]
Apologies, I did look through the list but didn't spot that.
