### ISSUE TITLE
Example tagging support

### ISSUE THREAD

**Issue by kevinnio** [phpspec/phpspec#820]
What about making possible to tag examples and later run only the ones with a specific tag? Pretty much like `rspec`. That would make easy to run parts of a suite by their own. 

I'll be glad to work on this if I found the time.

**Comment by ciaranmcnulty** [comment]
This is somewhat related to suites, I guess.

In my own usage I don't tend to want to run only part of the phpspec suite, but I'd be open to seeing example use cases
