### ISSUE TITLE
Incorrect when compares expected and actual

### ISSUE THREAD

**Issue by teclliure** [phpspec/phpspec#836]
It returns error comparing the expected and actual values but they are the same. I can see any diference using --verbose 

```
vendor/bin/phpspec run
xxxx/Condition/Group/Language/LanguageLevelCondition            
  42  - it evaluate language returns correct score less than required
      expected [double:33.333333333333], but got [double:33.333333333333].

xxxx/Lisa/Result/ResultMatrix                                         
  26  - it should build correct result matrix
      expected [array:16], but got [array:16].
```

**Comment by ciaranmcnulty** [comment]
Comparing floats is inexact, for instance

```
var_dump(10/3 * 3 == 3); // outputs false
```

Note that PHP may show fewer digits than the internal representation when printing floats, so the displayed digits may be equal but later digits may differ.

**Comment by ciaranmcnulty** [comment]
This duplicates #581 so please continue discussion there
