### ISSUE TITLE
[Discussion] (possible) Feature request to add mock/double classes with methods that are not in a parent class or interface

### ISSUE THREAD

**Issue by dstockto** [phpspec/phpspec#842]
Opening this at request of @ciaranmcnulty - 

There are a couple of use cases I could see for being able to define a new Mock/Test double class that has methods not defined in an interface or in a concrete or abstract class.

First would be to test functionality that works on "DuckTyped" classes. You could potentially define a mock for stdClass that contains the method you want it to have and then add behavior expectations that the method under test should perform certain actions against whatever was passed in as long as that object has the method(s) required.

Second, and the one I ran into recently was to build a function that would call a method only on an object that implemented a specific interface. If I pass in an double that implements the interface, everything works fine. Of course it works fine with that whether or not I test that the object passed in implements the interface or not. However, I'd like to ensure that it *only* works on objects that implement the interface, not just contain that method. What I ran into is phpspec run will blow up because it will attempt to call a non-existent method on the object I pass in if I don't have the if check. It'd be nice if I could put an expectation on that method that it should never be called which would result in a nice error in phpspec and a failed test.

Example code to test:

```
public function initialize($someObject)
{
    if ($someObject instanceOf SomeInterface) {
        $someObject->doSomething('withSomething'); 
    }
}
```

If the if is not included in the `initialize` method, the positive test works fine, but if I pass in some object that isn't an instance of SomeInterface, and doesn't have the doSomething method it blows up with a stack trace. The expectation of the non-SomeInterface class that has doSomething would allow a clean way to indicate that the method being tested doesn't pass the spec, but without crashing.

In phpunit, I'm able to mock \stdClass and add methods to it within my test. I'm interested in if the maintainers of phpspec thing this is a useful pattern (the adding of methods not defined in a class or interface, not the pattern in the sample code). I agree that there's some major issues with the sample above, but it's what I get to deal with for now. :)

**Comment by ciaranmcnulty** [comment]
For your sample code I would do the following:

```
function it_initializes_someinterfaces(SomeInterface $obj)
{
    $this->initialize($obj);
    $obj->doSomething('withSomething')->shouldHaveBeenCalled();
}

function it_initializes_other_objects(\StdClass $obj)
{
    $this->initialize($obj);
}

**Comment by dstockto** [comment]
@ciaranmcnulty I think with the second spec test, it would blow up with a stack trace saying it tried to call a non-existent method initialize on some object if the code wasn't written properly. Then any following tests are not run. I'm also interested in ensuring that it would not call the initialize method if it existed on the object but the object doesn't implement the interface. That way a check like methodExists wouldn't be sufficient. (Or potentially on the other side, testing Duck Typed objects that don't implement the interface but do have the method and ensuring the method is called).

Thank you for considering it.

**Comment by ciaranmcnulty** [comment]
It would indeed be a fatal until the code was implemented; catching fatals is a feature I'm going to implement in future.

Your other case could be done by defining a type with the method that doesn't implement the interface, and using `shouldNotBeCalled`.

This feature would have to be added to Prophecy so I suggest you raise in the phpspec/prophecy repository and we can continue discussion there.
