### ISSUE TITLE
How do we test what our objects return?

### ISSUE THREAD

**Issue by Saeven** [phpspec/phpspec#843]
I asked on SO yesterday, but looks like there isn't much presence for phpspec (which is outstanding btw, great work).

http://stackoverflow.com/questions/34915369/how-can-i-test-the-type-of-something-generated-in-my-phpspec-test

This possible, or crazy?
Thank you!!

**Comment by Luciam91** [comment]
shouldBeAnInstanceOf is what you're looking for :)

**Comment by ciaranmcnulty** [comment]
or `shouldHaveType` works too
