### ISSUE TITLE
rerun using PassthruRerunner isn't aware the shell supports colours so falls back to non-decorated 

### ISSUE THREAD

**Issue by petemcfarlane** [phpspec/phpspec#844]
Phpspec does a rerun after code generation (using the PassthruRerunner as pcntl isn't enabled). 

This in turn calls phpspec to run again with `passthru(...);` https://github.com/phpspec/phpspec/blob/54b54669a260fda4af471c867baeb680e78c7b1d/src/PhpSpec/Process/ReRunner/PassthruReRunner.php#L54

The problem is that when the Symfony Console app starts again, and the ConsoleOutput is created https://github.com/symfony/console/blob/d09af8f0c981dd381b30522e0939ad7f08c580c0/Application.php#L111

that checks if the stream supports colours
https://github.com/symfony/console/blob/d09af8f0c981dd381b30522e0939ad7f08c580c0/Output/StreamOutput.php#L53-L55

which is _false_ this time around.

We could override this by supplying an `--ansi` flag as an argument to the PassthruReRunner, if the initial ConsoleOutput is decorated, but I don't know how we should pass this to the rerunner.

**Comment by ciaranmcnulty** [comment]
It's probably not just the colours, it may also bail out of prompting for input if the stream is non-interactive too ;-/

**Comment by ciaranmcnulty** [comment]
This is because of a change in Symfony: https://github.com/symfony/console/commit/e8ccc45ab9aad790115de6943eef9c1ecfbebf99

Evidently `passthru` does not provide stderr as a TTY so we may need a different rerunner to handle these cases where `pcntl` isn't available
