### ISSUE TITLE
Is it possible to use psr-4 both for src and spec files?

### ISSUE THREAD

**Issue by luigi69** [phpspec/phpspec#847]
Hello.

Is it possible, to achive with `phpspec.yml` configuration, to handle psr-4 both for src and spec files?

Here is, what I am trying to accomplish:

```
// --------------------------------
// composer.json

...
"autoload": {
    "psr-4": {
        "App\\": "src/"
    }
},
"autoload-dev": {
    "psr-4": {
        "Test\\": "tests/"
    }
},
...


// --------------------------------
// tree

src
└── Foo
    └── Bar.php
tests
└── Spec
    └── Foo
        └── Bar.php


// --------------------------------
// src/Foo/Bar.php

<?php
namespace App\Foo;
...


// --------------------------------
// tests/Spec/Foo/Bar.php

<?php
namespace Test\Spec\Foo;
...
```

**Comment by ciaranmcnulty** [comment]
Specs are not required to be autoloadable (phpspec finds them directly). You'd achieve this by setting up `suites` in `phpspec.yml`

**Comment by ciaranmcnulty** [comment]
This may help http://www.phpspec.net/en/latest/cookbook/configuration.html#psr-4

**Comment by luigi69** [comment]
Thank You, for response, @ciaranmcnulty.

I have read the docs, of course.
I came up with following config:

```
suites:
    default:
        namespace: App
        psr4_prefix: App
        spec_prefix: Spec
        spec_path: tests
```

It seems to work, and results in expected file structure. I am however bothered with generated specs namespace: `Spec\App\Core\Foo`.

**Comment by stof** [comment]
Well, if you want the namespace ``Test\Spec`` for your specs, configure the ``spec_prefix`` accordingly.
but PhpSpec will always put the FQCN after the prefix. It won't allow to strip a prefix from the class name
