### ISSUE TITLE
it displays the wrong line number for a failed example

### ISSUE THREAD

**Issue by docteurklein** [phpspec/phpspec#848]
Let me explain:

I have a `function it_does_stuff() {}` defined line 216:

![shot](https://cloud.githubusercontent.com/assets/109846/12815196/fd095304-cb44-11e5-9fbb-b052c19772b1.png)

but phpspec displays the line 194 when I run it:

![shot](https://cloud.githubusercontent.com/assets/109846/12814968/70a1b59c-cb43-11e5-82c1-722ee4f20a9e.png)

I blindly suspect that the php7 support via on-the-fly code rewrite introduced this regression.
Not sure tho.

If that's indeed the problem, we should transport the line number from the original filename.

**Comment by docteurklein** [comment]
php7 only (from what I see).

Note that the diff corresponds to the number of lines I have for each parameter.
I suspect the rewriter to replace the 6 lines of parameters with a single (not typehinted) line.

**Comment by ciaranmcnulty** [comment]
Yes very likely. I guess the solution is for the rewrites to not collapse the white space

**Comment by kuczek** [comment]
Can be related to #858

**Comment by ciaranmcnulty** [comment]
@docteurklein does your example now work with `master`?

**Comment by ciaranmcnulty** [comment]
I'll assume this works
