### ISSUE TITLE
FatalThrowableError when phpspec is used with PHP 7

### ISSUE THREAD

**Issue by felixkiss** [phpspec/phpspec#854]
I use phpspec 2.4.1 on one of my projects.

Tests abort with the following error message using PHP 7.0.2:

```
$ phpspec run -vvv
                                 100%                                            291

  [Symfony\Component\Debug\Exception\FatalThrowableError]
  Parse error: syntax error, unexpected '.0' (T_DNUMBER), expecting ')'
```

The tests pass with PHP 5.6.17. Any ideas what this could be? The error message is not overly verbose ...

Thanks

**Comment by ciaranmcnulty** [comment]
It's a syntax error I guess? Do you have any idea which spec is causing the problem?

**Comment by felixkiss** [comment]
I did some digging. The error occurs if I mock-by-typehint `Illuminate\Support\Collection` (v5.2) like so:

```
<?php namespace spec\App;

use PhpSpec\ObjectBehavior;
use Illuminate\Support\Collection;

class FooSpec extends ObjectBehavior
{
    function let(Collection $collection)
    {
        $this->beConstructedWith($collection);
    }

    function it_is_initializable()
    {
        $this->shouldHaveType('App\Foo');
    }
}
```

```
PHP Parse error:  syntax error, unexpected '.0' (T_DNUMBER), expecting ')' in /Users/felix/code/foo-bar/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 53

Parse error: syntax error, unexpected '.0' (T_DNUMBER), expecting ')' in /Users/felix/code/foo-bar/vendor/phpspec/prophecy/src/Prophecy/Doubler/Generator/ClassCreator.php(49) : eval()'d code on line 53
```

Line 53 of the generated code looks like this:
```
public  function flatten( $depth = INF.0) {
    return $this->getProphecy()->makeProphecyMethodCall(__FUNCTION__, func_get_args());
}
```

**Comment by ciaranmcnulty** [comment]
This appears to be a PHP 7.0.2 bug that is fixed in 7.0.3...

https://3v4l.org/ngdPV

**Comment by ciaranmcnulty** [comment]
And here's the bug reference. https://bugs.php.net/bug.php?id=71314

As it only affects one PHP version I don't think we need to include a workaround

**Comment by felixkiss** [comment]
Thanks. Travis did not have `7.0.3` the last time I tried (4 days ago). Now with `7.0.3` everything works. :+1:
