### ISSUE TITLE
Can't use collaborators in PHP7

### ISSUE THREAD

**Issue by 8823-scholar** [phpspec/phpspec#861]
Using collaborators spec failed in PHP7.

### failed spec
https://travis-ci.org/samurai-fw/samurai/jobs/109525592#L1614-L1616
```
✘ Fatal error happened while executing the following 
    it inherits 
    Uncaught TypeError: Argument 1 passed to Samurai\Raikiri\Spec\Samurai\Raikiri\ContainerSpec::it_inherits() must be an instance of Samurai\Raikiri\Container, instance of PhpSpec\Wrapper\Collaborator given in /home/travis/build/samurai-fw/samurai/Samurai/Raikiri/Spec/Samurai/Raikiri/ContainerSpec.php:111
``` 

### spec code
```
class ContainerSpec extends ObjectBehavior
{
    public function it_inherits(Container $c)
    {
        // some specs, but not executed, becouse thrown TypeError ($c is Collaborator class.)
    }
}
```

**Comment by ciaranmcnulty** [comment]
Which version are you using? This was supported from `2.4.0` onwards

**Comment by ciaranmcnulty** [comment]
Never mind, I see you're using `2.4.1`. Odd

**Comment by 8823-scholar** [comment]
@ciaranmcnulty thank you for you reply.

Perhaps, is Supported pull request https://github.com/phpspec/phpspec/pull/788/files ?

**Comment by ciaranmcnulty** [comment]
Yes that is the fix.

What happens is that the specs are processed to remove the type hints before the spec is executed.

Possibly something in your configuration is stopping this process? If you can reduce it to a reproducible test case it would help a lot with debugging.

**Comment by 8823-scholar** [comment]
@ciaranmcnulty I tried somethings.

## use customized phpspec for debug
https://travis-ci.org/samurai-fw/samurai/jobs/109571981#L2948-L2955
debug print in StreamWrapper::stream_open.

### debug code
```php
        foreach (static::$specTransformers as $specTransformer) {
            $content = $specTransformer->transform($content);
            echo $content;
        }
```

### output
It seems no problem.
```php
    // actual
    public function it_gets_controller(Application $a)
    {
    }

    // output
    public function it_gets_controller( $a)
    {
        $a->config('controller.namespaces')->willReturn(['Samurai\\Console', 'Samurai\\Samurai']);
        $this->getContainer()->register('application', $a);
        $controller = $this->getController('spec');
        $controller->shouldHaveType('Samurai\Console\Controller\SpecController');
    }
```

**Comment by ciaranmcnulty** [comment]
Is it possible that your spec is being autoloaded rather than running through the transformer?

**Comment by 8823-scholar** [comment]
@ciaranmcnulty Maybe, no. Because checked using "class_exists" before ``require_once StreamWrapper::wrapPath($resource->getSpecFilename())``

```php
        foreach ($this->manager->locateResources($locator) as $resource) {
            if (!class_exists($resource->getSpecClassname(), false) && is_file($resource->getSpecFilename())) {
                require_once StreamWrapper::wrapPath($resource->getSpecFilename());
            }
        }
```

**Comment by stof** [comment]
Well, do you have an autoloader defined for your ``spec/`` folder ? even though PhpSpec avoids calling it does not mean that some other code may not trigger it earlier

**Comment by ciaranmcnulty** [comment]
Because the debug shows the transformer being triggered it is likely it's being loaded normally

**Comment by 8823-scholar** [comment]
@ciaranmcnulty very sorry. 

> your spec is being autoloaded rather than running through the transformer?

a apec is required from others spec.
I success the spec that requires use StreamWrapper::wrapPath.

https://github.com/samurai-fw/samurai/commit/50833ffd78211fd07acdd989dfee5cee06f71051
```
use PhpSpec\Loader\StreamWrapper;
require_once StreamWrapper::wrapPath(__DIR__ . DS . 'ContainerSpec.php');
```

@ciaranmcnulty @stof thanks, regard.

**Comment by ciaranmcnulty** [comment]
Ah. Unfortunately in this case the rewriting will not work :-/

I wonder whether the rewriter could do that wrapping for you?

**Comment by 8823-scholar** [comment]
@ciaranmcnulty I expended times to notice that phpspec is wrapping file read stream, ha ha ha...

> I wonder whether the rewriter could do that wrapping for you?

no. I think this case is not popular.
