### ISSUE TITLE
Catch Throwable errors

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#864]
With PHP 7 PhpSpec could continue operating after a fatal error; this has many benefits for users.

This involves finding Exception handling and switching to Throwable with some version detection.

Because this may involved switching type hints on methods it might be worth waiting for PhpSpec `3.0` but it's surely possible with hard work to implement on `2.x` without a BC break

**Comment by Elfiggo** [comment]
Will look into this

**Comment by ciaranmcnulty** [comment]
Worth validating whether this works in Php 7 / adding some test coverage for it
