### ISSUE TITLE
Rerun tests after fatal error

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#865]
On PHP 5.x, it would be good to be able to get to the end of a test suite even when fatals happen.

We now catch and present Fatals nicely; we could then prompt 'would you like to rerun the suite without this example?' and rerun everything, skipping the fatal-result spec (but presenting it as failed).

This would involve passing the list of fatal errors + reasons through the RerunContext.

Possibly some formatters could even resume output from the failure point, but that might be better as a later change

**Comment by Elfiggo** [comment]
Will look into this

**Comment by Elfiggo** [comment]
Would be worth creating an ignore-fatals option, and in doing so we print a list of scenarios and the message after a run.

We could add a new metric to the run output, something like `ignored-fatals 10` 

I suggest this as I don't see how you would cleanly manage a list, for example

Run 1 fatal. Ignore
Run 2 fatal. Ignore
Run 3 All pass

At which point would I remove the list? I still feel it would be right to highlight how many fatals were ignored so no one releases their code accidentally with fatals in.

**Comment by ciaranmcnulty** [comment]
Not sure it needs a separate config option.

On the second run you can still have the result as Fatal, just don't actually execute the failing Example.
