### ISSUE TITLE
Remove deprecated code

### ISSUE THREAD

**Issue by mheki** [phpspec/phpspec#873]
Approaching version 3.0 gives us an opportunity to remove deprecated classes:
-  `\PhpSpec\Formatter\Html\HtmlPresenter`
-  `\PhpSpec\Formatter\Presenter\PresenterInterface`
-  `\PhpSpec\Formatter\Presenter\StringPresenter`
-  `\PhpSpec\Formatter\Presenter\TaggedPresenter`

And the method:
-  `\PhpSpec\Util\Filesystem::findPhpFilesIn()`

**Comment by ciaranmcnulty** [comment]
Thanks @mheki !

**Comment by Sam-Burns** [comment]
Is this issue fixed by the pull request?
