### ISSUE TITLE
Use ::class constant instead of FQCN

### ISSUE THREAD

**Issue by Addvilz** [phpspec/phpspec#877]
I propose to move to use ::class constant instead of string class name like this.
So, instead of:
```php
$this->shouldHaveType('Some\Namespace\ClassName');
```
we could have
```php
use Some\Namespace\ClassName;
// ...
$this->shouldHaveType(ClassName::class);
```
in generator?

Does it makes sense?

**Comment by jakubzapletal** [comment]
It does make sense, but we would lost compatibility with PHP 5.3 and 5.4. As it was already discussed, phpspec 2 will keep a compatibility with PHP 5.3

**Comment by Addvilz** [comment]
So perhaps it should be for 3.0 milestone then?

**Comment by jakubzapletal** [comment]
All is discussed here #725

**Comment by Addvilz** [comment]
Okay!
