### ISSUE TITLE
Drop support for @param

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#879]
Since typehint support was added for doubles, I don't believe there's much of a use case left for supporting `@param` types in docblocks.

Perhaps this could be dropped for `3.0`?

**Comment by jakzal** [comment]
:+1: there's no need to use `@param` and it's better to have one way of doing things (from maintenance and the end user point of view).

**Comment by everzet** [comment]
Automatic conversion library would be awesome to help with migration though

**Comment by ciaranmcnulty** [comment]
@everzet great idea yes please when will you finish it? ;-)

**Comment by ciaranmcnulty** [comment]
Looking at #899 gives a bit more support for this change

**Comment by ciaranmcnulty** [comment]
Closed by #922
