### ISSUE TITLE
Not found http://www.phpspec.net

### ISSUE THREAD

**Issue by MedAhamada** [phpspec/phpspec#885]
I went to the official website http://www.phpspec.net to read the doc but it displays a not found message. Have you changed it ?

**Comment by ciaranmcnulty** [comment]
Nope! thanks for the heads up

**Comment by ciaranmcnulty** [comment]
http://phpspec.readthedocs.org/en/latest/ is still up; odd

**Comment by MedAhamada** [comment]
thanks !

**Comment by ciaranmcnulty** [comment]
I paid to renew the domain yesterday; I assume the DNS provider has screwed up somehow

**Comment by ciaranmcnulty** [comment]
I re-added `phpspec.net` to our ReadtheDocs config, and have raised an issue with them to see why it broke the way it did.

https://github.com/rtfd/readthedocs.org/issues/2067

**Comment by ciaranmcnulty** [comment]
Thanks again @MedAhamada

**Comment by MedAhamada** [comment]
Thanks ! Keep up the good work.
