### ISSUE TITLE
Segmentation fault on PHP 7

### ISSUE THREAD

**Issue by pamil** [phpspec/phpspec#886]
Hello,

last days I've implemented packages testing in Sylius, so the phpspec calls raised from one to ~70 per job. This made the bug more visible, as it seems to happen randomly.

The failing line: https://travis-ci.org/Sylius/Sylius/jobs/115837065#L2647

```sh
$ bin/phpspec --no-interaction -f dot

.................................................. 4150 / 4241
.................................................. 4200 / 4241
.........................................
747 specs
4241 examples (4241 passed)
6063ms
/home/travis/build.sh: line 45: 38987 Segmentation fault      (core dumped) bin/phpspec run --no-interaction -f dot
```

From my observations it happens only on PHP 7 and it is connected with OPCache or Travis server configuration. Running the same tests for 100 times on my local machine does not result in any error. On Travis there is PHP 7.0.4 and OPcache v7.0.6-dev.

The current OPCache configuration on our Travis:
```ini
; May help to speed up our test suites
[opcache]
opcache.enable = 1
opcache.enable_cli = 1

opcache.memory_consumption = 256
opcache.max_accelerated_files = 32531
opcache.interned_strings_buffer = 8
opcache.validate_timestamps = 0
opcache.save_comments = 1
opcache.fast_shutdown = 0 ; switching on causes "zend_mm_heap corrupted" errors
```

**Comment by GrahamCampbell** [comment]
Surely this needs reporting to PHP since this is a PHP bug?

**Comment by pamil** [comment]
@GrahamCampbell I'm not sure yet as it may be somehow connected with #884.

**Comment by stof** [comment]
@pamil segfaults are crashes in the C code, so they are bugs in PHP (even if they were not affecting the phpspec code previously). So it should be reported to the PHP team

**Comment by pamil** [comment]
@stof alright, going to report it tomorrow, thanks for help!
