### ISSUE TITLE
Reserved method names for the tested class

### ISSUE THREAD

**Issue by elcuro** [phpspec/phpspec#888]
I need to test a sample class
```
class Foo
{
    public function shouldUsersBeNotified()
    {
        return true;
    }
}

class FooSpec extends ObjectBehavior
{
    function it_returns_true()
    {
        $this->shouldUsersBeNotified()->willReturn(true);
    }
}
```
This test will fail with: 

> no usersBeNotified([array:0]) matcher found for
        [obj:Webtrh\Rating\Event\SingleRatingEvent].

Is there a way to test methods which starts with `should...`?

**Comment by jakubzapletal** [comment]
Unfortunately, all calls starting with `should` are used as an expectation.

It's defined in `\PhpSpec\Wrapper\Subject::__call`.

**Comment by MarcelloDuarte** [comment]
```
class FooSpec extends ObjectBehavior
{
    function it_returns_true()
    {
        $this->callOnWrappedObject('shouldUsersBeNotified')->shouldReturn(true);
    }
}
```
