### ISSUE TITLE
How to use PHPspec when class under test uses instanceof to check method parameters inside something other than a raw array

### ISSUE THREAD

**Issue by Harrisonbro** [phpspec/phpspec#895]
A class in my application accepts an array of objects as one of its constructor arguments and checks that the array contains only instances of a particular class. I've put a very simple example that's similar to what I'm doing in my real code. As you can see from the code and comments, my class is checking to see whether or not we've got instances of `Foo` using `instanceof` but the class is actually being given instances of `PhpSpec\Wrapper\Collaborator` so it fails. 

Interestingly, if instead of using Laravel's collection class (an array-like class with some useful methods) and pass in a raw array of the same objects given to me by PHPspec (ie. by doing `$this->beConstructedWith([$foo1, $foo2]);` instead of what's in the code sample below) it does indeed pass, and instead of being passed a set of `PhpSpec\Wrapper\Collaborator` the class is actually passed `Double\Foo\P1` and `Double\Foo\P2` instead.

So, my two questions are: 

1. Why is the behaviour of the prophecy objects PHPspec gives me different depending on whether I pass them into my class in an `array` vs. a `Collection` (ie. when using a raw array `MyClass` receives `Double\Foo\P1` but when using `Collection` it receives `PhpSpec\Wrapper\Collaborator`)?  
2. Given that I want (and sometimes need) to use `Collection` instead of a raw array can that be done with phpspec? I'm very new to PHPspec so there's a good chance I'm doing something wrong and would love to learn what that is!  

_If any authors or contributors to PHPspec read this, thank you. It's a wonderful tool, thank you for making it._

```php
use Illuminate\Support\Collection; // ← An array-like class from the Laravel framework
use PhpSpec\ObjectBehavior;
use Prophecy\Argument;

// The class I mock which is passed into MyClass
class Foo {}

// The class under test
class MyClass
{
    private $foo;
    private $bar;

    public function __construct($foos, $bar = false)
    {
        // Ensure the array we've been given contains only instances of Foo
        foreach ($foos as $foo) {
            if ( ! $foo instanceof Foo) {
                throw new \InvalidArgumentException('Not an instance of Foo');
            }
        }

        $this->foos = $foos;
        $this->bar = $bar;
    }

    public function getBar()
    {
        return $this->bar;
    }
}

// The spec tests
class MyClassSpec extends ObjectBehavior
{
    function let(Foo $foo1, Foo $foo2)
    {
        // Passing in that array-like class from the Laravel framework as the 
        // first argument. If instead I pass in a raw array the specs pass, but 
        // passing in a class which acts like  an array the specs fail saying 
        // they've got instances of \PhpSpec\Wrapper\Collaborator.
        $this->beConstructedWith(new Collection([$foo1, $foo2]));
    }

    function it_is_initializable()
    {
        $this->shouldHaveType('SolomonDashboards\MyClass');
    }

    // An unrelated question but one I'm curious about: if I remove this test 
    // example the spec passes, suggesting that it_is_initializable() doesn't 
    // actually instantiate the class under test. Why is that?
    function it_returns_false_by_default_as_bar()
    {
        $this->getBar()->shouldBe(false);
    }
}
```

**Comment by ciaranmcnulty** [comment]
Hi

PhpSpec does a lot of 'magic' around collaborators, and you've triggered an edge case where the magic breaks down.

*Short answer*

Rewrite your spec as follows:

```
$this->beConstructedWith(new Collection([
    $foo1->getWrappedObject(), 
    $foo2->getWrappedObject()
]));
```

*Long answer*

PhpSpec supports two types of collaborator interactions:

1. Testing with concrete collaborators (e.g. new Collection(), or ['a', 'b']).
2. Testing with doubles (i.e. type hinting creating Prophecy doubles).

In case 2 doubles are wrapped in Collaborator objects - this lets us call `->will*` and `->should` methods to specify stubbing and mocking behaviour. PhpSpec does some stuff under the hood to 'unwrap' these collaborator objects before the call happens.

You are passing a concrete object, that contains a concrete array, that contains some wrapped doubles - the unwrapping infrastructure can't handle this so unfortunately you have to explicitly unwrap them, as described above.

**Comment by Harrisonbro** [comment]
OK, that makes sense. Thanks for the speedy reply.

Does this mean that I can't set mocked behaviour on the `Foo` objects? I'll want to be able to do things like the example below, so does unwrapping the object given to me by return an actual instance of `Foo` or simply the double which will pass the `instanceof` guard?

Also, to check my own understanding, is it the case that the object given to me by adding a typehinted parameter to the spec method is a double wrapped in a collaborator, and that sometimes those doubles are unwrapped by phpspec before methods are called on them but I triggered a case where I added _another_ collaborator (my `Collection`) which meant phpspec couldn't unwrap the `Foo` collaborators wrapped in my `Collection` collaborator?

```
function it_counts_the_number_of_complete_foo_objects(Foo $foo1, Foo $foo2)
{
    $foo1->isComplete()->willReturn(true);
    $foo2->isComplete()->willReturn(false);
    
    $this->beConstructedWith(new Collection([
        $foo1->getWrappedObject(),
        $foo2->getWrappedObject(),
    ]));

    $this->countCompletedFoos()->shouldBe(1);
}
```

**Comment by ciaranmcnulty** [comment]
You can still mock or stub behaviour; you just have to unwrap the object manually when passing it.

**Comment by Harrisonbro** [comment]
Fantastic, I've got that working now. Thanks so much.

**Comment by Harrisonbro** [comment]
In case anyone else comes across this and wants to see the code I just used to test this out I've attached them here. You'll need to put them in the correct folders and sort out the namespaces.

[example.zip](https://github.com/phpspec/phpspec/files/210003/example.zip)

**Comment by Harrisonbro** [comment]
@ciaranmcnulty Out of interest, do you also know the answer to the second question I put in the code example? In the first code example, if I remove this test `it_returns_false_by_default_as_bar()` (so we're just left with `let()` and `it_is_initializable()` the example the spec passed even before I did the unwrapping fix, suggesting that `it_is_initializable()` doesn't actually instantiate the class under test (which also seems true since if I `die` and `var_dump` in `MyClass::__construct` I don't see anything). If that's true, why is that and what is `it_is_initializable()` actually supposed to test?

**Comment by ciaranmcnulty** [comment]
`$this->shouldHaveType('..')` specifically doesn't need to instantiate the class, but the class does have to exist.
