### ISSUE TITLE
Migration between 2.5 and 3.0

### ISSUE THREAD

**Issue by ciaranmcnulty** [phpspec/phpspec#896]
I'm opening this because there's an ongoing policy discussion across a few open PRs.

My intention was for `2.5` to be the last minor before `3.0`, and for us to feel free to break things in that transition.

@stof has advocated in a few places for us doing a `2.6` with deprecations before `3` - I'm not convinced this is needed for a project our size but would like to hear feedback on whether breaking changes between `2.5` and `3.0` without a deprecation would be an issue for anyone, especially Extension maintainers.

**Comment by GrahamCampbell** [comment]
I don't think a 2.6 release is needed.

**Comment by shanethehat** [comment]
From Magespec's point of view, a 2.6 release is unnecessary. The project is not particularly active currently anyway, but I would expect that any compatibility work would be undertaken as it has previously, against phpspec master branch, and so would be aiming for direct compatibility with 3.0.

In my mind, the point of using SemVer is that users and extension maintainers are protected from BC breaks just by using versioning correctly. I don't see much value in investing more of people's freely given time creating a deprecation release when that time could be spent on actual improvements for 3.0.

**Comment by norzechowicz** [comment]
I'm fine with 3.0 worhout 2.6 from my extensions point of view

**Comment by gnugat** [comment]
Same as all the above, spec-gen would be fine without a 2.6.

**Comment by gnugat** [comment]
I feel the need to add: as long as BC breaks are documented in an "upgrade" documentation, but I think we all implied it.

**Comment by ciaranmcnulty** [comment]
OK I've been thinking about this a lot and spoke to a few people.

I don't think at our current popularity we need to do a deprecation release - however we do need to make sure that users are aware of how to migrate from 2->3 (this is something that I felt Behat lacked).

So I'm ok with hard breaks in `3.0.0`, including in userland, as long as they're documented. We'll obviously try and minimise this but it includes:

1. Interface renaming. This will effect users who have defined custom matchers as objects
2. Configuration file changes
3. Removal of some features (I am thinking about `@param` support for instance).

To minimise the impact of these changes we should immediately start a migration guide and make sure all breaking changes are documented correctly.
