### ISSUE TITLE
Not honouring strict types (ie. not throwing expected TypeErrors for a scalar typehint)

### ISSUE THREAD

**Issue by Harrisonbro** [phpspec/phpspec#898]
Hi there. I've got a class which needs to accept a `string` parameter but am having trouble using phpspec to test the type checking behaviour when using PHP7 scalar type hints. The class and test are below. 

As you can see, I've declared `declare(strict_types=1);` in both the spec file and the class under test but when running the test in phpspec I don't get a `TypeError` despite the integer `123` being passed into a method with a `string` typehint (although I do get a `TypeError` if I run the code directly through a browser). I get the same issue when testing a normal (non-static, non-constructor) function as well.

Does anyone know what's going on here? Does the way phpspec runs method calls do something that breaks the expected PHP7 behaviour?

```php
// MyClass.php
declare(strict_types=1);

class MyClass 
{
    public static function myFactoryMethod(string $foo) 
    {
        return new static($foo);
    }

    private function __construct(string $foo) 
    {
        $this->foo = $foo;
    }
}

// MyClassSpec.php
declare(strict_types=1);

class MyClassSpec extends ObjectBehavior 
{
    function it_requires_a_string()
    {
        $this->beConstructedThrough('myFactoryMethod', [123]);
        $this->shouldThrow('\TypeError')->duringInstantiation();
    }
}
```

**Comment by stof** [comment]
This is because the call to your method ``myFactoryMethod`` is not done inside ``MyClassSpec`` but inside PhpSpec. and the PhpSpec file is not declared in strict mode (and we cannot put in it in strict mode as it would force all users to write specs in strict mode).

Note that due to the way strict types work in PHP, the TypeError is not part of the specification of your class. Strictness of the argument scalar typehint is not something chosen by your class but by the file using your class. This is the place choosing whether they want to always throw a TypeError or to let PHP cast the argument when supported.
This makes me tell that there is no point trying to support this case in PhpSpec, as it does not make sense according to the way PHP works.

**Comment by Harrisonbro** [comment]
OK, that makes sense. Agreed that phpspec can't be in strict mode.

I hadn't realised that it's the calling class that declares strict types, not the class being called (this is my first time using PHP7), so thanks for pointing that out.

In this case, then — where my class really does need to check that it's given a string as the argument and not an integer — would you suggest that I should remove the `string $foo` typehint and just check manually in `MyClass::myFactoryMethod` that `$foo` is a string (eg. just by using `is_string`)? 

Also, what does the community consider best practice around using scalar type hints? Do you just use `declare(strict_types=1);` everywhere, or ignore them completely, or something in the middle? It seems like they're somewhat dangerous since a class doesn't (and shouldn't) necessarily know where it will be called from, and if it typehints against a `string` it might inadvertently cast something to a string that it should really have thrown a `TypeError` or `InvalidArgumentException` for.

**Comment by stof** [comment]
@Harrisonbro the strict mode is defined by the file setting the value. So for arguments, it is the caller file, and for return types, it is the implementer (the rule being that the strict mode is defined by the code able to fix issues).

My own approach would be (in the future when targeting PHP 7) to typehint as a string, and let the caller decide whether casting is fine for them or no. They are the one deciding whether they want to be strict or let PHP do its magic. Your library does not care (when the argument is typehinted as a string, you will always receive a string).
This is similar to my approach for object typehints: I don't write examples testing the PHP behavior when calling it without respecting the typehint. I consider that what happens is not part of the contract of my class (it is part of the behavior of the language instead, and it is different on PHP 7 than on PHP 5 btw)

**Comment by Harrisonbro** [comment]
Yep, makes sense to me. Thanks for the advice.
