### ISSUE TITLE
Collaborators will throw exception when types in doc comments are not written fully qualified

### ISSUE THREAD

**Issue by bestform** [phpspec/phpspec#899]
If you are using a PHP IDE, it will probably create a doc comment using imports (with a use statement). Meaning, you define your collaborators in your example method signature and the types are being imported (read: not written fully qualified). When creating a doc comment for the method, the IDE will use those imports and - again - will write the types not fully qualified.

Currently, phpspec will try the type hint in the doc comment first, which it cannot resolve, as it does not have access to the reflection class when parsing the doc comment string. This will result in a ClassNotFound Exception.

If there is no doc comment, it will use the type hint in the method signature, which it can resolve using the imports.

I suggest to switch priorities here and always prefer the type written in the actual method signature, as it will always be possible to resolve it, even if it is being imported.

I have already implemented a solution with a corresponding test case. I will refer to it here.

**Comment by ciaranmcnulty** [comment]
I'm actually considering removing the docblock parsing entirely

**Comment by bestform** [comment]
Yeah, that would be an option, too :)

**Comment by ciaranmcnulty** [comment]
Your change would break backwards compatibility and we have 3.0 coming up but to be honest I don't see a use case for them since we added typehint support (pre-2.0)

**Comment by ciaranmcnulty** [comment]
See #879 by the way

**Comment by bestform** [comment]
I'll leave the PR open if you decide that it would be a good option to keep @param support while ensuring that it won't break if you are using imports

**Comment by ciaranmcnulty** [comment]
This is now closed via #922
