### ISSUE TITLE
Improvements to Installation documentation page

### ISSUE THREAD

**Issue by ifdattic** [phpspec/phpspec#907]
In my opinion the [installation page](http://www.phpspec.net/en/latest/manual/installation.html) is a bit outdated and could be improved/simplified. Here are the changes I would suggest:

* Remove the note about requiring PHP 5.3+. Or change because as far as I can tell the documentation is for the latest version and latest version requires at least 5.6
* Remove *Method #1* as only a single method is available
* Replace composer install with simple "Run the `composer require` command ....."
* Because examples in documentation use the `bin/phpspec` command add the section which tells how to change the bin directory and the documentation uses this directory. That by default the command would be at `vendor/bin/phpspec`
* Instructions for installing composer itself (the link to its installation page) could be left as is.

**Comment by ciaranmcnulty** [comment]
I agree about PHP versions.
I agree about the #1.

I'm unsure about changing all the examples to `vendor/bin/phpspec` as I always set the bin-dir, but we could indeed update the install instructions to use composer commands rather than the JSON

**Comment by ifdattic** [comment]
Might have not translated in my comment, but personally myself I think it's not worth changing all examples to `vendor/bin/phpspec`. That I'm suggesting is just a adding a section explaining that it's possible to change the directory of the executable. If we want to get even fancier we can add that you can make a bash alias to just execute with `phpspec` :)

**Comment by Sam-Burns** [comment]
Fixed in https://github.com/phpspec/phpspec/pull/919
