### ISSUE TITLE
No details about certain PHP errors showing in console output

### ISSUE THREAD

**Issue by Harrisonbro** [phpspec/phpspec#908]
Quite often when using phpspec I see console output similar to `but got [obj:Error]`, particularly when testing that something should throw an exception (so my output is something like `expected exception of class "My\Namespace\...", but got [obj:Error].`)

Is there a way to get phpspec to show me more details about the error that was shown? Currently, I'm having to go and recreate the test in the browser to get the actual error so I can fix it and carry on.

**Comment by ciaranmcnulty** [comment]
Have you tried the different verbosity settings? `-v` or `-vv` ?

**Comment by Harrisonbro** [comment]
Afraid so, it didn't change the output at all.

**Comment by ciaranmcnulty** [comment]
Thanks - I suspect what happens is that we're only riffing them if the exception type is the same - in the cases of `Error` introduced in PHP7 it's probably more important to show the message regardless.

**Comment by Harrisonbro** [comment]
Yep, that makes sense. 
Is that something that needs phpspec itself to be updated (ie. there's no configuration option or anything like that which can make it behave in the way you describe)?
If it does require an update, is there anything I can do to help with that?

**Comment by ciaranmcnulty** [comment]
Yes it's something that will need to be fixed inside PhpSpec - I would start by looking at `PhpSpec\Matcher\ThrowMatcher` (the component that handles `shouldThrow`) and its `verifyPositive` and `verifyNegative` calls.

I'm interested in encouraging new contributors so if you have time and want to help but get stuck please open other issues - I'd love to know where the roadblocks are for new contributors.

**Comment by Harrisonbro** [comment]
Thanks, have done. See https://github.com/phpspec/phpspec/pull/915 and https://github.com/phpspec/phpspec/pull/916

**Comment by ciaranmcnulty** [comment]
Let's leave this open until those PRs are merged
