### ISSUE TITLE
Verbosity (not?) working 

### ISSUE THREAD

**Issue by grunch** [phpspec/phpspec#909]
Hi, i just discovered phpspec and working with it, I found something that i think is not working quite well, correct me if i am wrong.

I am getting the same information when i run `phpspec run` and when i run `phpspec -vvv run`

**Comment by ciaranmcnulty** [comment]
What output are you expecting? If your specs are passing the output will be the same for most formatters, it's normally used for more verbose errors.

**Comment by grunch** [comment]
I think it would be great to print a message like "the example 'it is ... ...' has passed" when you ask for more verbosity

**Comment by ciaranmcnulty** [comment]
You can get different outputs by looking at different formatters, in this case `-f pretty` will get what you're after
