### ISSUE TITLE
Add -f option in phpspec command help

### ISSUE THREAD

**Issue by grunch** [phpspec/phpspec#913]
I was told there was a ´-f pretty´ option but i don't see this option in the command help or documentation

**Comment by avant1** [comment]
This is an option of `run` command of phpspec.

Try executing this in command line:

```bash
bin/phpspec run --help
```

or simply 

```bash
bin/phpspec r -h
```

Replace `bin/phpspec` with actual path to phpspec executable file.

You'll see `--format` option (with shortcut `-f`) and list of available formatters there.

This information is also available in documentation: http://www.phpspec.net/en/latest/cookbook/console.html#run-command
