### ISSUE TITLE
->willThrow() ignored when using other collaborator return values

### ISSUE THREAD

**Issue by theshaunwalker** [phpspec/phpspec#937]
Hi,
I'm having a weird bug. I'm trying to test a dependency throwing an exception but the `->willThrow()` doesnt seem to work when other collaborator return values are used as arguments to the dependency in question's collaborator method call.

Spec file snippet
```php
    function let(
        PaymentsRepository $paymentsRepository,
        PaymentSourceRepository $paymentSourceRepository
    ) {
        $this->paymentsRepository = $paymentsRepository;
        $this->paymentSourceRepository = $paymentSourceRepository;
        $this->beConstructedWith(
            $this->paymentsRepository,
            $this->paymentSourceRepository
        );
    }

    function it_creates_a_new_charge_that_isnt_on_the_system(
        StripeWebhook $webhook
    ) {
        $webhook->getMethodKey()->willReturn('stripe');
        $webhook->getResourceId()->willReturn('ch_1234');
        $this->paymentsRepository->getPaymentForMethodReference('stripe', 'ch_1234')
            ->willThrow(NoRecordsFound::class));
        $this->handleWebhook($webhook);
    }
```

Class under test
```php
    public function handleWebhook(IsAGatewayWebhook $webhook)
    {
        // lookup the local charge or create one locally
        try {
            $paymentModel = $this->paymentsRepository->getPaymentForMethodReference(
                $webhook->getMethodKey(),
                $webhook->getResourceId()
            );
            $payment = $this->paymentsSourceRepository->load($paymentModel->getId());
        } catch (NoRecordsFound $e) {
            $payment = $this->createNewPayment($webhook);
            $paymentModel = $this->paymentsRepository->getPaymentForMethodReference(
                $webhook->getMethodKey(),
                $webhook->getResourceId()
            );
        }
    }
```

The `->getPaymentForMethodReference()` call doesnt throw the `NoRecordsFound` exception like I'm trying to get it to, so the catch is never ran. PHPSpec fails the test on the `$paymentModel->getId()` call being unexpected (because it shouldnt be called as the exception is supposed to be thrown).

The weirdness of this is I tested the call using hard coded values and it gave the expected behaviour. When I put the following into the class under test (outside of the try catch to just see if PHPSpec failed on the exception) the exception is thrown correctly...
```php
$this->paymentsRepository->getPaymentForMethodreference(
    'stripe',
    'ch_1234'
);
```
PHPSpec fails correctly on "exception NoRecordsFound has been thrown".

But trying the exact same thing just swapping out the hard coded arguments for the collaborator return values. The exception doesnt get thrown.
```php
$this->paymentsRepository->getPaymentForMethodReference(
    $webhook->getMethodKey(),
    $webhook->getReferenceId()
);
```

And I've noticed that I can remove from the test, any expectation that `->getPaymentForMethodReference()->shouldBeCalled()` etc. and phpspec will still behave like it expects it to be called when using the collaborator return values as arguments.
I would expect it to fail at it being an unexpected call like:
```
unexpected call to ->getPaymentMethodForReference(exact('stripe'), exact('ch_1234'))
```
but it doesnt it acts as if the call happened as expected and moves to the next line of code.

I'm assuming this is some kind of magic at the fact is only collaborators working together or something but I dont know PHPSpec/prophecy enough.

Any clue whats going on here?

Thanks,
Shaun

**Comment by MarcelloDuarte** [comment]
try using type hinting to reuse the same double for `PaymentsRepository` at `it_creates_a_new_charge_that_isnt_on_the_system` instead of keeping a copy of it as properties of your spec using `$this->`.

```
function it_creates_a_new_charge_that_isnt_on_the_system(
        StripeWebhook $webhook, PaymentsRepository $paymentsRepository
    ) {
        $webhook->getMethodKey()->willReturn('stripe');
        $webhook->getResourceId()->willReturn('ch_1234');
        $paymentsRepository->getPaymentForMethodReference('stripe', 'ch_1234')
            ->willThrow(NoRecordsFound::class));
        $this->handleWebhook($webhook);
    }
```

**Comment by theshaunwalker** [comment]
That doesnt solve it in this instance.

I keep them as properties on the spec file purely out of writing convenience.

**Comment by theshaunwalker** [comment]
This turned out to be a case of multiple identical calls to a collaborator method clashing.

Described in this issue https://github.com/phpspec/prophecy/issues/213
