### ISSUE TITLE
Incorrect exit code on fatal error

### ISSUE THREAD

**Issue by nomysz** [phpspec/phpspec#950]
For instance you pass string instead of required object as parameter. Exit code is 0 but it should be everything but 0 becouse its "everything ok" exit code.

Then when using GitLab CI, enviroment thinks tests passed, but actually code is broken.

**Comment by ciaranmcnulty** [comment]
Can you give a specific example please?

**Comment by nomysz** [comment]
Yeah,
For example you have spec with function like this:
function it_create_json_response()
{
    $tracking = new TrackingStatusDto();
    $tracking->setStatusType(TrackingStatusTypeEnum::PICKED_UP);
    $tracking->setDate(new DateTime('2015-10-30'));

    $trackingResponse = new GetTrackingResponseDto();
    $trackingResponse->addTrackingStatus($tracking);

    $app = new Application();
    $app->register(new SerializerServiceProvider());

    $this->beConstructedWith($trackingResponse, '200', $app['serializer']);

    $this->getContent()->shouldReturn('{"trackingStatuses":[{"statusType":"PICKED_UP","date":"2015-10-30 00:00"}]}');
    $this->headers->get('Content-Type')->shouldReturn('application/json');
}
then just do something that will trigger parse error. For instance I will remove DateTime object and instead put a string

function it_create_json_response()
{
    $tracking = new TrackingStatusDto();
    $tracking->setStatusType(TrackingStatusTypeEnum::PICKED_UP);
    $tracking->setDate('2015-10-30'); // change here

    $trackingResponse = new GetTrackingResponseDto();
    $trackingResponse->addTrackingStatus($tracking);

    $app = new Application();
    $app->register(new SerializerServiceProvider());

    $this->beConstructedWith($trackingResponse, '200', $app['serializer']);

    $this->getContent()->shouldReturn('{"trackingStatuses":[{"statusType":"PICKED_UP","date":"2015-10-30 00:00"}]}');
    $this->headers->get('Content-Type')->shouldReturn('application/json');
}


Now when I run spec tests I got error in console:


div id="sf-resetcontent" class="sf-reset">
                <h1>Whoops, looks like something went wrong.</h1>
                                        <h2 class="block_exception clear_fix">
                            <span class="exception_counter">1/1</span>
                            <span class="exception_title"><abbr title="Symfony\Component\Debug\Exception\FatalThrowableError">FatalThrowableError</abbr> in <a title=".......TrackingStatusDto.php line 49" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">TrackingStatusDto.php line 49</a>:</span>
                            <span class="exception_message">Type error: Argument 1 passed to .....tTracking\TrackingStatusDto::setDate() must be an instance of DateTime, string given, called in .......esponseSpec.php on line 30</span>
                        </h2>
                        <div class="block">
                            <ol class="traces list_exception">
       <li> in <a title="/.......ponse/GetTracking/TrackingStatusDto.php line 49" ondblclick="var f=this.innerHTML;this.innerHTML=this.title;this.title=f;">TrackingStatusDto.php line 49</a></li>
       <li>at <abbr title="......TrackingStatusDto">TrackingStatusDto</abbr>->setDate('asd') in <a title="......ResponseSpec.php line 30" ondblclick="var f=this

but application response code is 0
run from console $ echo $?
0

so 0 is understanded as OK result. It should be anything but 0. When my tests are running automaticly as a part of gitlab CI that kind of response is interpreted by gitlab as passing tests and automatic testing specs is useless.

 greetsSzymon Marcinkowski
 

    On Sunday, June 19, 2016 12:56 PM, Ciaran McNulty <notifications@github.com> wrote:
 

 Can you give a specific example please?—

**Comment by m1n0** [comment]
I tried debugging the `$exitCode` variable returned by `Symfony\Component\Console::doRun` but I got `1` returned when producing similar error and `0` for successful runs as expected, both for stable 2.5 version and the current-dev master branch. I am not sure if that is what you are referring to, maybe it's a setup issue with your CI?
(Also, use format options when pasting code please, it's much easier to read, thanks)

**Comment by nomysz** [comment]
Im sory for quality of that answer. I responded to email and forgot about markdown.

I dont think its about CI configuration. I can easily replicate issue on my workstation console. Just run spec and then run in console command:

```
echo $?
```

It will return last runned application exit code and in this case it is 0 but I got stacktrace on screen mixed with phpspec output.

I think to resolve this issue spec has to catch parse error and return code 1 in this case. Correct me if I'm wrong. Do you need more info to debug?

Try this:

```
<?php

namespace spec\TestNamespace;

use PhpSpec\Silex\SilexObjectBehavior;
use Prophecy\Argument;
use Silex\Application;

class TestClassSpec extends SilexObjectBehavior
{
    function it_is_doing_something()
    {
        $this->test(new \DateTime)->shouldReturn('ok');
    }
}
```

with

```
<?php

namespace TestNamespace;

class TestClass
{
    public function test(\DateTime $dateTime)
    {
        return 'ok';
    }
}
```

and it pass ok

```
docker exec -it testcontainer_1 bin/phpspec run

      TestNamespace\TestClass

  11  ✔ is doing something


1 specs
1 examples (1 passed)
5ms
```

but then change spec into:

```
<?php

namespace spec\TestNamespace;

use PhpSpec\Silex\SilexObjectBehavior;
use Prophecy\Argument;
use Silex\Application;

class TestClassSpec extends SilexObjectBehavior
{
    function it_is_doing_something()
    {
        $this->test('invalid')->shouldReturn('ok');
    }
}
```

and it should return exit code different than 0 (which is OK) but you get stacktrace on screen and code 0 as correct execution of script.

```
      TestNamespace\TestClass

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta name="robots" content="noindex,nofollow" />
        <style>
            /* Copyright (c) 2010, Yahoo! Inc. All rights reserved. Code licensed under the BSD License: http://developer.yahoo.com/yui/license.html */
            html{color:#000;background:#FFF;}body,div,dl,dt,dd,ul,ol,li,h1,h2,h3,h4,h5,h6,pre,code,form,fieldset,legend,input,textarea,p,blockquote,th,td{margin:0;padding:0;}table{border-collapse:collapse;border-spacing:0;}fieldset,img{border:0;}address,caption,cite,code,dfn,em,strong,th,var{font-style:normal;font-weight:normal;}li{list-style:none;}caption,th{text-align:left;}h1,h2,h3,h4,h5,h6{font-size:100%;font-weight:normal;}q:before,q:after{content:'';}abbr,acr..........................................
```

debug with linux console command

```
echo $?
```

**Comment by m1n0** [comment]
I tried your example, but I had to change `class TestClassSpec extends SilexObjectBehavior` to extend `ObjectBehaviour` since I don't have your code base of course.

When everything is correct, and I run `vendor/bin/phpspec run`, all tests pass and `echo $?` prints out `0`.

When I change the spec to pass string into the test method as you suggest, test fails with 
```
vendor/bin/phpspec run
TestNamespace/TestClass
  11  - it is doing something
      error: Argument 1 passed to TestNamespace\TestClass::test() must be an instance of DateTime, string given in
      /Users/m1n0/Sites/phpspec-playground/src/TestNamespace/TestClass.php line 7

                         66%                                     33%             3
2 specs
3 examples (2 passed, 1 broken)
20ms
```
and `echo $?` prints out `1` as expected.

**Comment by ciaranmcnulty** [comment]
I suspect what is happening is that Silex has some error handler that is providing the stack trace (to show friendly error pages to users), so PhpSpec's error handling is not being triggered.

I recommend you raise this with the Silex extension (I guess this one https://github.com/lasotaartur/phpspec-silex ?) - I've not seen it before but it looks cool :-)

**Comment by jakubzapletal** [comment]
Still I think that this testing doesn't belong to phpspec as it is a low
level testing tool.

**Comment by nomysz** [comment]
@ciaranmcnulty 
Actually I'm using extension that you have mentioned. Probably extension has problems with handling such errors. I'll check that out. Thanks guys
