### ISSUE TITLE
[RFC] Support for iterators (incl. generators)

### ISSUE THREAD

**Issue by pamil** [phpspec/phpspec#954]
Hello!

Due to lack of generators support (#379), I wrote a [small extension](https://github.com/pamil/phpspec-generator-extension). However, it would be awesome to have it included in the core (looking forward to 3.0 release) :)

Iterators and generators are quite different than arrays:
 - they can be infinite
 - they can return keys that aren't just string or integer
 - keys do not have to be unique
 - generators cannot be rewinded if they were run

My use-cases have brought up the following matchers:
 - `shouldGenerateKeys(...$keys)` - I was generating a map `object => array` and only cared, if objects are in the correct order
 - `shouldGenerateValues(...$values)` - it's like `shouldReturn(['foo', 'bar'])`, but also works for infinite iterator
 - `shouldGenerate` - to assert both keys and values, two APIs:
    - `shouldGenerate(['key' => 'value1'], ['key' => 'value2'])` - for string/integer keys
    - `shouldGenerate([$object, 'value1'], [$anotherObject, 'value2'])` - for more complicated keys

The following generators assume that we want to check only the first elements, ie. `shouldGenerateValues('foo')` matches `yield 'foo'; yield 'bar';`.

Is there a need to check if given iterator has no more elements than it is matched against? `shouldExactlyGenerate`?

Is there a need to check if given iterator has no elements? `shouldGenerate*()` with no arguments?

That's all, I hope :tada: Let me know what can be improved.

**Comment by ciaranmcnulty** [comment]
I've not reviewed the code yet (because it's not a PR so it's more effort :-) ) but the behaviour as described could be useful - I'd probably try and phrase it as something more generic than generate if it covers iterators too.

The new `iterable` type makes me think that is the more generic terminoligy
