### ISSUE TITLE
Support for testing triggered error

### ISSUE THREAD

**Issue by Taluu** [phpspec/phpspec#957]
This is kind of related to #366, but not completely. IT would be nice I think to test that a call on a method triggers error messages (such as deprecations), or on construct methods (with a `duringInstanciation`).

Something along the lines of `$this->shouldTrigger(E_USER_DEPRECATED, $message)->during()` ? Unless something equivalent is already done (I've been searching but found nothing so far...) ?

**Comment by ciaranmcnulty** [comment]
I had thought that setting the `runner.maintainers.errors.level` parameter would do this?

**Comment by Taluu** [comment]
IRC, it sets the error level threshold, but it doesn't help if you want to test that the error is triggered (and which message / line / ... triggers it). Or I may have misunderstood something, which is quite possible...

IRC The errors should be transformed as exceptions on the [ErrorMaintainer](https://github.com/phpspec/phpspec/blob/master/src/PhpSpec/Runner/Maintainer/ErrorMaintainer.php), but I couldn't manage to have the result I wanted to have (I tried a `$this->throwException(ErrorException::class)->duringInstanciation()` but to no avail). Once again, I may have done something wrong.

If I am running the spec, the deprecated error is triggered (I even tried to do a simple `try { } catch (ErrorException $e) { } ` but couldn't catch it ?). But now that I'm thinkg about it, I'll need to run some other tests though, as I may have screwed up with the first tests.

I'll keep you informed. But I still think it would be a nice to have. :}

**Comment by ciaranmcnulty** [comment]
Ah, no, you're correct

**Comment by Taluu** [comment]
> If I am running the spec, the deprecated error is triggered (I even tried to do a simple `try { } catch (ErrorException $e) { } ` but couldn't catch it ?). <del>But now that I'm thinking about it, I'll need to run some other tests though, as I may have screwed up with the first tests.</del>

Nope, I'm confirming, tried the following :

```
<?php
//snippet

$this->beConstructedWith($a, $b, $c);
$this->shouldThrow(ErrorException::class)->duringInstanciation();
```

And the error was still triggered, breaking said spec with a deprecated error message.

```
Tolerance/Operation/Runner/RetryOperationRunner
  28  - it should trigger deprecation error on exception voter
      16384: Tolerance\Operation\ExceptionCatcher\ExceptionCatcherVoter is deprecated, you should implement
      Tolerance\Operation\ExceptionCatcher\ThrowableCatcherVoter instead in
      /home/talus/dev/Tolerance/src/Tolerance/Operation/Runner/RetryOperationRunner.php line 52

                       80%                             20%      5
1 specs
5 examples (4 passed, 1 broken)
117ms
```

**Comment by ciaranmcnulty** [comment]
You've spelled `instantiation` wrong...

**Comment by Taluu** [comment]
.... Okay, now it works.

Then, how about adding said `$this->shouldTrigger($level, $message)` as a helper ?
