### ISSUE TITLE
PHP 7 type hint fails if coming from a parent class or trait

### ISSUE THREAD

**Issue by hackel** [phpspec/phpspec#966]
I've just started migrating a project to php7 and noticed this strange behaviour, which seems like it's probably related to #659 and the fix in #788.

I have several classes that extend from an abstract class.  Since all of these child classes need the same dependencies, my specs each extend a base class that contains a `let` method and sets up the mocks.  This worked fine with PHP 5.6.  Now, I'm getting errors like:
`Type error: Argument 1 passed to spec\ChildSpec::let() must be an instance of SomeClass, instance of PhpSpec\Wrapper\Collaborator given`

If I copy the let() method directly into my ChildSpec class, the spec runs fine.

This will work in a pinch, but I'd like to find away to avoid this code duplication.  I tried putting the let() method into a trait, and saw the same result.  Is this something that can be fixed, or is there a better way for me to achieve this?

Edit: Using a DocBlock instead of type hinting to specify the collaborator types in the parent class seems to work to solve this.

**Comment by ciaranmcnulty** [comment]
We're not supporting this right now (or rather, we don't have a good workaround).

I'm currently considering whether it's a use case we want to support - my instinct is that it's not but I'd be interesting to know why a shared `let` is important for you

**Comment by hackel** [comment]
I'm really just using a shared let method to avoid code duplication...  That way the specs also follow the structure of the code--if the method is used in the parent class, the mocked version gets defined in the parent test class.  I want the mock to be defined the same regardless of which child class is using it.

At least that was my thinking.  If I'm missing something, please let me know!  It seems like otherwise I would just have to paste the same exact code into all of my specs.

**Comment by ciaranmcnulty** [comment]
Any more discussion can continue on #825
