### ISSUE TITLE
How to test factories/builders properly?

### ISSUE THREAD

**Issue by deeky666** [phpspec/phpspec#969]
As I could not find a "best practice" on how to test factory/builder classes I will try to find an answer here.

Consider the following classes (the scenario would be much more complex in the real world of course):

```php
class Foo
{
    private $values;
    
    public function __construct(array $values)
    {
        $this->values = $values;
    }
    
    public function get($name)
    {
        return $this->values[$name];
    }
}

class FooBuilder
{
    private $values = array();
    
    public function add($name, $value)
    {
        $this->values[$name] = $value;
        
        return $this;
    }
    
    public function build()
    {
        return new Foo($this->values);
    }
}
```

I would like to test that `FooBuilder::add()` actually adds the given value correctly and I don't know how to do this appropriately:

```php
function it_adds_values()
{
    $this->add('foo', 'bar');
    
    // expect that 'foo' with value 'bar' was added
}
```

Is phpspec even intended for testing factories/builders and if so what is the preferred strategy? The problem I have is that I cannot do expectations on `Foo` returned by `FooBuilder::build()` as it is not wrapped into a subject. The second thing that feels wrong is to do expectations on `Foo` API when I actually want to test `FooBuilder` (`Foo` API is already tested in its own Spec). Adding methods to the public API of `FooBuilder` just for testing purposes seems wrong too and is not something I intend to do.

I hope you guys can lighten me up :) Thanks!

**Comment by ciaranmcnulty** [comment]
One option is:

```
$this->build()->shouldBeLike(new Foo(['foo', 'bar']);
```

**Comment by deeky666** [comment]
Yeah this was coming to my mind, too and is also the only solution I have to this problem. But I was not sure if that is really the right thing to do. If that is a solution I can totally live with it =) In more complex scenarios where `Foo` is composed out of many different collaborators it might get messy though...

**Comment by ciaranmcnulty** [comment]
Yes, it will. You can also do:

```
$this->build()->should(function($item) {
   // some code that checks and returns boolean
}));
```

Or write your own inline matchers, but it might require you to expose state and get messy :-/

**Comment by deeky666** [comment]
Hmmm okay thanks for showing the different options. I will evaluate those and choose one :)

**Comment by ciaranmcnulty** [comment]
For what it's worth, as factories/builders get more complex you can have them delegate to smaller (mockable) factories and it helps keep the testing simpler, or just don't worry as much about them.
