### ISSUE TITLE
Expected call not recorded when collaborator is passed to tested method as a public property of a value object

### ISSUE THREAD

**Issue by brollypop** [phpspec/phpspec#971]
Hi, i wonder if this is a bug or a limitation by design: https://gist.github.com/brollypop/bce905920078a11abe552220dc69aa19

If I don't instantiate VO, and make it collaborator instead the test will pass. But I think I shouldn't have to mock value objects.

**Comment by stof** [comment]
this is because you are setting the ObjectProphecy instance in the property, not the double. So you are not calling the method on the double.

**Comment by stof** [comment]
The solution is to get the real Bar object from the Collaborator instance (it is not an ObjectProphecy as I said above, but actually a Collaborator wrapper around it).
See my latest revision in https://gist.github.com/stof/227f6d405bd71f44f3389a9a6a4699a3/revisions for the way to update your spec.

**Comment by brollypop** [comment]
Oh I see now, `i somehow missed the wrapped-objects part of the cook book. Thanks :)
