### ISSUE TITLE
shouldImplement order breaks beConstructedWith

### ISSUE THREAD

**Issue by senkal** [phpspec/phpspec#982]
Hi,
I found some weird issue with order of the matchers in phpspec.
This is a vanilla example of this:
https://github.com/senkal/phpspec-issue-example/tree/master
One entity I test: https://github.com/senkal/phpspec-issue-example/blob/master/src/Entity.php
One spec, first fails, second passes: https://github.com/senkal/phpspec-issue-example/blob/master/spec/EntitySpec.php

As you can see order in which you call should implement matters, this works:
```
        $this->shouldImplement(UserInterface::class);
        $this->beAnInstanceOf(Entity::class);
```

This fails:
```

        $this->beAnInstanceOf(Entity::class);
        $this->shouldImplement(UserInterface::class);
```
```
  16  - it is initializable this fails
      error: Argument 1 passed to Entity::__construct() must be an instance of stdClass, none given in
      /{...}/phpspec-issue-example/src/Entity.php line 10
```
Just clone my repo and run `composer install` and `vendor/bin/phpspec r`
Is it normal behaviour?

**Comment by ciaranmcnulty** [comment]
Are you conflating `shouldBeAnInstanceOf` with `beAnInstanceOf`?

**Comment by senkal** [comment]
@ciaranmcnulty Ah yes, you are right.
Silly mistake, sorry for that.
Closing.
